platform/alarms/itests/src/test/java/org/opennms/horizon/alarms/itests/CoreContainer.java
platform/alarms/itests/src/test/resources/users.properties
platform/alarms/rest/pom.xml
platform/alarms/rest/src/main/java/org/opennms/AuthenticationFailureExceptionMapper.java
platform/alarms/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/assemblies/core-dynamic-dist/src/main/resources/etc/org.apache.cxf.osgi.cfg
platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/bom/pom.xml
platform/core/pom.xml
platform/core/rest/pom.xml
platform/core/rest/src/main/java/org/opennms/rest/AuthenticationFailureExceptionMapper.java
platform/core/rest/src/main/java/org/opennms/rest/jaxrs/AnnotatedMethod.java
platform/core/rest/src/main/java/org/opennms/rest/jaxrs/RolesAllowedDynamicFeature.java
platform/core/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/docker-it/src/test/java/org/opennms/horizon/AlarmsDaemonRestTestSteps.java
platform/docker-it/src/test/resources-filtered/karaf/etc/org.apache.cxf.osgi.cfg
platform/docker-it/src/test/resources-filtered/karaf/etc/org.apache.karaf.features.cfg
platform/docker-it/src/test/resources/karaf/etc/users.properties
platform/docker-it/src/test/resources/org/opennms/horizon/alarmsd-rest.feature
platform/events/rest/pom.xml
platform/events/rest/src/main/java/org/opennms/netmgt/events/rest/internal/EventRestServiceImpl.java
platform/events/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/pom.xml

Adds JAAS Authentication and Roles validation (`@RolesAllowed`).
Adds core/rest bundle that adds both to the default Whiteboard.
Maps CXF Authentication failure to 403 instead of 500.

Add jaas auth

---

dev/README.md

updated dev/README.md with docs

---

dev/README.md

updated dev/README.md

---

local-docker-compose/kubernetes.kafka.yaml
rest-server/src/main/docker/Dockerfile
rest-server/src/main/resources/application.yml
skaffold.yaml

the local kubernetes environment for REST API server

---

dev/kubernetes.kafka.yaml
rest-server/src/main/java/org/opennms/horizon/server/filter/ResponseHeaderFilter.java
rest-server/src/main/resources/application.yml
ui/.env
ui/.env.development
ui/src/components/Alarms/AlarmsTable.vue
ui/src/directives/v-date.ts
ui/src/main.ts
ui/src/services/alarmService.ts
ui/src/services/authService.ts
ui/src/services/errorService.ts
ui/src/services/eventService.ts
ui/src/services/index.ts
ui/src/store/alarmStore.ts
ui/src/store/eventStore.ts
ui/src/types/alarms.ts
ui/src/types/events.ts
ui/src/types/index.ts
ui/src/types/mocks.ts

https://issues.opennms.org/browse/HS-31

HS-31: Add event/alarm calls

---

.github/actions/core/action.yml
.github/workflows/release.yml

.github/ - developing ci-cd

---

dev/kubernetes.kafka.yaml

Add clientScopes to Keycloak CRD

---

dev/ci-cd-test.txt

dev/ - testing ci-cd

---

local-sample/ingress.TEMPLATE.yaml
local-sample/run.sh

local-sample/ - fixes for local env build.

---

dev/kubernetes.kafka.yaml
local-sample/run.sh

updating local-sample and skaffold to work together with ui/

---

dev/README.md

TEST - github actions

---

.github/workflows/develop.yml

Jira/HS-76 - CI-CD K8s Testing with Cucumber - reset branch filtering

---

.github/workflows/develop.yml

github/ - developing workflow develop.yml

---

.github/workflows/develop.yml
.github/workflows/release.yml

Tag and Release Workflow - Add more automation and pre-testing processes

---

local-sample/run.sh

RELEASE v0.0.6-dev - testing new release workflow

---

.github/workflows/release.yml

RELEASE v0.0.7-dev - testing new release workflow

---

.github/workflows/develop.yml

jira/HS-139-tag-release-workflow - develop workflow test 6

---

.github/workflows/develop.yml
.github/workflows/release.yml

jira/HS-139-tag-release-workflow - develop workflow test 9

---

.github/workflows/develop.yml

.github/ - updated ci-cd workflow

---

platform/assemblies/features/src/main/feature/features.xml
platform/bom/pom.xml
platform/common/common-config-vars/pom.xml
platform/common/common-config-vars/src/main/java/org/opennms/configvars/ContextKey.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/EmptyScope.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/FallbackScope.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/Interpolator.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/MapScope.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/ObjectScope.java
platform/common/common-config-vars/src/main/java/org/opennms/configvars/Scope.java
platform/common/pom.xml
platform/core/config-vars/pom.xml
platform/core/config-vars/src/main/java/org/opennms/horizon/core/configvars/EntityScopeContexts.java
platform/core/config-vars/src/main/java/org/opennms/horizon/core/configvars/EntityScopeProvider.java
platform/core/config-vars/src/main/java/org/opennms/horizon/core/configvars/impl/EntityScopeProviderImpl.java
platform/core/config-vars/src/main/resources/OSGI-INF/blueprint/config-vars-blueprint.xml
platform/core/pom.xml
platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/IpInterfaceDao.java
platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/MonitoredServiceDao.java
platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/SnmpInterfaceDao.java
platform/db/dao-impl/src/main/java/org/opennms/horizon/db/dao/impl/IpInterfaceDaoHibernate.java
platform/db/dao-impl/src/main/java/org/opennms/horizon/db/dao/impl/MonitoredServiceDaoHibernate.java
platform/db/dao-impl/src/main/java/org/opennms/horizon/db/dao/impl/SnmpInterfaceDaoHibernate.java
platform/db/dao-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/pom.xml
platform/provision/service/pom.xml
platform/provision/service/src/main/java/org/opennms/netmgt/provision/detector/client/DetectorRequestBuilderImpl.java
platform/provision/service/src/main/java/org/opennms/netmgt/provision/detector/client/LocationAwareDetectorClientRpcImpl.java
platform/provision/service/src/main/resources/OSGI-INF/blueprint/horizon-provision-service.xml

Working EntitySCopeProvider; added MonitoredServiceDao and SnmpInterfaceDao impls.  Use in detector configs.  Better home for scope classes.

---

platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/provision/jdbc/pom.xml
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/AbstractJdbcDetector.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcDetector.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcDetectorFactory.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcQueryDetector.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcQueryDetectorFactory.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcStoredProcedureDetector.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/JdbcStoredProcedureDetectorFactory.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/client/JDBCClient.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/request/JDBCRequest.java
platform/provision/jdbc/src/main/java/org/opennms/netmgt/provision/detector/jdbc/response/JDBCResponse.java
platform/provision/jdbc/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/provision/pom.xml

Add JDBC detector.

---

platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/core/lib/src/main/java/org/opennms/horizon/core/lib/parameters/ParameterMapUtil.java
platform/core/lib/src/main/java/org/opennms/horizon/core/lib/poller/PollStatus.java
platform/core/lib/src/main/java/org/opennms/horizon/core/lib/timeout/TimeoutTracker.java
platform/provision/pom.xml
platform/provision/ssh/pom.xml
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/SshDetector.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/SshDetectorFactory.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/client/SshClient.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/request/NullRequest.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/response/SshResponse.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/support/ssh/AbstractPoll.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/support/ssh/InsufficientParametersException.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/support/ssh/Poll.java
platform/provision/ssh/src/main/java/org/opennms/netmgt/provision/detector/ssh/support/ssh/Ssh.java
platform/provision/ssh/src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://issues.opennms.org/browse/HS-108

Add SSH detector.

---

platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/bom/pom.xml
platform/dhcpd/pom.xml
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/Dhcpd.java
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/Transaction.java
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/impl/DhcpdImpl.java
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/impl/Listener.java
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/impl/Response.java
platform/dhcpd/src/main/java/org/opennms/horizon/dhcpd/impl/TransactionImpl.java
platform/pom.xml
platform/provision/dhcp/pom.xml
platform/provision/dhcp/src/main/java/org/opennms/netmgt/provision/detector/dhcp/DhcpDetector.java
platform/provision/dhcp/src/main/java/org/opennms/netmgt/provision/detector/dhcp/DhcpDetectorFactory.java
platform/provision/dhcp/src/main/java/org/opennms/netmgt/provision/detector/dhcp/client/DhcpClient.java
platform/provision/dhcp/src/main/java/org/opennms/netmgt/provision/detector/dhcp/request/DhcpRequest.java
platform/provision/dhcp/src/main/java/org/opennms/netmgt/provision/detector/dhcp/response/DhcpResponse.java
platform/provision/pom.xml

https://issues.opennms.org/browse/HS-105

Add the DHCP detector.

---

platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/pom.xml
platform/provision/activemq/pom.xml
platform/provision/activemq/src/main/java/org/opennms/netmgt/provision/detector/jms/ActiveMQDetector.java
platform/provision/activemq/src/main/java/org/opennms/netmgt/provision/detector/jms/ActiveMQDetectorFactory.java
platform/provision/activemq/src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://issues.opennms.org/browse/HS-102

Add ActiveMQ detector

---

platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/provision/datagram/pom.xml
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/DnsDetector.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/DnsDetectorFactory.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/NtpDetector.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/NtpDetectorFactory.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/client/DatagramClient.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/client/NtpClient.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/support/dns/DNSAddressRR.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/support/dns/DNSAddressRequest.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/support/dns/DNSInputStream.java
platform/provision/datagram/src/main/java/org/opennms/netmgt/provision/detector/datagram/support/ntp/NtpMessage.java
platform/provision/datagram/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/provision/pom.xml

https://issues.opennms.org/browse/HS-103

Add DATAGRAM detector.

---

platform/db/dao-impl/src/main/java/org/opennms/horizon/db/dao/impl/AcknowledgmentDaoHibernate.java

Use setMaxResults=1 to get single result for findLatestAckForRefId
https://issues.opennms.org/browse/HS-75

HS-75: Fix periodic error on log

---

platform/ipc/twin/grpc/subscriber/src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://issues.opennms.org/browse/HS-223
Its a small fix to complete blueprint update.

HS-223 Adjust blueprint for grpc twin subscriber.

---

.github/actions/core/action.yml
.github/actions/shared-lib/action.yml
.github/workflows/develop.yml
.github/workflows/feature-core.yml
.github/workflows/feature-rest-server.yml
.github/workflows/release.yml
rest-server/pom.xml
shared-lib/pom.xml

jira/HS-221 - added action for core and rest-server workflows to build shared-lib dependency

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/utils/TestTrustManager.java

https://issues.opennms.org/browse/HS-236

HS-236: Bypass the SSL for external IT tests

---

charts/opennms-operator/templates/operator-clusterrole.yaml
operator/internal/reconciler/opennms_reconciler.go
operator/local-instance.yaml

https://issues.opennms.org/browse/HS-147
Disable the buggy feature for now pending a future redesign in ticket [HS-232](https://issues.opennms.org/browse/HS-232)

HS-147: disable image updater pending future redesign

---

ui/src/App.vue
ui/src/components/Appliances/DeviceTable.vue

Cloud team does this a nice way without extra pckgs

HS-207: Table transition

---

dev/kubernetes.kafka.yaml
skaffold.yaml

https://issues.opennms.org/browse/HS-239
Skaffold debug has pain points, so we're bringing the ability to debug into skaffold dev. This also forwards several other ports that should be useful for developers, like for Postgres.

[HS-239] Open and port forward development ports in Skaffold

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature
platform/events/rest/src/main/java/org/opennms/netmgt/events/rest/internal/EventRestServiceImpl.java
platform/ipc/pom.xml

Validate /minions end point on horizon-stream
- https://issues.opennms.org/browse/HS-241

HS-241: Add Cucumber IT for /minions

---

external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature

Revert failing scenario
- https://issues.opennms.org/browse/HS-241

HS-241: Revert failing scenario

---

ui/mock-graphql/package.json
ui/mock-graphql/src/data/device.ts
ui/mock-graphql/src/data/minions.ts
ui/mock-graphql/src/graphql/Queries/deviceQuery.graphql
ui/mock-graphql/src/graphql/Queries/minionsQuery.graphql
ui/mock-graphql/src/helpers/random.ts
ui/mock-graphql/src/typeDefs.ts
ui/mock-graphql/yarn.lock
ui/src/App.vue
ui/src/components/Appliances/DeviceTable.vue
ui/src/components/Appliances/MinionsTable.vue
ui/src/containers/Appliances.vue
ui/src/helpers/formatting.ts
ui/src/store/Queries/minionsQueries.ts
ui/src/types/graphql-mocks.ts
ui/tests/Appliances/deviceTable.test.ts
ui/tests/Appliances/minionsTable.test.ts

Add background colour according to the metrics.
- https://issues.opennms.org/browse/HS-240-new-wf-adjustment

HS-240 Adjust to new wireframe

---

.github/actions/operator/action.yml
.github/workflows/develop.yml

HS-247: added ssh session for debugging

---

platform/db/model/src/main/java/org/opennms/horizon/db/model/OnmsNode.java
platform/db/schema-liquibase/src/main/liquibase/changelog.xml
platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/changelog.xml
platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/api/DeviceRestService.java
platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/impl/DeviceRestServiceImpl.java
platform/inventory/device/src/main/resources/OSGI-INF/blueprint/blueprint.xml
shared-lib/dto-model/src/main/java/org/opennms/horizon/shared/dto/device/DeviceDTO.java

Include the SNMP community string in the device model
- https://issues.opennms.org/browse/HS-208

HS-208 Add snmp community string to device

---

ui/mock-graphql/src/data/device.ts
ui/mock-graphql/src/helpers/random.ts
ui/src/components/Appliances/AddDeviceCtrl.vue
ui/src/components/Appliances/DeviceTable.vue
ui/src/components/Appliances/NotificationsCtrl.vue

- https://issues.opennms.org/browse/HS-255-onging-ui-mods

HS-255 ongoing UI mods

---

charts/opennms/templates/prometheus/prometheus-configmap.yaml
charts/opennms/templates/prometheus/prometheus-deployment.yaml
charts/opennms/templates/prometheus/prometheus-service.yaml
charts/opennms/templates/prometheus/pushgateway-deployment.yaml
charts/opennms/templates/prometheus/pushgateway-service.yaml
charts/opennms/values.yaml
operator/internal/handlers/prometheus.go
operator/internal/model/values/prometheus_values.go
operator/internal/model/values/values.go
operator/internal/reconciler/init.go
operator/values.yaml

Under the operator folder run the following commands
```
make copy-charts dependencies build
./operator
```
Wait for a while and run `kubectl get all -n local-instance` to verify the prometheus and pushgateway pods are created 
- https://issues.opennms.org/browse/HS-193

HS-193: TSDB DevOps

---

platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/impl/DeviceRestServiceImpl.java
platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/service/DeviceService.java
platform/inventory/device/src/test/java/org/opennms/horizon/inventory/device/service/DeviceServiceTest.java
rest-server/src/main/java/org/opennms/horizon/server/service/DeviceService.java
shared-lib/dto-model/src/main/java/org/opennms/horizon/shared/dto/device/DeviceCreateDTO.java

- https://issues.opennms.org/browse/HS-269

HS-269: Separate Device creation/retrieval DTOs

---

platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
platform/snmp/snmp4j/pom.xml

SnmpStrategy was not getting registered in karaf container.
Also fix SNMP UpTime.
- https://issues.opennms.org/browse/HS-306
* [] Documentation has been updated as necessary.

HS-306: Fix SNMP RPC failure

---

platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/impl/DeviceRestServiceImpl.java
platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/service/DeviceService.java
platform/inventory/device/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Fill up ManagementIP for get calls
- https://issues.opennms.org/browse/HS-269

HS-269: Retrieve managementIp for the node

---

platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/api/LocationRestService.java
platform/inventory/device/src/main/java/org/opennms/horizon/inventory/device/rest/impl/LocationRestServiceImpl.java
platform/inventory/device/src/main/resources/OSGI-INF/blueprint/blueprint.xml
rest-server/src/main/java/org/opennms/horizon/server/service/LocationService.java
rest-server/src/main/java/org/opennms/horizon/server/service/PlatformGateway.java
shared-lib/dto-model/src/main/java/org/opennms/horizon/shared/dto/device/LocationCollectionDTO.java

Add Rest/Graphql API to list locations
- https://issues.opennms.org/browse/HS-308

HS-308: List locations/location by id

---

ui/src/components/Appliances/DeviceTable.vue
ui/src/components/Appliances/MinionsTable.vue
ui/src/components/Appliances/appliances.helpers.ts
ui/src/store/Queries/applianceQueries.ts

- https://issues.opennms.org/browse/HS-314-device-status-metric

HS-314 Add/mod device metrics

---

ui/src/components/Appliances/appliances.helpers.ts
ui/src/store/Queries/applianceQueries.ts

- https://issues.opennms.org/browse/HS-314-device-status-metric

HS-314 Mod metric display

---

README.md

Clean up the main README, already present in the Getting Started guide.
- https://issues.opennms.org/browse/HS-315

HS-315: Remove unnecessary step from main README

---

.gitignore

Add possible `idea` folder from IntelliJ to gitignore.
- https://issues.opennms.org/browse/HS-326

HS-326: Add idea folder to gitignore

---

minion/minion-3rdParty/pom.xml
minion/minion-3rdParty/shaded-grpc/pom.xml
minion/minion-features/pom.xml
minion/minion-features/src/main/resources/features.xml
minion/minion-grpc/features/src/main/feature/feature.xml
minion/minion-ipc/echo/pom.xml
minion/minion-ipc/echo/src/main/java/org/opennms/horizon/minion/ipc/echo/EchoClient.java
minion/minion-ipc/echo/src/main/java/org/opennms/horizon/minion/ipc/echo/EchoRequest.java
minion/minion-ipc/echo/src/main/java/org/opennms/horizon/minion/ipc/echo/EchoResponse.java
minion/minion-ipc/echo/src/main/java/org/opennms/horizon/minion/ipc/echo/EchoRpcModule.java
minion/minion-observability/features/src/main/feature/feature.xml
minion/minion-taskset/features/src/main/feature/feature.xml
minion/plugins/registration/pom.xml
minion/pom.xml

One last bit of cleanup found when maven repo is purged of horizon core jars.

More cleanup needed without core in maven repo

---

dev/kubernetes.kafka.yaml

Test: start skaffold dev a couple of times without any issue.
- https://issues.opennms.org/browse/HS-343

HS-343 change the grafana init container script to check grafana db

---

ui/skaffold.yaml

Caused by an incorrect pattern that wasn't matching files properly.
- https://issues.opennms.org/browse/HS-349

HS-349: Fix Skaffold file sync for UI

---

ui/components.d.ts
ui/src/components/Appliances/Device.vue
ui/src/components/Appliances/DeviceTable.vue
ui/src/containers/Node.vue
ui/src/router/index.ts

- https://issues.opennms.org/browse/HS-346

HS-346 Add Device component and route

---

charts/opennms/templates/grafana/grafana-configmap.yaml
charts/opennms/templates/grafana/grafana-deployment.yaml
charts/opennms/templates/grafana/grafana-service.yaml
charts/opennms/templates/ingress/ingresses/opennms-ingress.yaml
charts/opennms/templates/keycloak/keycloak-realmimport.yaml
charts/opennms/templates/postgres/postgres-cred-secret.yaml
charts/opennms/templates/postgres/postgres-deployment.yaml
charts/opennms/templates/postgres/postgres-init-configmap.yaml
charts/opennms/values.yaml
operator/internal/handlers/opennms.go
operator/internal/model/values/grafana_values.go
operator/internal/model/values/postgres_values.go
operator/internal/reconciler/init.go
operator/internal/reconciler/values_updater.go
operator/scripts/install-operator-local.sh

Adding Grafana into the list of deployables for the Operator
- https://issues.opennms.org/browse/HS-249

HS-249: add Grafana into Operator

---

.github/actions/notifications/action.yml
.github/workflows/develop.yml
.github/workflows/feature-notifications.yml
.github/workflows/release.yml
notifications/pom.xml

HS-369: Added pipeline for notifications, running test

---

charts/opennms/templates/opennms/core/core-deployment.yaml
charts/opennms/values.yaml

HS-353: Added some changes that help reduce down about 1GB

---

notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyDaoImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/api/dto/PagerDutyConfigDTO.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationServiceImpl.java
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/pagerDutyConfig.xml
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyAPIImplTest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyDaoImplTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestControllerTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestIntegrationTest.java

Extra integration tests made possible after adding H2 database for the tests (with help from Liquibase)
- https://issues.opennms.org/browse/HS-358
Is a review still required when just adding extra tests?

HS-358: add extra tests

---

notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestIntegrationTest.java

Had to revert earlier PR as I mistakenly added extra work into it that had not been code reviewed. Adding these tests back in, then will create separate PR for new stuff.
- https://issues.opennms.org/browse/HS-358
none

HS-358: add extra tests back in

---

ui/src/composables/useWidgets.ts

Dynamic imports are currently only working in local dev env.
This is the first attempt to fix them in the build env.
- https://issues.opennms.org/browse/HS-395

HS-395: Fix dynamic imports

---

ui/src/composables/useWidgets.ts

Take 2 for fixing dynamic imports in prod/skaffold env
- https://issues.opennms.org/browse/HS-395

HS-395: Fix dynamic imports in prod take 2

---

ui/src/composables/useWidgets.ts

Fix dynamic imports on skaffold take 3
- https://issues.opennms.org/browse/HS-395

HS-395: Attempt to fix dynamic async imports on skaffold take 3

---

platform/3rdparty/keycloak-admin-client/src/main/java/org/opennms/keycloak/admin/client/impl/KeycloakAdminClientImpl.java
platform/core/rest/src/main/java/org/opennms/rest/jaxrs/jwt/impl/KeycloakRoleAssignmentProvider.java

- Also moves log line to a better place in the code
- https://issues.opennms.org/browse/HS-416

[HS-416] Remove Keycloak admin password from logs

---

notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java

Fix intermittent kafka test failure
I believe the failure occurs because the consumer has not been set up before the first test sends a record to the topic. Therefore the second test gets both records.
A quick google suggested the best way to await a consumer being properly assigned was to use ContainerTestUtils.waitForAssignment.
- https://issues.opennms.org/browse/HS-407
n/a

HS-407: Fix intermittent kafka test failure

---

charts/opennms/templates/ingress/ingresses/opennms-ingress.yaml
charts/opennms/templates/ingress/nginx-controller/controller-deployment.yaml
charts/opennms/templates/ingress/nginx-controller/controller-service.yaml
charts/opennms/values.yaml

- Allows config of ingress port numbers in Helm chart, enables local dev
- Does not include operator changes.
- https://issues.opennms.org/browse/HS-370

[HS-370] Allow configuration of port numbers for ingress-nginx controller in Helm chart

---

charts/opennms-operator/crds/opennms.yaml
charts/opennms-operator/values.yaml
charts/opennms/templates/ingress/jobs/job-createsecret.yaml
charts/opennms/templates/ingress/jobs/job-patchwebhook.yaml
charts/opennms/templates/ingress/nginx-controller/controller-deployment.yaml
charts/opennms/templates/ingress/nginx-controller/controller-service.yaml
charts/opennms/values.yaml
operator/api/v1alpha1/opennms_types.go
operator/internal/handlers/postgres.go
operator/internal/model/values/ingress_values.go
operator/internal/model/values/values.go
operator/internal/util/crd/crd_to_values.go
operator/scripts/create-kind-cluster.sh
operator/scripts/kind-config.yaml
operator/scripts/local-onms-instance.yaml

Exposing the ability to customise the ports an ONMS instance is exposed on through the CRD
Some aditional related clean up as well. 
- https://issues.opennms.org/browse/HS-420

HS-420: custom ports through the CRD; a bit more cleanup

---

ui/.gitignore
ui/components.d.ts
ui/src/components/Appliances/NotificationsCtrl.vue
ui/src/graphql/Notifications/pagerDuty.graphql
ui/src/store/Mutations/notificationMutations.ts
ui/src/types/graphql.ts
ui/tests/Appliances/notificationsCtrl.test.ts

Adds mutation for pager duty integration key
- https://issues.opennms.org/browse/HS-234

HS-234: Add pagerduty integration key mutation

---

charts/opennms/templates/kafka/kafka-deployment.yaml
charts/opennms/templates/postgres/postgres-cred-secret.yaml

Fixing a couple connection issues relating to Postgres and Kafka

Fix postgres and kafka connections

---

keycloak-ui/themes/horizon-stream/common/resources/css/style.css
keycloak-ui/themes/horizon-stream/login/resources/js/gradient.js

Fixes login gradient
- https://issues.opennms.org/browse/HS-388

fix choppy gradient

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/router/MinionLookupServiceImpl.java
minion-gateway/main/src/test/java/org/opennms/miniongateway/router/MinionLookupServiceImplTest.java

The new MinionLookupService in Minion Gateway has possible race condition when a location is new. This addresses the issue by creating a synchronization lock on the location key using the  Ignite Cache api.

Fixing race condition by locking cache on location key

---

skaffold.yaml

- Previous PR didn't disable all tests, some flags were missing
- Also removes unused profile
- https://issues.opennms.org/browse/HS-454

[HS-454] Prevent certain other tests from running on minion when --skip-tests flag is used

---

platform/assemblies/features/src/main/feature/features.xml
platform/pom.xml

Signed-off-by: Łukasz Dywicki <luke@code-house.org>

Fix failing build caused by grpc/protobuf version skew.

---

minion/minion-grpc/grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
minion/minion-taskset/taskset-scheduler/src/main/resources/OSGI-INF/blueprint/scheduler.xml
minion/minion-taskset/taskset-worker/src/main/resources/OSGI-INF/blueprint/horizon-ignite.xml

Cleaning up blueprint config so they are consistent per our discussions:
- standard bluepint properties defined in <cm> tags
- use dot notation for complex properties
- Can be overridden using this approach with ENV vars: https://karaf.apache.org/manual/latest/#_environment_variables_system_properties

Cleaning up blueprint configs for consistency

---

minion/minion-3rdParty/shaded-ignite/pom.xml
minion/pom.xml
parent-pom/pom.xml
platform/3rdparty/ignite/pom.xml
platform/core/monitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/pom.xml
tools/CORE.bash
tools/CORE.ssh

This PR fixes reconnection issues ignite thin client has. This affects in severe way core if minion-gateway is restarted or scaled.
Additional follow up commit contains fixes for helper scripts used for development purposes.

Update ignite to 2.14 release

---

platform/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Minor configuration update to point stats endpoint to the stats.opennms.org/datachoices endpoint correctly
- https://issues.opennms.org/browse/HS-463

HS-463: Update stats endpoint to point correctly

---

charts/opennms/templates/kafka/kafka-deployment.yaml
charts/opennms/templates/kafka/kafka-service.yaml
charts/opennms/values.yaml
operator/internal/handlers/keycloak.go
operator/internal/model/values/kafka_values.go

Opening up an extra listener on the kafka deployment to allow for port-forwarded local development
- https://issues.opennms.org/browse/HS-474

HS-474: adding an extra listener to kafka for local development

---

charts/opennms-operator/crds/opennms.yaml
charts/opennms/templates/keycloak/keycloak-deployment.yaml
operator/api/v1alpha1/opennms_types.go
operator/api/v1alpha1/zz_generated.deepcopy.go
operator/internal/model/values/keycloak_values.go
operator/internal/reconciler/opennms_reconciler.go
operator/internal/reconciler/resource_updater.go
operator/internal/util/crd/crd_to_values.go
operator/scripts/local-onms-instance.yaml

Making the Minion Gateway configurable through the CRD
- https://issues.opennms.org/browse/HS-488

HS-488: add the Minion gateway to the CRD

---

build-tools/basic/compile.sh
build-tools/basic/destroy-cluster.sh
build-tools/basic/helm-values.yaml
build-tools/basic/mk-docker-images.sh
build-tools/basic/push-images-to-kind.sh
build-tools/basic/run-cluster.sh
build-tools/basic/run-port-forwards.sh
build-tools/basic/stop-dev-pods.sh
tools/CORE.list-minions
tools/MINION.add-ssh

Update the basic build tools.

---

.github/workflows/feature-notifications.yml
charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/core/core-deployment.yaml
charts/opennms/templates/opennms/notification/notification-deployment.yaml
notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyDao.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyDaoImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/config/SecurityConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/config/keycloak/KeycloakDeploymentHelper.java
notifications/src/main/java/org/opennms/horizon/notifications/config/keycloak/KeycloakRolesHelper.java
notifications/src/main/java/org/opennms/horizon/notifications/config/keycloak/KeycloakTokenFilter.java
notifications/src/main/java/org/opennms/horizon/notifications/config/test/TestSecurityConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/exceptions/NotificationException.java
notifications/src/main/java/org/opennms/horizon/notifications/rest/NotificationRestController.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationServiceImpl.java
notifications/src/main/resources/application.yml
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTestNoConfig.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestControllerTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestIntegrationTest.java
notifications/src/test/resources/application.yml
rest-server/src/main/resources/application.yml
rest-server/src/test/resources/application.yml

Add security for notifications to protect REST endpoint
- https://issues.opennms.org/browse/HS-404
n/a

HS-404: Add security for notifications

---

.github/workflows/develop.yml

Add Inventory to github workflow, to make it run in the develp github actions

HS-465: Add Inventory to github workflow

---

charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
operator/internal/handlers/opennms.go
operator/internal/model/values/opennms_values.go
operator/internal/reconciler/resource_updater.go

Added the Metrics Processor service to the operator
Fixed and improved the conditionals controlling whether the operator attempted to update a resource or not. 
- https://issues.opennms.org/browse/HS-491
- https://issues.opennms.org/browse/HS-494

HS-491/494: add metrics processor; fix update conditions

---

.github/actions/metrics-processor/action.yml
.github/workflows/develop.yml
.github/workflows/feature-metrics-processor.yml
.github/workflows/release.yml
install-local.sh

HS-502 - added metrics-processor to ci-cd pipeline and install-local.sh

---

inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/ip-interface.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitored-service-type.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitored-service.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitoring-locations.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitoring-systems.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/node.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/snmp-interface.xml

Adding initial liquibase schemas as discussed in the meetings.
Have intentionally not included the indexes, in favour of adding indexes where required. 
Or we may have another call about this.
- https://issues.opennms.org/browse/HS-498

HS-498: Add Initial Inventory Liquibase Schemas

---

charts/opennms-operator/crds/opennms.yaml
charts/opennms/templates/grafana/grafana-secret.yaml
charts/opennms/values.yaml
install-local-onms-instance.yaml
operator/api/v1alpha1/opennms_types.go
operator/api/v1alpha1/zz_generated.deepcopy.go
operator/internal/model/values/values.go
operator/internal/reconciler/instance_updater.go
operator/internal/util/crd/crd_to_values.go
operator/scripts/local-onms-instance.yaml
skaffold-helm-values.yaml

Fix HS-506
- https://issues.opennms.org/browse/HS-506

Fix grafana sso config [wip]

---

charts/opennms/values.yaml
minion/docker-assembly/src/main/docker/app/Dockerfile

a couple misc. fixes related to deployment, see commits for details

misc deployment fixes

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoredServiceTypeMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoredServiceType.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoredServiceTypeRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceTypeService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringLocationService.java
shared-lib/inventory/src/main/proto/opennms/monitoredServiceType.proto

add Monitored Service Type to Inventory
n/a

HS-470: add Monitored Service Type to Inventory

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/NodeMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoringLocation.java
inventory/src/main/java/org/opennms/horizon/inventory/model/Node.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/ControllerExceptionHandler.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/MonitoredServiceTypeRest.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/NodeRest.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceTypeService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/test/java/org/opennms/horizon/inventory/MonitoredServiceTypeIntegrationTest.java
inventory/src/test/java/org/opennms/horizon/inventory/MonitoringLocationIntegrationTest.java
inventory/src/test/java/org/opennms/horizon/inventory/NodeIntegrationTest.java
shared-lib/inventory/src/main/proto/opennms/node.proto

Add Node to Inventory.
Also tests for MonitoringServiceTypes which I seem to have missed from last PR.
n/a

HS-470: Add Node to Inventory

---

ui/src/components/Appliances/DevicesTable.vue
ui/src/components/Appliances/MinionsTable.vue
ui/src/components/Appliances/utils.ts
ui/src/types/index.ts
ui/tests/Appliances/devicesTable.test.ts

HS-437 Fix build fail

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoredServiceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoredService.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoredServiceRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/MonitoredServiceRest.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoredServiceService.java
inventory/src/test/java/org/opennms/horizon/inventory/MonitoredServiceIT.java
shared-lib/inventory/src/main/proto/opennms/monitoredService.proto

Add MonitoredService into Inventory
none

HS-470: Add MonitoredService into Inventory

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/IpInterfaceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/SnmpInterfaceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoredService.java
inventory/src/main/java/org/opennms/horizon/inventory/model/SnmpInterface.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/SnmpInterfaceRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/SnmpInterfaceRest.java
inventory/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/SnmpInterfaceService.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/test/java/org/opennms/horizon/inventory/SnmpInterfaceIT.java
shared-lib/inventory/src/main/proto/opennms/snmpInterface.proto

Add SnmpInterface to Inventory
none

HS-470: Add SnmpInterface to Inventory

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoringSystemMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/MonitoringSystem.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoringSystemRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/rest/MonitoringSystemRest.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/test/java/org/opennms/horizon/inventory/MonitoringSystemIT.java
shared-lib/inventory/src/main/proto/opennms/monitoringSystem.proto

Add MonitoringSystem into Inventory
none

HS-470: Add MonitoringSystem into Inventory

---

inventory/src/test/java/org/opennms/horizon/inventory/grpc/GrpcIntegrationTest.java

- https://issues.opennms.org/browse/HS-471

HS-471 :fix unit tests

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/tasks/EchoRoutingTask.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TaskSetTwinMessageProcessor.java

Minion Gateway security hotspots fixes
- https://issues.opennms.org/browse/HS-547

HS-547: SonarCloud - Minion Gateway security hotspots fixes

---

events/src/main/resources/db/changelog/hs-0.1.0/tables/event.xml
shared-lib/events/pom.xml
shared-lib/events/src/main/proto/events.proto
shared-lib/pom.xml

Add events proto file
- https://issues.opennms.org/browse/HS-545

HS-545: Add events proto

---

ui/src/components/Common/PageHeader.vue
ui/src/components/Layout/NavigationRail.vue
ui/src/containers/Inventory.vue
ui/src/router/index.ts
ui/tests/Common/PageHeader.test.ts

- https://issues.opennms.org/browse/HS-538-inventory-page

HS-538 Add inventory page header

---

ui/src/components/Appliances/DevicesTable.vue
ui/src/components/Appliances/MinionsTable.vue
ui/src/components/Appliances/utils.ts

- https://issues.opennms.org/browse/HS-437-graph-device

HS-437 Change to shorted human-readeable duration metric

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/rpcrequest/impl/RpcRequestRouterImpl.java
minion-gateway/main/src/test/java/org/opennms/miniongateway/grpc/server/rpcrequest/impl/RpcRequestRouterImplTest.java
minion-gateway/main/src/test/java/org/opennms/miniongateway/rpcrequest/service/RpcRequestGrpcServiceTest.java
minion-gateway/main/src/test/resources/log4j2.xml
minion-gateway/main/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
minion-gateway/rpc-request-server/src/main/java/org/opennms/miniongateway/rpcrequest/service/RpcRequestGrpcService.java
platform/rpc-request-client/pom.xml
platform/rpc-request-client/src/main/java/org/opennms/horizon/core/rpc/request/client/RpcRequestGrpcClient.java
platform/rpc-request-client/src/test/java/org/opennms/horizon/core/rpc/request/client/RpcRequestGrpcClientFactoryTest.java
platform/rpc-request-client/src/test/java/org/opennms/horizon/core/rpc/request/client/RpcRequestGrpcClientTest.java
platform/rpc-request-client/src/test/resources/log4j2.xml
platform/rpc-request-client/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Unit testing for GRPC between core and Minion Gateway.

---

minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/TaskExecutionResultProcessor.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/TaskExecutorLocalServiceFactory.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutionResultProcessorImpl.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorIgniteService.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalDetectorServiceImpl.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalServiceFactoryImpl.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskSetLifecycleManagerImpl.java
minion/minion-taskset/taskset-worker/src/main/resources/OSGI-INF/blueprint/horizon-ignite.xml
minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpDetector.java
minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpDetectorManager.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceDetector.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceDetectorManager.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceDetectorResponse.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceDetectorResponseImpl.java
minion/plugins/plugins-api/src/test/java/org/opennms/horizon/minion/plugin/api/registries/AlertingPluginRegistryTest.java
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpDetector.java
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpDetectorManager.java
minion/plugins/snmp-plugin/src/main/resources/OSGI-INF/blueprint/snmp-plugins.xml
minion/plugins/snmp-plugin/src/test/java/org/opennms/horizon/minion/snmp/SnmpDetectorTest.java
platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/taskset/TaskSetManagerUtil.java
shared-lib/protobuf/src/main/proto/snmp.proto
shared-lib/protobuf/src/main/proto/taskSet.proto

HS-558: Implement SNMP Detector on Minion
- https://issues.opennms.org/browse/HS-558

HS-558: Implement SNMP Detector on Minion

---

charts/opennms/templates/keycloak/keycloak-realm-configmap.yaml

Introduction of tenant claim into access token generated for UI. Intended for further consumption by backend services.

Inject 'tenant' attribute into ui access token

---

inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringLocationGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcService.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java

Based on the UI team's comments, keep the API name consistent and fixed the gRPC channel closed error.
- https://issues.opennms.org/browse/HS-600

HS-600: QuickFix : change the API name to keep consistence

---

ui/src/styles/_statusBackground.scss

HS-615 Fix chip text color

---

inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/NodeMapper.java
shared-lib/inventory/src/main/java/org/opennms/horizon/inventory/Constants.java

How to test: Creating a new node without location should success and assigned with the default location
- https://issues.opennms.org/browse/HS-623

HS-623 Use default location when create new node without the location specified

---

rest-server/src/main/java/org/opennms/horizon/server/config/DataLoaderFactory.java

Fixed the location data loader key size error. 
- https://issues.opennms.org/browse/HS-629

HS-629 fix data loader key size exception.

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/IpInterfaceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoredServiceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoredServiceTypeMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoringLocationMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoringSystemMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/NodeMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/SnmpInterfaceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/Node.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/IpInterfaceMapper.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/NodeMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/IpInterface.java
shared-lib/inventory/src/main/proto/nodeService.proto

Return IpInterfaces with Nodes.
- https://issues.opennms.org/browse/HS-631

HS-631: Add IpInterfaces to Nodes 

---

rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLNodeServiceTest.java

- https://issues.opennms.org/browse/HS-635

HS-635 Add GraphQL endpoints/dataloader tests

---

charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/events/events-deployment.yaml
charts/opennms/templates/opennms/events/events-service.yaml
charts/opennms/values.yaml
events/grpc/pom.xml
events/grpc/src/main/java/org/opennms/horizon/events/grpc/config/EventServerInterceptor.java
events/grpc/src/main/java/org/opennms/horizon/events/grpc/config/GrpcConfig.java
events/grpc/src/main/java/org/opennms/horizon/events/grpc/config/GrpcTenantLookupImpl.java
events/main/src/main/resources/application.yml
operator/internal/model/values/opennms_values.go
platform/docker-it/pom.xml
rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/EventMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/events/Event.java
rest-server/src/main/java/org/opennms/horizon/server/model/events/EventInfo.java
rest-server/src/main/java/org/opennms/horizon/server/model/events/EventParameter.java
rest-server/src/main/java/org/opennms/horizon/server/model/events/SnmpInfo.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcEventService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/EventsClient.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/main/resources/application.yml
rest-server/src/test/resources/application.yml
shared-lib/events/pom.xml
shared-lib/events/src/main/java/org/opennms/horizon/events/Constants.java

HS-361: Add GQL endpoints to get events
Saved some test data to the database and tested with the following GraphQL requests:
1. findAllEvents
Request:
```
query {
findAllEvents {
id,
tenantId,
uei,
nodeId,
ipAddress,
producedTime,
eventParams {
name,
value,
type,
encoding
},
eventInfo {
snmp {
id,
version,
community,
generic,
trapOid,
generic
}
}
}
}
```
Response:
```
{
"data": {
"findAllEvents": [
{
"id": 1,
"tenantId": "opennms-prime",
"uei": "uei",
"nodeId": 1,
"ipAddress": "192.168.1.1",
"producedTime": 1669908409482,
"eventParams": [
{
"name": "ifIndex",
"value": "64",
"type": "int32",
"encoding": "encoding"
}
],
"eventInfo": {
"snmp": {
"id": "snmp",
"version": "",
"community": "public",
"generic": 34,
"trapOid": "0.0.1.2"
}
}
},
{
"id": 2,
"tenantId": "opennms-prime",
"uei": "uei", …
```

HS-361: Add GQL endpoints to get events 

---

inventory/src/main/java/org/opennms/horizon/inventory/grpc/InventoryServerInterceptor.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcService.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/LocationGrpcIntegrationTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/LocationGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/repository/MonitoringLocationRepoTest.java
inventory/src/test/java/org/opennms/horizon/inventory/repository/MonitoringSystemRepositoryTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java

Fix a few sonar code smells
- https://issues.opennms.org/browse/HS-646
n/a

HS-646: fix inventory sonar code smells

---

Tiltfile

changing port forward conflicts on new alarm service

Fixing port forward conflicts

---

operator/internal/handlers/opennms.go
operator/internal/model/values/opennms_values.go

New service was added that was breaking the operator's pipeline
- https://issues.opennms.org/browse/HS-656

HS-656: add the Minion Gateway gRPC Gateway to the Operator

---

minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/MinionManager.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/rpcstreaming/impl/MinionRpcStreamConnectionManagerImpl.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/MinionManagerImpl.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/heartbeat/HeartbeatKafkaForwarder.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/tasktresults/TaskResultsKafkaForwarder.java

Fixes needed to propagate and link minions properly with rest of stack.
- https://issues.opennms.org/browse/HS-660

HS-660 Apply propagation of tenant identifier across places.

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature

External-IT - only say "Hello World" for now; remove tests that are outdated

---

ui/src/components/Appliances/MinionsTable.vue
ui/src/components/Appliances/utils.ts
ui/src/components/utils.ts
ui/src/store/Queries/appliancesQueries.ts
ui/src/types/minion.d.ts
ui/tests/Appliances/minionsTable.test.ts
ui/tests/Appliances/nodesTable.test.ts
ui/tests/fixture/minions.ts
ui/tests/store/Queries/appliancesQueries.test.ts

HS-657 Fix failing tests

---

rest-server/src/main/java/org/opennms/horizon/server/model/status/NodeStatus.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLNodeServiceTest.java

Request:
```
query {
nodeStatus(id: 1) {
id,
status
}
}
```
Response:
```
{
"data": {
"nodeStatus": {
"id": 1,
"status": "UP"
}
}
}
```
- https://issues.opennms.org/browse/HS-640
* [] Documentation has been updated as necessary.

HS-640: Derive Node Status from Critical service (ICMP) on Management IP

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLNodeServiceTest.java

HS-666 fix the broken BFF

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/MonitoringSystemMapper.java
inventory/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java
minion/minion-taskset/taskset-scheduler/src/main/java/org/opennms/horizon/minion/scheduler/impl/OpennmsSchedulerImpl.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/Minion.java
shared-lib/inventory/src/main/proto/monitoringSystem.proto

- https://issues.opennms.org/browse/HS-664

HS-664: Add minion status

---

inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/CollectorTaskSetService.java
minion/minion-taskset/taskset-worker/pom.xml
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/shell/TaskSetPrint.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/TaskSetLifecycleManager.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/MeteredWorkflowLifecycleManager.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskSetLifecycleManagerImpl.java
minion/minion-taskset/taskset-worker/src/main/resources/OSGI-INF/blueprint/horizon-ignite.xml

SNMP v2c & TaskSet debugging

---

minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/standalone/Dumper.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/standalone/V4Pinger.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/standalone/V6Pinger.java
minion/icmp/icmp-jni/src/main/java/org/opennms/minion/icmp/jni/Ping.java
minion/icmp/icmp-jni6/src/main/java/org/opennms/minion/icmp/jni6/Ping.java
minion/minion-observability/observability-metrics/src/main/java/org/opennms/horizon/minion/observability/metrics/internal/MetricsServlet.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/ignite/IgniteMetricsAdapter.java
minion/testtools/minion-gateway-wiremock/minion-gateway-wiremock-main/src/main/java/org/opennms/horizon/testtool/miniongateway/wiremock/rest/MinionGatewayWiremockRestController.java

HS-532,HS-564: Minion - Attain A rating for Security Review on SonarCloud
- https://issues.opennms.org/browse/HS-532
- https://issues.opennms.org/browse/HS-564
[https://sonarcloud.io/summary/new_code?id=opennms_horizon-stream_minion&pullRequest=542](https://sonarcloud.io/summary/new_code?id=opennms_horizon-stream_minion&pullRequest=542)
Sonarqube gives 0% test coverage. Not sure if this has been set up yet on minion.
I do notice quite alot of other sonarqube issues which show on the Sonarqube intellij plugin, but do not show in the sonar cloud. I have only done sonar cloud related items.

HS-532,HS-564: Minion - Attain A rating for Security Review on SonarCloud

---

rest-server/src/main/java/org/opennms/horizon/server/mapper/MinionMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/Minion.java

Consolidate status between Node/Minion
- https://issues.opennms.org/browse/HS-664

HS-664: Update minion status to be String

---

operator/internal/handlers/opennms.go
operator/internal/model/values/opennms_values.go
operator/internal/util/crd/crd_to_values.go
operator/internal/util/crd/crd_to_values_test.go

removing the defunct core from the operator's handlers and models
- https://issues.opennms.org/browse/HS-663

HS-663: remove core from the operator

---

ui/src/components/Graphs/LineGraph.vue
ui/src/containers/Graphs.vue

ifInOctets, ifOutOctets etc.
- https://issues.opennms.org/browse/HS-627

HS-627: Update metric graphs

---

inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java

- https://issues.opennms.org/browse/HS-669

HS-669: Fix systems/locations querying for tenantId

---

ui/src/components/Appliances/AddNodeCtrl.vue

Correct location name sent to BFF for add-device.

---

charts/opennms/templates/opennms/minion/minion-deployment.yaml
minion/assembly/src/main/resources/etc/org.opennms.identity.cfg
minion/docker-assembly/src/main/docker/app/Dockerfile

Bring back old variables in place
- https://issues.opennms.org/browse/HS-672

HS-672 Use MINION_ID and MINION_LOCATION environment variables

---

alarm/src/main/java/org/opennms/horizon/alarmservice/model/AlarmSeverity.java
alarm/src/main/java/org/opennms/horizon/alarmservice/service/AlarmServiceImpl.java
alarm/src/test/java/org/opennms/horizon/alarmservice/dockerit/AlarmTestSteps.java
alarm/src/test/resources/org/opennms/horizon/alarmservice/dockerit/alarm.feature

Pivoting to pull the reduction key, clear key, and severity from the new AlarmData in Event proto definition

Pivot to pull reduction and clear keys from new event proto def

---

alarm/pom.xml
alarm/src/main/java/org/opennms/horizon/alarmservice/db/entity/Alarm.java
alarm/src/test/java/org/opennms/horizon/alarmservice/dockerit/AlarmTestSteps.java
alarm/src/test/java/org/opennms/horizon/alarmservice/dockerit/RetryUtils.java
alarm/src/test/resources/org/opennms/horizon/alarmservice/dockerit/alarm.feature

Alarms docker-it - use retries and eliminate hard-coded delays.  Fix alarm counter update.

---

ui/src/components/utils.ts
ui/tests/Utils/common.test.ts

Add tests, refactor complex function to satisfy sonar
- https://issues.opennms.org/browse/HS-734

HS-734: Test, refactor getting human readable duration

---

minion/docker-it/pom.xml

Correct the test minion location (use MINION_LOCATION env variable to override the default hard-coded into the docker image).

---

ui/src/components/Layout/NavigationRail.vue
ui/src/containers/Discovery.vue
ui/src/containers/MyDiscovery.vue
ui/src/router/index.ts
ui/tests/Discovery/discovery.test.ts
ui/tests/MyDiscovery/myDiscovery.test.ts

Covers HS-759 / HS-760.
Adds initial routes / container comps for the `Discovery` and `My Discovery` pages.
- https://issues.opennms.org/browse/HS-759
- https://issues.opennms.org/browse/HS-760
[HS-759]: https://opennms.atlassian.net/browse/HS-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HS-760]: https://opennms.atlassian.net/browse/HS-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HS-759]: https://opennms.atlassian.net/browse/HS-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HS-760]: https://opennms.atlassian.net/browse/HS-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HS-759: Init discovery / my-discovery pages

---

inventory/pom.xml
inventory/src/test/java/org/opennms/horizon/inventory/CucumberRunnerIT.java
inventory/src/test/java/org/opennms/horizon/inventory/InventoryCucumberTestSteps.java
inventory/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutionResultProcessorImpl.java
parent-pom/pom.xml

Spins up Inventory Application and validates following functionality.
- Sending Minion heartbeat creates location/monitoring system
- Create new device and validates that device got created
This PR depends on #574 for tests to pass
- https://issues.opennms.org/browse/HS-746
[HS-746]: https://opennms.atlassian.net/browse/HS-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HS-746: Add Cucumber IT for Inventory

---

ui/components.d.ts
ui/src/components/Common/Stepper/CustomFeatherStep.vue
ui/src/components/Common/Stepper/CustomFeatherStepper.vue
ui/tests/Common/stepper.test.ts

Adds custom feather stepper, to be used on discovery or wherever
- https://issues.opennms.org/browse/HS-765

HS-765: Add custom feather stepper

---

ui/components.d.ts
ui/src/components/Common/Stepper/CustomFeatherStep.vue
ui/src/components/Discovery/DiscoveryStep2.vue
ui/src/components/Discovery/DiscoveryStepper.vue
ui/src/store/Views/discoveryStore.ts

Add step 2 of ICMP discovery. Combines with step 3.
- https://issues.opennms.org/browse/HS-768
- https://issues.opennms.org/browse/HS-769

HS-768: Step 2 of discovery

---

minion/flows/features/src/main/feature/feature.xml
minion/flows/parser/pom.xml
minion/flows/pom.xml

This PR cleans up dependency versions and makes the compatible with the parent pom.
- https://opennms.atlassian.net/browse/DC-494

DC-494: Clean up flow dependencies

---

ui/src/components/Discovery/Infobar.vue
ui/src/containers/Discovery.vue

- https://issues.opennms.org/browse/HS-761
- https://issues.opennms.org/browse/HS-763
- https://issues.opennms.org/browse/HS-764

HS-761: Add infobar, add modal

---

.github/actions/external-it/action.yml
install-local/install-local.sh

.github/actions/external-it - fix

---

minion/flows/parser/pom.xml
minion/flows/parser/src/main/java/org/opennms/horizon/minion/flows/shell/SendFlowCmd.java
minion/flows/parser/src/test/java/org/opennms/horizon/minion/flows/shell/SendFlowCmdTest.java
minion/flows/parser/src/test/resources/log4j.properties
minion/pom.xml

adds a shell command to manually send test flow data.
- https://opennms.atlassian.net/browse/DC-466

DC-466: Shell Command: send netflow data

---

.github/workflows/develop.yml
.github/workflows/feature-grafana.yml
.github/workflows/release.yml
grafana/Dockerfile

Migrate to OpenNMS-Cloud and Use Larger Runners
- https://opennms.atlassian.net/browse/HS-829

HS-829 - Migrate to OpenNMS-Cloud and Use Larger Runners

---

alarm/pom.xml
minion/plugins/plugins-api/pom.xml
parent-pom/pom.xml

Dependency updates for things which failed to resolve automatically via dependabot PRs.
- https://issues.opennms.org/browse/HS-875
No major review required, these are only pom.xml updates.

Third party dependency updates for backend services

---

minion-gateway/docker-it/pom.xml
minion/docker-it/pom.xml
minion/docker-it/src/test/java/org/opennms/horizon/dockerit/CucumberRunnerIT.java
minion/docker-it/src/test/java/org/opennms/horizon/dockerit/testcontainers/TestContainerRunnerClassRule.java
minion/docker-it/src/test/resources/karaf/etc/org.opennms.core.ipc.grpc.client.cfg
parent-pom/pom.xml

Use test containers instead of docker-maven-plugin for Minion docker-it.

---

ui/components.d.ts
ui/src/components/Graphs/utils.ts
ui/tests/Appliances/appliances.test.ts
ui/tests/Discovery/discoveryStepper.test.ts
ui/tests/Map/mapAlarmsGrid.test.ts
ui/tests/setupWrapper.ts

Fixes the downloadMultipleCanvases function, used on the graphs page
Fixes some test warnings
- https://issues.opennms.org/browse/HS-874

HS-874: Fix multi chart download

---

charts/opennms/templates/opennms/minion/minion-deployment.yaml
charts/opennms/values.yaml
install-local/install-local-external-minion-test/docker-compose.yml
inventory/src/main/resources/flows-config.json
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/rpcrequest/flows/FlowKafkaForwarder.java
minion/assembly/runInPlace.sh
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpListener.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/UdpListener.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/factory/TcpListenerFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/factory/TelemetryRegistry.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/factory/UdpListenerFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/ConfigManager.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/FlowSinkModule.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixTcpParser.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/IpfixUdpParser.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/Netflow5UdpParser.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/Netflow9UdpParser.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/ParserBase.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/UdpParserBase.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/IpfixTcpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/IpfixUdpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/Netflow5UdpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/Netflow9UdpParserFactory.java
minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ClockSkewTest.java
minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ConfigManagerTest.java
minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/IllegalFlowTest.java
minion/minion-flows/flows-parser/src/test/resources/flows-config.json
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/flow/telemetry.proto

- add a runInPlace.sh in minion/assembly for easy startup minion standalone.
- add UDP port expose in install-local/install-local-external-minion-test/docker-compose.yml
- fix flow listener and make sure flow data will reach kafka 
- https://opennms.atlassian.net/browse/DC-512

DC-512: Support UDP protocol in minion

---

ui/src/components/Common/InputButtonPopover.vue
ui/src/components/Inventory/InventoryTagManager.vue
ui/src/store/Mutations/taggingMutations.ts

- https://issues.opennms.org/browse/HS-848-split-add-tag

HS-848 Popoverlay split into comp

---

ui/src/components/Inventory/InventoryMonitoredNodesTabContent.vue
ui/src/components/Inventory/InventoryNodeTaggingEditOverlay.vue
ui/src/components/Inventory/InventoryTagManager.vue
ui/src/store/Mutations/nodeMutations.ts

- https://issues.opennms.org/browse/HS-849-split node-overlay

HS-849 Split node overlay

---

.github/workflows/develop.yml
charts/opennms/templates/opennms/minion/minion-deployment.yaml
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/MetricsTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/CreateNodeData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/ErrorData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/ErrorLocationData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/GQLQuery.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/CreateNodeResponseData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/CreateNodeResponseWrapper.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/CreateNodeResult.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature
minion/assembly/src/main/resources/etc/org.opennms.horizon.minion.ignite.worker.cfg
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/ignite/WorkerIgniteConfiguration.java
minion/minion-taskset/taskset-worker/src/main/resources/OSGI-INF/blueprint/horizon-ignite.xml

- https://issues.opennms.org/browse/HS-900

EXTERNAL-IT - add devices and watch for metrics

---

events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java

Fix bug
- https://issues.opennms.org/browse/HS-886

HS-886: Fix bug where events are not associating with nodeId

---

Tiltfile
ui/src/components/Common/Icon.vue
ui/src/components/Inventory/InventoryDetectedNodesTabContent.vue
ui/src/components/Inventory/InventoryFilter.vue
ui/src/components/Inventory/InventoryIconActionList.vue
ui/src/components/Inventory/InventoryMonitoredNodesTabContent.vue
ui/src/components/Inventory/InventoryNodeTaggingEditOverlay.vue
ui/src/components/Inventory/InventoryTagManager.vue

- https://issues.opennms.org/browse/HS-850-search

HS-850 Add search filter tags

---

ui/src/components/Layout/NavigationRail.vue
ui/src/components/MonitoringPolicies/Condition.vue
ui/src/containers/Dashboard.vue
ui/src/router/index.ts
ui/src/store/Views/dashboardStore.ts
ui/tests/Dashboard/dashboard.test.ts

Adds initial dashboard page, route, store, etc. 
- https://issues.opennms.org/browse/HS-897

HS-897: Initial dashboard container, store

---

datachoices/pom.xml
inventory/src/main/java/org/opennms/horizon/inventory/grpc/GrpcConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/TagGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/TagMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/model/Node.java
inventory/src/main/java/org/opennms/horizon/inventory/model/Tag.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/TagRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/tag.xml
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/TagGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/src/test/resources/application.yml
shared-lib/inventory/src/main/proto/tagService.proto

HS-789: Add node tag manangement: add and remove a tag from node(s)
Tag has a many to many relationship with Node with a degree of idempotency on create/remove
Creating a Tag will associate it with a Node, if its not already associated.
Removing a Tag will remove the Tag association with the node, and if there is no other associations it will delete the Tag.
Deleting a node will delete the associations of the tag, if there is no other associations it will delete the tag also.
Endpoints add/remove a list of tags.
- https://issues.opennms.org/browse/HS-789

HS-789: Add node tag manangement: add and remove a tag from node(s)

---

minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/ignite/WorkerIgniteConfiguration.java

Use consistent id on ignite client
- https://issues.opennms.org/browse/HS-963

HS-963: Use consistent id on ignite client

---

shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-contract/src/main/proto/opennms/flow/telemetry.proto

https://opennms.atlassian.net/browse/HS-951

HS-951 Add additional fields to TelemetryMessage proto buf

---

inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/TaskUtils.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/taskset/TestTaskSetGrpcService.java
minion/plugins/nodescan-plugin/pom.xml
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddrTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddressTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/SNMPInterfaceTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/SystemGroupTracker.java
minion/plugins/nodescan-plugin/src/test/java/org/opennms/horizon/minion/nodescan/NodeScanTest.java
rest-server/src/main/resources/application.yml
shared-lib/protobuf/src/main/proto/nodescan.proto
shared-lib/snmp/snmp-api/src/main/java/org/opennms/horizon/shared/snmp/SnmpHelper.java

Migrate couple for SNMP trackers 
Add code to scan IP address table, SNMP interface table, and System Group
- https://issues.opennms.org/browse/HS-807
- https://issues.opennms.org/browse/HS-880
- https://issues.opennms.org/browse/HS-882
- https://issues.opennms.org/browse/HS-883

HS-807_880__882_883 node scan implementation

---

alarm/pom.xml
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/GrpcTenantLookupImpl.java
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/TenantConfig.java
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/TenantIdentifierResolver.java
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/TenantLookup.java
alarm/src/main/resources/db/changelog/changelog.xml
alarm/src/main/resources/db/changelog/hs-0.1.0/tables/alarm_association_tenant_update.xml
alarm/src/main/resources/db/changelog/hs-0.1.0/tables/alarm_attributes_tenant_update.xml
alarm/src/main/resources/db/changelog/hs-0.1.0/tables/alarm_tenant_update.xml
alarm/src/main/resources/db/changelog/hs-0.1.0/tables/memo_tenant_update.xml
alarm/src/main/resources/db/changelog/hs-0.1.0/tables/service_tenant_update.xml
alarm/src/test/java/org/opennms/horizon/alarmservice/CucumberRunnerIT.java
alarm/src/test/java/org/opennms/horizon/alarmservice/SpringContextTestInitializer.java
alarm/src/test/java/org/opennms/horizon/alarmservice/SpringCucumberRunnerIT.java
alarm/src/test/java/org/opennms/horizon/alarmservice/steps/SpringTestSteps.java
alarm/src/test/java/org/opennms/horizon/alarmservice/testcontainers/TestContainerRunnerClassRule.java
alarm/src/test/resources/org/opennms/horizon/spring/spring_alarm.feature

Create spring based cucumber tests that live beside container cucumber tests for easier development
- https://issues.opennms.org/browse/HS-971
I was working on HS-941 (Add tenant id to alarms) before I realised it was sensible to split this story out. Some tenant id code from that story is in here, but it is all commented out. It will go in HS-941, which I will work on next.
Also, the test is a very basic one, to prove the piping works. It will be removed in HS-941

HS-971: Create spring based cucumber tests that live beside container cucumber tests

---

ui/src/components/NodeStatus/SNMPInterfacesTable.vue

Fix the column ordering
- https://issues.opennms.org/browse/HS-949

HS-949: Fix SNMP interface table columns

---

rest-server/src/main/java/org/opennms/horizon/server/mapper/TagMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/tag/Tag.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/tag/TagCreate.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/tag/TagListAdd.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/tag/TagListRemove.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLTagServiceTest.java

HS-790: BFF - Add node tag management API
```
mutation {
addTags(
tags: { 
nodeId: 1,
tags: [
{
name: "tag-1"
},
{
name: "tag-2"
}
]
}
) {
id,
tenantId,
name
}
}
```
```
mutation {
removeTags(
tags: { 
nodeId: 1,
tagIds: [ 1 ]
}
) 
}
```
```
query {
tagsByNodeId (nodeId: 1) {
id,
tenantId,
name
}
}
```
- https://issues.opennms.org/browse/HS-790

HS-790: BFF - Add node tag management API

---

ui/src/components/Appliances/AppliancesAddNodeCtrl.vue
ui/src/services/gqlService.ts

- https://issues.opennms.org/browse/HS-988

HS-988 Add notification error msg for duplicated node addition

---

ui/src/services/gqlService.ts

- https://issues.opennms.org/browse/HS-988

HS-988 Add service unavailable

---

alarm/src/main/java/org/opennms/horizon/alarmservice/db/entity/TenantAwareEntity.java
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/TenantConfig.java
alarm/src/main/java/org/opennms/horizon/alarmservice/db/tenant/TenantIdentifierResolver.java
alarm/src/main/java/org/opennms/horizon/alarmservice/service/AlarmEntityNotifierImpl.java
alarm/src/main/java/org/opennms/horizon/alarmservice/service/routing/EventConsumer.java
alarm/src/main/resources/db/changelog/changelog.xml
alarm/src/test/java/org/opennms/horizon/alarmservice/kafkahelper/KafkaTestHelper.java
alarm/src/test/java/org/opennms/horizon/alarmservice/stepdefs/AlarmTestSteps.java
alarm/src/test/resources/org/opennms/horizon/alarmservice/alarm.feature

Add tenantId into alarms module
- https://issues.opennms.org/browse/HS-941
n/a

HS-941: add tenant id to alarms

---

inventory/src/main/java/org/opennms/horizon/inventory/mapper/EmptyStringMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/IpInterfaceMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/NodeMapper.java
inventory/src/main/java/org/opennms/horizon/inventory/mapper/SnmpInterfaceMapper.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddrTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddressTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/SNMPInterfaceTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/SystemGroupTracker.java
minion/plugins/nodescan-plugin/src/test/java/org/opennms/horizon/minion/nodescan/NodeScanTest.java
shared-lib/snmp/snmp-api/src/main/java/org/opennms/horizon/shared/snmp/AbstractSnmpStore.java

- https://issues.opennms.org/browse/HS-987

HS-987 Fixed null pointer exception in node scan process

---

inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/CollectorTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/MonitorTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/TaskUtils.java

HS-972: Make Azure Task ID more unique
- https://issues.opennms.org/browse/HS-972

HS-972: Make Azure Task ID more unique

---

shared-lib/horizon-common-utils/src/main/java/org/opennms/horizon/shared/utils/IPAddressRange.java
shared-lib/horizon-common-utils/src/main/java/org/opennms/horizon/shared/utils/IPPortRange.java
shared-lib/horizon-common-utils/src/test/java/org/opennms/horizion/shared/utils/IPAddressRangeTest.java

This PR only add two classes into shared-lib which will be use in classification.
- https://opennms.atlassian.net/browse/HS-927

HS-927: add IPAddressRange & IPPortRange for flow classification

---

charts/opennms/values.yaml
install-local/install-local-opennms-horizon-stream-custom-images-values.yaml
install-local/install-local-opennms-horizon-stream-values.yaml
inventory/src/main/java/org/opennms/horizon/inventory/mapper/EncryptAttributeConverter.java
inventory/src/main/resources/application.yml
inventory/src/test/java/org/opennms/horizon/inventory/grpc/AzureCredentialGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/mapper/EncryptAttributeConverterTest.java
inventory/src/test/resources/application.yml

HS-994: Inventory Security Vulnerabilities
Also addressing some comments of geralds in from another PR
- https://issues.opennms.org/browse/HS-994

HS-994: Inventory Security Vulnerabilities

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/KeycloakTestSteps.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/TagGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/TagRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeTaggingStepDefinitions.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/TagGrpcItTest.java
inventory/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLTagServiceTest.java
shared-lib/inventory/src/main/proto/tagService.proto

HS-1014: Inventory - Get All Tags: Fetch a list of tags
- https://issues.opennms.org/browse/HS-1014

HS-1014: Inventory - Get All Tags: Fetch a list of tags

---

ui/src/components/Layout/NavigationRail.vue
ui/src/containers/SyntheticTransactions.vue
ui/src/router/index.ts
ui/src/store/Views/syntheticTransactionsStore.ts
ui/tests/SyntheticTransactions/syntheticTransactions.test.ts

Initial page for synthetic transactions
- https://issues.opennms.org/browse/HS-1019

HS-1019: Initial Synthetic Transactions

---

install-local/install-local-external-minion-test/docker-compose.yml
install-local/install-local-external-minion-test/snmpd.conf
install-local/install-local-snmpd-device.yaml

Created k8s deployment file for smpd instance with customized snmpd.conf file
Modified the compose file using ARM64 image and customized snmpd.conf file

Created local snmpd instance deployment for BTO and Kind cluster

---

ui/src/components/Discovery/EditDiscovery.vue
ui/src/components/Discovery/LocationsAutocomplete.vue
ui/tests/Discovery/locationsAutocomplete.test.ts

HS-953 - location autocomplete

---

ui/src/store/Queries/appliancesQueries.ts
ui/src/store/Queries/inventoryQueries.ts

- https://issues.opennms.org/browse/HS-1048

HS-1048 Get ipAddress from SNMP interface

---

inventory/src/main/java/org/opennms/horizon/inventory/model/AzureCredential.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/azure-credential-name.xml
inventory/src/test/java/org/opennms/horizon/inventory/cucumber/CucumberRunnerIT.java
inventory/src/test/java/org/opennms/horizon/inventory/cucumber/InventoryBackgroundHelper.java
inventory/src/test/java/org/opennms/horizon/inventory/cucumber/steps/AzureDiscoveryStepDefinitions.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/AzureCredentialGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java
inventory/src/test/resources/org/opennms/horizon/inventory/azure-discovery.feature
inventory/src/test/resources/wiremock/azure-mappings.json
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/AzureCredential.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/AzureCredentialCreate.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLAzureCredentialServiceTest.java
shared-lib/inventory/src/main/proto/azureCredential.proto

HS-1045: Add Name field to Azure Credentials
- https://issues.opennms.org/browse/HS-1045

HS-1045: Add Name field to Azure Credentials

---

inventory/src/test/java/org/opennms/horizon/inventory/grpc/DiscoveryConfigGrpcItTest.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/DiscoveryConfigMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/CreateDiscoveryConfigRequest.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/DiscoveryConfig.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/SNMPConfig.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcDiscoveryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
shared-lib/inventory/src/main/proto/discovery.proto

- https://issues.opennms.org/browse/HS-944

HS-944 BFF GraphQL endpoints for discovery config

---

ui/src/containers/Graphs.vue
ui/src/graphql/Views/graphQueries.graphql
ui/src/store/Queries/graphsQueries.ts
ui/src/types/graphql.ts

- https://issues.opennms.org/browse/HS-1062

HS-1062 Fix graph node with snmpPrimary interface

---

ui/src/components/Discovery/DiscoveryAutocomplete.vue
ui/src/components/Discovery/DiscoveryContentEditable.vue
ui/src/components/Discovery/DiscoverySyslogSNMPTrapsForm.vue
ui/src/components/Discovery/discovery.text.ts
ui/src/graphql/Tag/tagsByNodeIdQuery.gql
ui/src/graphql/Tag/tagsQuery.gql
ui/src/store/Mutations/discoveryMutations.ts
ui/src/store/Queries/discoveryQueries.ts
ui/src/types/graphql.ts
ui/tests/Discovery/discoveryAutocomplete.test.ts
ui/tests/Discovery/discoverySyslogSNMPTrapsForm.test.ts
ui/tests/mountWithPiniaVillus.ts

- Add tag search endpoint
- Add form reset
- Add unit tests
- https://issues.opennms.org/browse/HS-1058

HS-1058 Syslog form with endpoints and unit tests

---

inventory/src/main/java/org/opennms/horizon/inventory/model/IpInterface.java
inventory/src/main/java/org/opennms/horizon/inventory/model/SnmpInterface.java
inventory/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/SnmpInterfaceService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/ip-snmp-interfaces.xml
inventory/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddrTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddressTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
minion/plugins/nodescan-plugin/src/test/java/org/opennms/horizon/minion/nodescan/NodeScanTest.java
shared-lib/inventory/src/main/proto/ipInterface.proto
shared-lib/inventory/src/main/proto/snmpInterface.proto
shared-lib/protobuf/src/main/proto/nodescan.proto

Updated the schema and data model, the node scan result data model, the scan process, and the results process.
- https://issues.opennms.org/browse/HS-1012

HS-1012 Fixed the IpInterface and SnmpInterface schema and data model

---

ui/src/components/Discovery/DiscoveryAzureForm.vue
ui/src/components/Discovery/LocationsAutocomplete.vue
ui/src/graphql/Discovery/addAzureCredentialMutation.graphql
ui/src/store/Views/discoveryStore.ts
ui/src/types/graphql.ts

- Ensure all avail endpoints are used
- Saving flow success/fail behave as expected
- 
- https://issues.opennms.org/browse/HS-1065

HS-1065 Integrate avail endpoints

---

inventory/src/test/java/org/opennms/horizon/inventory/SpringContextTestInitializer.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/AzureCredentialGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/GrpcTestBase.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcStartupIntTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/DetectorResponseServiceIntTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java

- https://issues.opennms.org/browse/HS-1074

HS-1074 fix unit tests

---

.github/workflows/develop.yml
.github/workflows/release.yml

Deploy Workaround Until Github Action Runners Are Back Online.
Because we are in dev state still, as a temporary work around, will comment out end to end testing for both develop.yml and release.yml.
- https://issues.opennms.org/browse/HS-1100

Deploy Workaround Until Github Action Runners Are Back Online

---

inventory/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringLocationGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoringLocationRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringLocationService.java
inventory/src/test/java/org/opennms/horizon/inventory/repository/MonitoringLocationRepoTest.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcLocationService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
shared-lib/inventory/src/main/proto/monitoringLocation.proto

- https://issues.opennms.org/browse/HS-1063

HS-1063 Search location

---

ui/package.json
ui/src/components/Discovery/DiscoveryAzureForm.vue
ui/src/components/Discovery/LocationsAutocomplete.vue
ui/src/types/graphql.ts
ui/yarn.lock

Adds discovery azure form validations
- https://issues.opennms.org/browse/HS-1101

HS-1101: Add azure validations

---

charts/opennms/templates/grafana/grafana-secret.yaml

Fix grafana setup in tilt deployments.
- https://issues.opennms.org/browse/HS-1086

HS-1086 Adjust default grafana configuration

---

inventory/src/main/java/org/opennms/horizon/inventory/model/SnmpAgentConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/model/SnmpConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/SnmpConfigRepository.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/snmp-config.xml
inventory/src/test/java/org/opennms/horizon/inventory/repository/SnmpConfigRepositoryTest.java

Add Snmp Config persistence
- https://issues.opennms.org/browse/HS-1104

HS-1104: Add Snmp Config persistence

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java

HS-1093: Associate tags with nodes from azure discovery
- https://issues.opennms.org/browse/HS-1093

HS-1093: Associate tags with nodes when created from azure discovery

---

ui/src/components/Discovery/DiscoveryContentEditable.vue
ui/src/components/Discovery/DiscoverySnmpForm.vue
ui/src/components/Discovery/discovery.text.ts

tooltip for IP and Port fields with basic explanation

HS-1115 - add info icon with tooltip

---

inventory/main/src/main/java/org/opennms/horizon/inventory/repository/AzureCredentialRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/AzureCredentialService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/AzureCredentialGrpcItTest.java

- https://issues.opennms.org/browse/HS-1130

HS-1130: Make azure credentia unique by client, subcription, directory id

---

build-tools/basic/compile.sh
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/InventoryBackgroundHelper.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/PassiveDiscoveryStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/azure-discovery.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/passive-discovery.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/GrpcConfig.java
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/PassiveDiscoveryGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/mapper/PassiveDiscoveryMapper.java
inventory/main/src/main/java/org/opennms/horizon/inventory/model/PassiveDiscovery.java
inventory/main/src/main/java/org/opennms/horizon/inventory/repository/PassiveDiscoveryRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/repository/TagRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/Constants.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/PassiveDiscoveryService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/main/src/main/resources/db/changelog/changelog.xml
inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/passive-discovery.xml
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/GrpcTestBase.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/PassiveDiscoveryGrpcItTest.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/PassiveDiscoveryMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/passive/PassiveDiscovery.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/passive/PassiveDiscoveryUpsert.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcPassiveDiscoveryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLPassiveDiscoveryServiceTest.java
shared-lib/inventory/src/main/proto/passiveDiscovery.proto

HS-1011: Create passive discovery
HS-1010: Add tags when saving passive discovery
CREATE
```
mutation { 
upsertPassiveDiscovery( 
discovery: { 
id: 1,
name: "Passive Discovery",
location: "Default",
snmpPorts: [161],
snmpCommunities: ["public"],
tags: [
{
name: "tag-1"
}
]
}
) {
id,
name,
location
toggle,
snmpPorts,
snmpCommunities,
createTimeMsec
}
}
```
GET
```
query {
passiveDiscoveries {
id,
name,
location
toggle,
snmpPorts,
snmpCommunities,
createTimeMsec
}
}
```
- https://issues.opennms.org/browse/HS-1011

HS-1010,HS-1011: Create passive discovery

---

inventory/main/src/main/java/org/opennms/horizon/inventory/model/PassiveDiscovery.java

HS-1010,HS-1011: Create passive discovery - fix compile issue
Was caught out by the ordering of PRs, fixing previous merge
- https://issues.opennms.org/browse/HS-1011

HS-1010,HS-1011: Create passive discovery - fix compile issue

---

inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/PassiveDiscoveryGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/PassiveDiscoveryService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/PassiveDiscoveryGrpcItTest.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/PassiveDiscoveryMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/discovery/passive/PassiveDiscoveryToggle.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcPassiveDiscoveryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLPassiveDiscoveryServiceTest.java

Add a toggle mutation for passive discoveries
mutation {
togglePassiveDiscovery(toggle: { id: 1, toggle: false }) {
toggle
}
}
- https://issues.opennms.org/browse/HS-1066

HS-1066: Toggle passive discovery

---

inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/ActiveDiscoveryGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/TaskUtils.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/PingScan.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
shared-lib/protobuf/src/main/proto/icmp.proto
shared-lib/protobuf/src/main/proto/nodescan.proto
shared-lib/protobuf/src/main/proto/taskSet.proto

- https://issues.opennms.org/browse/HS-1145

HS-1145: Add Snmp configs to node scan

---

.github/pull_request_template.md

PR Checklist - Add a step to notify devops of changes to the Charts.

---

ui/tests/Discovery/locationsAutocomplete.test.ts

hotfix - fix location test

---

ui/components.d.ts
ui/src/containers/Flows.vue
ui/src/router/index.ts
ui/tests/Flows/flows.test.ts

Create the flows page, route and tests
- https://issues.opennms.org/browse/HS-1195
Page created, route works.

HS-1195 - Create Flows Page and Route

---

ui/src/components/Alerts/ACard.vue
ui/src/components/Alerts/ACardList.vue
ui/src/components/Alerts/alerts.enum.ts
ui/src/containers/Alerts.vue
ui/src/styles/mixins.scss
ui/tests/Alerts/aCard.test.ts
ui/tests/Alerts/aCardList.test.ts
ui/tests/Alerts/alerts.test.ts

- https://issues.opennms.org/browse/HS-1166

HS-1166 Add card list

---

ui/components.d.ts
ui/src/components/Common/BasicChipSelect.vue
ui/src/components/Common/BasicSelect.vue
ui/src/containers/Flows.vue

This is a PR to add the needed filters to the Flows page. These are placeholders until the endpoints are ready.
- https://issues.opennms.org/browse/HS-1199
I have updated the BasicSelect to have chips for the selected value. Prop is set to false.
To view page, goto '/flows'.

HS-1199 - Add Filters to Flows page.

---

ui/src/components/Discovery/DiscoveryLocationsAutocomplete.vue
ui/src/components/Discovery/DiscoverySyslogSNMPTrapsForm.vue
ui/src/containers/Discovery.vue

Validate passive discovery
- https://issues.opennms.org/browse/HS-1006

HS-1006 - validate form passive

---

ui/mock-graphql/codegen.yml
ui/mock-graphql/src/data/discovery.ts
ui/mock-graphql/src/graphql/Mutations/saveRoutingKey.graphql
ui/mock-graphql/src/graphql/Queries/listAzureDiscoveries.graphql
ui/mock-graphql/src/schema.ts
ui/mock-graphql/src/typeDefs.ts
ui/src/types/graphql-mocks.ts

Fixes our mock server so it can be used to new modules.
- https://issues.opennms.org/browse/HS-1213

HS-1213: Fix/update mock server & examples

---

ui/mock-graphql/README.md
ui/mock-graphql/codegen.yml
ui/mock-graphql/src/data/alerts.ts
ui/mock-graphql/src/data/discovery.ts
ui/mock-graphql/src/graphql/Queries/alertList.gql
ui/mock-graphql/src/helpers/random.ts
ui/mock-graphql/src/schema.ts
ui/mock-graphql/src/typeDefs.ts
ui/src/components/Alerts/AlertsCard.vue
ui/src/components/Alerts/AlertsCardList.vue
ui/src/components/Alerts/alerts.constant.ts
ui/src/graphql/Alerts/alertsQueries.gql
ui/src/store/Queries/alertsQueries.ts
ui/src/store/Views/alertsStore.ts
ui/src/styles/mixins.scss
ui/src/types/alerts.d.ts
ui/src/types/graphql-mocks.ts
ui/tests/Alerts/alertsCard.test.ts
ui/tests/Alerts/alertsCardList.test.ts

- https://issues.opennms.org/browse/HS-1164

HS-1164 Add search filter

---

ui/src/components/Alerts/alerts.constant.ts
ui/src/containers/Alerts.vue
ui/src/store/Views/alertsStore.ts

- https://issues.opennms.org/browse/HS-1163

HS-1163 Add markup

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/GrpcTwinPublisher.java

This PR improves error handling in digital twin layer of minion gateway. Given its a runtime issue which occurs in specific conditions existing tests are not covering it.
- https://issues.opennms.org/browse/HS-1032
- Error handling logic in `GrpcTwinPublisher`

HS-1032 Cleanup stale minion connections in digital twin layer

---

ui/src/components/Discovery/DiscoveryContentEditable.vue

validation do not accept range. will be fixed in another ticket, for now we don't validate IPs
- hot fix

hotfix - no validation for ip

---

external-it/external-horizon-stream-it/pom.xml
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/DiscoveryTest.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature

Adding new methods to remove nodes and to get node ID as well as list of nodes
- https://issues.opennms.org/browse/HS-1253

Extending Environmental testing HS-1253

---

doc/architecture/decisions/0002-store-cross-project-api-contracts-in-a-separate-repository.md

- Adds a proposed ADR for moving cross-project proto files into a new repository and producing artifacts.
- ADR is in Proposed state.
- https://issues.opennms.org/browse/AR-30

AR-30: ADR for moving API contracts to a new repository

---

alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature

add pagination to alerts/listAlerts
- https://issues.opennms.org/browse/HS-1219

HS-1219: add pagination to alerts/listAlerts

---

ui/src/components/Common/BasicChart.vue
ui/src/containers/Flows.vue
ui/src/store/Views/flowsStore.ts
ui/src/types/index.ts

Add radio buttons which hide and show data. Added Icon buttons for future use. Added Feather object to declare types better.
- https://issues.opennms.org/browse/HS-1200
Radio Buttons.

HS-1200: Add radio buttons to flows page

---

notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyDaoTest.java
notifications/src/test/java/org/opennms/horizon/notifications/tenant/AspectTest.java
notifications/src/test/java/org/opennms/horizon/notifications/tenant/AspectTestHelper.java

Tidy notifications tests
- https://issues.opennms.org/browse/HS-1305
n/a

HS-1305: notifications test tidy up

---

Tiltfile
charts/opennms/templates/grafana/grafana-deployment.yaml
charts/opennms/templates/grafana/grafana-secret.yaml
charts/opennms/templates/opennms/events/events-deployment.yaml
charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
events/consumer/pom.xml
events/consumer/src/main/java/org/opennms/horizon/events/consumer/EventsConsumer.java
events/consumer/src/main/java/org/opennms/horizon/events/consumer/metrics/TenantMetricsTracker.java
events/consumer/src/main/java/org/opennms/horizon/events/consumer/metrics/TenantMetricsTrackerImpl.java
events/main/pom.xml
events/main/src/main/resources/application.yml
metrics-processor/main/pom.xml
metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tenantmetrics/TenantMetricsTracker.java
metrics-processor/main/src/main/java/org/opennms/horizon/tenantmetrics/impl/TenantMetricsTrackerImpl.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/MetricNameConstants.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/TaskSetResultProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorAzureResponseProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorResultProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorSnmpResponseProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/detector/TaskSetDetectorResultProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/monitor/TaskSetMonitorResultProcessor.java
metrics-processor/main/src/main/resources/application.yml
metrics-processor/main/src/test/java/org/opennms/horizon/flows/FlowProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/TSDataProcessorTest.java
metrics-processor/pom.xml
metrics-processor/timeseries/pom.xml

Counting metrics and flows per tenant. Additionally - refactoring TSDataProcessor into separate classes so its less complicated.
- https://issues.opennms.org/browse/HS-1152

Add tenant metrics collection for metrics and flow samples

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumer.java
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/repository/IcmpActiveDiscoveryRepositoryTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/repository/IpInterfaceRepositoryTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/repository/SnmpConfigRepositoryTest.java

remove code related to TenantID annotation from inventory, as some was missed when removing this first time round.
- https://issues.opennms.org/browse/HS-1272
n/a

HS-1272: remove code related to TenantID annotation from inventory

---

ui/components.d.ts
ui/src/components/MonitoringPolicies/MonitoringPoliciesCard.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesCardAlertRow.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesEventCondition.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesExistingItems.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesThresholdCondition.vue
ui/src/components/MonitoringPolicies/monitoringPolicies.constants.ts
ui/src/components/MonitoringPolicies/monitoringPolicies.utils.ts
ui/src/store/Queries/monitoringPoliciesQueries.ts
ui/src/store/Views/monitoringPoliciesStore.ts
ui/src/types/policies.d.ts

Handles alert conditions for both threshold and events
- https://issues.opennms.org/browse/HS-1111

HS-1111: MP Alert Conditions

---

rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/alert/MonitorPolicyMapper.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/alert/PolicyRuleMapper.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/alert/TriggerEventMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/BaseModel.java
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/MonitorPolicy.java
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/PolicyRule.java
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/TriggerEvent.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/AlertsClient.java
rest-server/src/main/resources/application.yml
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientDeadlineTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientTest.java

- https://issues.opennms.org/browse/HS-1273
- https://issues.opennms.org/browse/HS-1091
- https://issues.opennms.org/browse/HS-1090
- https://issues.opennms.org/browse/HS-1085

HS-1273 BFF: endpoints monitor policy

---

metrics-processor/main/pom.xml
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorAzureResponseProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorResultProcessor.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorSnmpResponseProcessor.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/TSDataProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorAzureResponseProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorResultProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorSnmpResponseProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/detector/TaskSetDetectorResultProcessorTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/monitor/TaskSetMonitorResultProcessorTest.java
shared-lib/azure/proto/src/main/proto/azure-api.proto

- https://issues.opennms.org/browse/HS-1306

HS-1306: refactor tests for the refactored TSDataProcessor.

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/tags/NodeTaggingStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLNodeServiceTest.java
shared-lib/inventory/src/main/proto/nodeService.proto
shared-lib/protobuf/src/main/proto/nodescan.proto

HS-1217: Get nodes for a list of tags
Also removing unused passive discovery id variable in node scan
```
query {
findAllNodesByTags(tags: ["tag"]) {
id,
tenantId,
nodeLabel,
createTime,
}
}
```
- https://issues.opennms.org/browse/HS-1217

HS-1217: Get nodes for a list of tags

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/DiscoveryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/AddDiscoveryResponseData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/AddDiscoveryResponseWrapper.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/AddDiscoveryResult.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/helper/TestsExecutionHelper.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature

Simple discovery test that check that we have discovery working and creating a node that has been discovered. 
- https://issues.opennms.org/browse/HS-1280

Discovery test  HS-1280

---

alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEngine.java
alert/src/main/resources/application.yaml
alert/src/test/java/org/opennms/horizon/alertservice/grpc/AbstractGrpcUnitTest.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/AlertGrpcServiceTest.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/testcontainers/TestContainerRunnerClassRule.java
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/AlertResponse.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/AlertsClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLAlertsServiceTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientDeadlineTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientTest.java
shared-lib/events/src/main/proto/alerts.proto

o add severity filter
o add time filter ('today', '24h', '7d')
o add severity and time filter
o update cucumber test
HS-1285
Add filter to list alerts
module:
alert
rest-server
- https://issues.opennms.org/browse/HS-1285

HS-1285: Add filter to list alerts

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java

Adding more logging to testing
- https://issues.opennms.org/browse/HS-1280
Do not approve this, it is only for testing

Adding more logging to tests

---

notifications/src/main/resources/application.yml

Ad-hoc fix for deployment issues in recent develop.
- https://issues.opennms.org/browse/HS-1371

HS-1371 Fix missing fallback value for configuration property.

---

ui/src/components/Discovery/DiscoveryListCard.vue
ui/src/components/Discovery/DiscoverySuccessModal.vue
ui/src/components/Discovery/discovery.text.ts

Text improvements required by Bonnie
https://issues.opennms.org/browse/HS-1094

HS-1094: update texts in discovery page

---

ui/src/containers/Alerts.vue
ui/src/store/Views/alertsStore.ts

- https://issues.opennms.org/browse/HS-1259

HS-1259 Api UI updates

---

ui/tests/Alerts/alerts.test.ts
ui/tests/Alerts/alertsCard.test.ts
ui/tests/Alerts/alertsCardList.test.ts
ui/tests/Alerts/alertsSeverityCard.test.ts
ui/tests/Alerts/alertsSeverityFilters.test.ts
ui/tests/Alerts/alertsSeverityLabel.test.ts

- https://issues.opennms.org/browse/HS-1382

HS-1382 Fix Alerts test breaking CI

---

ui/tests/Alerts/alerts.test.ts
ui/tests/Alerts/alertsCard.test.ts
ui/tests/Alerts/alertsCardList.test.ts

Fix the pipeline.
- https://issues.opennms.org/browse/HS-1382

HS-1382: Remove imports from mockgql server for unused tests

---

ui/src/store/Views/alertsStore.ts

- https://issues.opennms.org/browse/HS-1386

HS-1386 Adjust api changes

---

alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertDefinitionRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/mapper/MonitorPolicyMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/mapper/PolicyRuleMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/mapper/TriggerEventMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/main/resources/db/changelog/hs-0.1.0/data/alert_definition_test_data.xml
alert/src/test/java/org/opennms/horizon/alertservice/CucumberRunnerIT.java
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature

HS-1392: Fixed the error and cucumber test: short term solution

---

alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java

Quick debug by adding more debug message

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumer.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumerTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/flows/FlowProcessorTest.java

Attempt to fix flaky test
- https://issues.opennms.org/browse/HS-1390
- https://issues.opennms.org/browse/HS-1393

HS-1390: fix flaky test

---

rest-server/src/main/java/org/opennms/horizon/server/model/flows/ExporterFilter.java
rest-server/src/main/java/org/opennms/horizon/server/service/flows/FlowClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/FLowClientTest.java

- https://opennms.atlassian.net/browse/HS-1413

HS-1413: simplify exporter parameter and add includeOther

---

charts/opennms/templates/cortex/cortex-configmap.yaml
charts/opennms/templates/cortex/cortex-deployment.yaml
charts/opennms/templates/cortex/cortex-service.yaml
charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/opennms/values.yaml

cortex-config-update-helm

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/MetricsTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/MinionData.java

Refactoring test cases to reduce code repetition 
- https://issues.opennms.org/browse/HS-1307

HS 1307 refactoring external it tests

---

ui/src/components/Alerts/AlertsSeverityLabel.vue
ui/src/styles/_severities.scss

- https://issues.opennms.org/browse/HS-1259

HS-1259 Fix severity pills color

---

external-it/hs-system-tests/pom.xml
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/AddNewInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/DeleteInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstancePage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalLoginPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalSnackBar.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalCloudSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalSnackBarSteps.java
external-it/hs-system-tests/src/test/resources/features/create-instance.feature
external-it/hs-system-tests/src/test/resources/selenide.properties

[WIP] Jira/hs 1434 portal tests

---

rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java
rest-server/src/main/java/org/opennms/horizon/server/service/flows/FlowClient.java
rest-server/src/main/java/org/opennms/horizon/server/service/flows/GrpcFlowService.java
rest-server/src/test/java/org/opennms/horizon/server/RestServerApplicationTests.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/FLowClientTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/GrpcFlowServiceTest.java

Also make sure proper passing application in request
- https://issues.opennms.org/browseHS-1450

HS-1450: translate nodeId to interfaceId for flow querier

---

external-it/hs-system-tests/README.md
external-it/hs-system-tests/pom.xml
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/HSCucumberRunnerTest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/keyvalue/SecretsStorage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalLoginSteps.java
external-it/hs-system-tests/src/test/resources/features/create-instance.feature

Jira Issue: https://opennms.atlassian.net/browse/HS-1463 
We need to store some sensitive data for tests, so KeyVault is a good option to do that.

[HS-1463] Support to azure key vault

---

ui/src/containers/Flows.vue
ui/src/store/Queries/flowsQueries.ts
ui/src/store/Views/flowsStore.ts
ui/tests/Flows/flows.test.ts

Adds autocomplete for Exporter to allow a user to few a certain exporters flows.
- https://issues.opennms.org/browse/HS-1440
Exporter Code.

Feature/HS-1440 - Add exporter autocomplete. Add Refresh functionality. Add total flows code.

---

ui/components.d.ts
ui/src/components/Common/InstructionsStepper.vue
ui/tests/Common/instructionsStepper.test.ts

- https://issues.opennms.org/browse/HS-1470

HS-1470 Add instructions stepper generic component

---

alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature

- https://issues.opennms.org/browse/HS-1486

Fixed cucumber tests

---

notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/api/email/EmailAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/email/Velocity.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/main/resources/alert.html.vm
notifications/src/main/resources/application.yml
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPITest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/email/VelocityTest.java
notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationServiceImplTest.java
notifications/src/test/resources/application.yml
notifications/src/test/resources/test.txt.vm
parent-pom/pom.xml

A step up from a regular plain text email. Content of the email is out of scope for this PR and will be reworked by technical writing team.
Sample email from integration test:
- https://issues.opennms.org/browse/HS-1399

HS-1399 Add Velocity template for alert notification emails

---

ui/src/components/Flows/LineChart.vue
ui/src/components/Flows/TableChart.vue
ui/src/containers/Flows.vue
ui/src/dtos/chartJS.dto.ts
ui/src/store/Views/flowsStore.ts
ui/tests/Flows/flows.test.ts

Added a DTO. This DTO will convert the data we receive from the BE, look for objects with the same timestamp and label, add these together and make a new object and remove the old object to calculate the total of inbound and outbound data to make an array of totals. Moved some methods about to improve performance.
- https://issues.opennms.org/browse/HS-1439
Chart DTO

HS-1439 - Add Line chart traffic. Refactor performance.

---

keycloak-ui/themes/horizon-stream/common/resources/js/mode.js
ui/src/App.vue
ui/src/components/Layout/NavigationRail.vue
ui/src/components/Layout/NavigationRailNavItem.vue
ui/src/composables/useTheme.ts
ui/src/main.ts

This wraps the `FeatherAppRailNavItem` components with a `router-link`. There was a good amount of duplicate code so I moved it to its own component.
Pages will no longer fully refresh when clicking things in the navbar. Layout and style should be exactly the same.
I was able to debug the reason text is black in the sidebar, it appears to be a FeatherDS bug caused by styles depending on CSS import order. I didn't include a fix for that in this PR.
I've also removed the redirectUri-based theming for Keycloak, it now uses localStorage.
- https://issues.opennms.org/browse/HS-280

HS-280: Improve routing in NavigationRail

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEngine.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature

Mainly adding tests to show that thresholded alerts can be cleared.
- https://issues.opennms.org/browse/HS-1475
n/a

HS-1475: Allow for clearing thresholded alerts

---

external-it/hs-system-tests/pom.xml
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/ServiceGenerator.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/OktaEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalApi.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/AuthnRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/AuthnResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/BtoInstanceRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/BtoInstancesResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/TokenResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/keyvalue/SecretsStorage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java

Tests create some instances, so now they delete all of them when they finished.

[HS-1461] clean up after tests

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature

Realised I had failed to add a test for the scenario when we have say 3 events needed in 10 minutes, and we have 3 events, but they come in over a period of 15 minutes say.
- https://issues.opennms.org/browse/HS-1475
n/a

HS-1475: add test

---

rest-server/src/main/java/org/opennms/horizon/server/service/grpc/MinionCertificateManagerClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/MinionCertificateManagerClientTest.java
rest-server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

HS-1309: pure white-box unit test for MinionCertificateManagerClient.

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java

Previously not possible to remove tags from a node
- https://issues.opennms.org/browse/HS-1423
n/a

HS-1423: fix remove tag from node issue

---

ui/components.d.ts
ui/src/components/Appliances/AppliancesAddNodeCtrl.vue
ui/src/components/Common/CountColor.vue
ui/src/components/Common/HeadlineSection.vue
ui/src/components/Common/HoverMenu.vue
ui/src/components/Common/PillColor.vue
ui/src/components/Locations/LocationsCard.vue
ui/src/components/Locations/LocationsList.vue
ui/src/containers/Locations.vue
ui/src/store/Views/locationsStore.ts
ui/tests/Common/headlineSection.test.ts
ui/tests/Locations/locationsCard.test.ts
ui/tests/Locations/locationsList.test.ts

- https://issues.opennms.org/browse/HS-1469

HS-1469 Fix fail tests

---

external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/CloudAuthErrorPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/CloudLeftPanelPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/CloudLoginPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudAuthErrorSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLeftPanelSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalCloudSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PrepareDataSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/utils/TestDataStorage.java
external-it/hs-system-tests/src/test/resources/cloud-features/tenant-authorization.feature

- Add hack for logout from okta for instance authorization.
- Add steps for `Given` where prepare data via Portal API
- Add some classes for Instance authorization pages

[HS-1497] Add instance authorization tests

---

external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalApi.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/DeleteInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstanceNamePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstancePage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudAuthErrorSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/DeleteInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceNameSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalCloudSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PrepareDataSteps.java
external-it/hs-system-tests/src/test/resources/portal-features/delete-instance.feature

- Add PageObject and Steps for DeleteInstance feature
- Add scenarios for DeleteInstance feature

[HS-1504] Delete instance feature

---

external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstanceNamePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalSnackBar.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceNameSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalSnackBarSteps.java
external-it/hs-system-tests/src/test/resources/portal-features/create-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/edit-instance.feature

- cosmetic changes for create-instance.feature (replace ' ' to " " for string values)
- Add PageObject, Steps and tests for Edit instance functionality

[HS-1521] edit instance tests

---

external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/ServiceGenerator.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/BtoInstancesResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/CloudAuthErrorPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/ConfirmDeleteMinionPopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/AddNewInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/DeleteInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstanceNamePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstancePage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ApplianceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudAuthErrorSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/ConfirmDeleteMinionSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/UdpGenSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/DeleteInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceNameSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalCloudSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PrepareDataSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/utils/TestDataStorage.java
external-it/hs-system-tests/src/test/java/testcontainers/MinionContainer.java
external-it/hs-system-tests/src/test/java/testcontainers/UpdGenContainer.java
external-it/hs-system-tests/src/test/resources/portal-features/cloud-summary.feature
external-it/hs-system-tests/src/test/resources/portal-features/create-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/delete-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/edit-instance.feature

- Fix naming problems in existed scenarios
- Add more specific locators for error texts
- Add PO, Steps and Scenarios for Summary page
- https://issues.opennms.org/browse/HS-1526

[HS-1526] Add tests for Summary page functionality, add small fixes to other scenarios

---

ui/src/components/Dashboard/dashboard.text.ts
ui/src/components/Discovery/DiscoverySyslogSNMPTrapsForm.vue
ui/src/components/NodeStatus/EventsTable.vue
ui/src/components/NodeStatus/IPInterfacesTable.vue
ui/src/components/NodeStatus/NodeInfoTable.vue
ui/src/components/NodeStatus/SNMPInterfacesTable.vue
ui/src/containers/Discovery.vue
ui/src/containers/NodeStatus.vue
ui/src/graphql/Views/nodeStatusQueries.graphql
ui/src/store/Queries/discoveryQueries.ts
ui/src/store/Views/nodeStatusStore.ts
ui/src/types/graphql.ts

For azure nodes, hides the snmp table and renames ip interfaces to network interfaces.
Fixes bugs for the discovery toggle.
Fixes typo.
- https://issues.opennms.org/browse/HS-1549
- https://issues.opennms.org/browse/HS-1530
- https://issues.opennms.org/browse/HS-1479

Fix node status page for azure types

---

minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/SimpleReconnectStrategy.java
minion/minion-ipc/ipc-heartbeat/src/main/java/org/opennms/horizon/minion/ipc/heartbeat/internal/HeartbeatProducer.java
parent-pom/pom.xml

JIRA: https://opennms.atlassian.net/browse/HS-1384
This doesn't solve the problem completely, but does address some known stability issues which I believe are worth getting in while we continue to dive deeper.
Changes include:
* Upgrade gRPC from 1.43.2 to 1.54.1 (includes a Netty upgrade and addresses some race conditions)
* Address synchronization problems in the SimpleReconnectStrategy class

HS-1384: Improve stability/recovery of gRPC connections

---

alert/src/main/java/org/opennms/horizon/alertservice/db/entity/Alert.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertMapper.java
alert/src/main/resources/db/changelog/changelog.xml
alert/src/main/resources/db/changelog/hs-0.1.0/tables/update_alert_trigger_event.xml
shared-lib/alert/src/main/proto/alerts.proto

Return monitoring policy rule event name in alerts list
- https://issues.opennms.org/browse/HS-1511
Still requires some work from ui side
(nodeName in alerts.proto is required in HS-1510, which will be done next)

HS-1511: Back end work to display monitoring policy rule event name in alerts list

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/TSDBMetricsService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/normalization/Constants.java
rest-server/src/test/java/org/opennms/horizon/server/metrics/DurationRangeTest.java
ui/src/components/NodeStatus/NodeStatusMetricsModal.vue
ui/src/containers/Graphs.vue

Update queries for network_in_bits/network_out_bits.
Separate range queries
- https://issues.opennms.org/browse/HS-1335

HS-1335: Add network_in_bits/network_out_bits

---

notifications/src/main/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/config/EmailConfig.java
notifications/src/test/java/org/opennms/horizon/notifications/api/email/SmtpEmailAPITest.java

In case email sending fails due to some transient issue (like failure to connect to the SMTP relay), we should continue to retry the sending for best effort delivery.
Tested that email delivery still works as expected when bringing the whole system up via Tilt.
- https://issues.opennms.org/browse/HS-1563

HS-1563 Add retries when sending email via SMTP

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/NodeMonitoringManager.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/NodeMonitoringManagerTest.java

Add tags from a passive discovery definition onto nodes which are discovered.
- https://issues.opennms.org/browse/HS-1498
None

HS-1498: Add tags to node with passive discovery

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/normalization/Constants.java

- https://issues.opennms.org/browse/HS-1557

HS-1557: Add Errors In/Out queries

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/discovery/PassiveDiscoveryService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/PassiveDiscoveryServiceTest.java

Allow update to keep the same location
Validate community string according to rules in ticket
- https://issues.opennms.org/browse/HS-1332
Not sure of validation requirement for community strings and comma's. I have implemented as per my understanding from the ticket.

HS-1332: Passive discovery validations

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/TSDBMetricsService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/normalization/Constants.java

HS-1375: Azure bits In/Out prometheus query
- https://issues.opennms.org/browse/HS-1375

HS-1375: Azure bits In/Out prometheus query

---

minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/MinionGrpcClientTest.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/queue/OffHeapSendQueueFactoryTest.java

- https://issues.opennms.org/browse/HS-1363

HS-1363: cleanup all the streams on disconnect.

---

minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/ValueTest.java

https://opennms.atlassian.net/browse/HS-1473

HS-1473 Enrich ValueTest with missing test cases

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/RpcConnectionTrackerImpl.java

- https://issues.opennms.org/browse/HS-1379

HS-1379: Fix minion cleanup in Gateway

---

minion/assembly/runInDocker.sh

Added extraction of certs from Tilt and several options to customize connection points.
- https://issues.opennms.org/browse/HS-1310

HS-1310 Update run in docker script so it behaves similar to runInPlace.

---

ui/src/components/Dashboard/DashboardApplications.vue
ui/src/components/Dashboard/DashboardCard.vue
ui/src/containers/Dashboard.vue

Fixes this issue at request of PO:
- https://issues.opennms.org/browse/HS-1593

HS-1593: Fix top 10 legend on smaller screens

---

ui/components.d.ts
ui/src/components/Dashboard/DashboardApplications.vue
ui/src/components/Flows/LineChart.vue
ui/src/components/Flows/TableChart.vue
ui/src/components/Graphs/LineGraph.vue

- https://issues.opennms.org/browse/HS-1370
Update Axis Lines on theme change.

HS-1370 - Change graph line colours on theme change.

---

ui/src/components/Graphs/LineGraph.vue
ui/tests/Flows/flows.test.ts

- https://issues.opennms.org/browse/HS-1370

HS-1370 - Fix Broken tests

---

inventory/docker-it/pom.xml
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/InventoryBackgroundHelper.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/tags/NodeTaggingStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
inventory/main/pom.xml
inventory/main/src/main/java/org/opennms/horizon/inventory/component/TagPublisher.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/main/src/main/resources/application.yml
inventory/main/src/test/java/org/opennms/horizon/inventory/SpringContextTestInitializer.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/TagPublisherTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java

This PR is related to https://github.com/OpenNMS-Cloud/horizon-stream/pull/1059
- https://issues.opennms.org/browse/HS-1509

HS-1509 publish tag operation on node to Kafka in the inventory service

---

inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/discovery/AzureActiveDiscoveryGrpcItTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/discovery/IcmpActiveDiscoveryGrpcItTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/discovery/PassiveDiscoveryGrpcItTest.java
inventory/main/src/test/resources/logback-test.xml

Disable failing test 
- https://issues.opennms.org/browse/HS-1605

HS-1605: Disable failing test

---

alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/NodeRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/AlertGrpcServiceTest.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/node.feature
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/Alert.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/AlertsClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLAlertsServiceTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientDeadlineTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientTest.java
shared-lib/alert/src/main/proto/alerts.proto

Mike asked for the ability to search by node label within list alerts
- https://issues.opennms.org/browse/HS-1317
n/a

HS-1317: Added node label as search parameter for listAlerts

---

alert/src/main/java/org/opennms/horizon/alertservice/service/routing/KafkaConfig.java

fix tech debt
- https://issues.opennms.org/browse/HS-1529
n/a

HS-1529: Remove hard coded alerts topic

---

charts/opennms/templates/keycloak/keycloak-deployment.yaml
charts/opennms/values.yaml

HS-1610 Align secret naming strategy.

---

metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/DocumentEnricherTest.java
metrics-processor/main/src/test/java/org/opennms/horizon/flows/grpc/client/IngestorClientTest.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/transport/IpFixMessageBuilder.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/transport/Netflow5MessageBuilder.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/transport/Netflow9MessageBuilder.java
shared-lib/flows/src/main/proto/flow_document.proto

https://opennms.atlassian.net/browse/HS-1247

HS-1247 NetflowV5 doesn't have  tag

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/normalization/Constants.java

HS-1612: Add labels to azure metrics queries
- https://issues.opennms.org/browse/HS-1612

HS-1612: Add labels to azure metrics queries

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java

- https://issues.opennms.org/browse/HS-1588

HS-1588: Add errors in/out to range queries

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/IcmpDiscoveryStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/icmp-active-discovery.feature
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/discovery/IcmpActiveDiscoveryGrpcItTest.java

move flaky IT test into cucumber test
- https://issues.opennms.org/browse/HS-1615
n/a

HS-1615: move flaky IT test into cucumber test

---

events/main/src/main/resources/application.yml

After HS-1591 this KafkaTemplate's config broke, this readds it. 
- https://issues.opennms.org/browse/HS-1624

HS-1624: Fix missing config for Kafka producer serializers

---

minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/channel/SSLChannelFactory.java

Added basic check for blank parameters, just like for keystore.
- https://issues.opennms.org/browse/HS-1625

HS-1625 Do not configure trust store if its not specified

---

ui/tests/Inventory/inventoryTabContent.test.ts

Fixes inventory test
- https://issues.opennms.org/browse/HS-1632

HS-1632: Fix inventory test

---

ui/src/store/Queries/inventoryQueries.ts

Add the management ip for unmonitored nodes.
- https://issues.opennms.org/browse/HS-1632

HS-1632: Fix card for unmonitored nodes

---

charts/opennms/templates/kafka/kafka-deployment.yaml
charts/opennms/templates/kafka/kafka-service.yaml
charts/opennms/templates/opennms/alert/alert-deployment.yaml
charts/opennms/templates/opennms/datachoices/datachoices-deployment.yaml
charts/opennms/templates/opennms/events/events-deployment.yaml
charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/opennms/templates/opennms/minion/minion-gateway-deployment.yaml
charts/opennms/templates/opennms/notification/notification-deployment.yaml
charts/opennms/values.yaml

- https://issues.opennms.org/browse/HS-1474

HS-1474 - update for external kafka config.

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/InventoryBackgroundHelper.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/AzureDiscoveryStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/azure-discovery.feature

HS-1622: Move azure IT tests to cucumber
- https://issues.opennms.org/browse/HS-1622
n/a

HS-1622: Move azure IT tests to cucumber

---

ui/src/components/Common/InstructionsStepper.vue
ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsEditForm.vue

Add autocomplete address to add locations form.
- https://issues.opennms.org/browse/HS-1628
-

HS-1628 - Add auto address component to add location form

---

inventory/main/src/main/java/org/opennms/horizon/inventory/model/MonitoringLocation.java
inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/monitoring-location.xml
rest-server/src/main/java/org/opennms/horizon/server/mapper/MonitoringLocationMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoringLocationCreate.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoringLocationUpdate.java

Fix last PR [HS-1539 ](https://github.com/OpenNMS-Cloud/horizon-stream/pull/1076) cause liquibase error
- https://opennms.atlassian.net/browse/HS-1539

HS-1539: fix liquibase latitude not null constrain issue

---

ui/src/components/Dashboard/DashboardNetworkTraffic.vue

BE now returns a more granular dataset for the dashboard total network graph. This updates the x-axis to accommodate that change.
Also converts y-axis values to the units of the appropriate [SI prefix](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes), which makes it consistent with the node status page graphs.
- https://issues.opennms.org/browse/HS-1554

HS-1554: Fix total network graph granularity

---

charts/opennms/Chart.yaml
charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/opennms/values.yaml

Split Cortex Read & Write paths into different values
- https://issues.opennms.org/browse/HS-170

BTO-170 - Split Cortex Read & Write paths into different values

---

external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/LocationData.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/FindAllLocationsData.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature
install-local/install-local-opennms-horizon-stream-custom-images-values.yaml
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/CommonStepDefinitions.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/active-discovery-tagging.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/azure-discovery.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/icmp-active-discovery.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-metrics.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/component/NodeMonitoringManager.java
inventory/main/src/main/java/org/opennms/horizon/inventory/exception/LocationNotFoundException.java
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumerTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/NodeMonitoringManagerTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java
shared-lib/horizon-grpc-common-constants/src/main/java/org/opennms/horizon/shared/constants/GrpcConstants.java

This is an updated version of #1068 made by Benjamin, but applied against current develop. I keep old branch and PR as a reference point in case of issues with this change set.
- https://issues.opennms.org/browse/HS-1519
-

HS-1519 Remove autoamtic creation of location in inventory

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumer.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumerTest.java

Address failure while creating Minion
- https://issues.opennms.org/browse/HS-1662

HS-1662: Fix lazy initialization exception

---

rest-server/src/main/java/org/opennms/horizon/server/model/inventory/MonitoringLocation.java
ui/src/components/Common/AddressAutocomplete.vue
ui/src/components/Discovery/DiscoveryLocationsAutocomplete.vue
ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsEditForm.vue
ui/src/components/Map/MapNodesGrid.vue
ui/src/graphql/Location/locationMutations.gql
ui/src/graphql/Location/locationQueries.gql
ui/src/store/Mutations/locationMutations.ts
ui/src/store/Views/locationStore.ts
ui/src/store/Views/mapStore.ts
ui/src/types/graphql.ts
ui/src/types/locations.d.ts
ui/tests/fixture/locations.ts
ui/tests/fixture/minions.ts

- https://opennms.atlassian.net/browse/HS-1648

HS-1648: FE - pass long/lat and address to BFF

---

.github/workflows/develop.yml
charts/opennms/templates/opennms/minion-certificate-manager/minion-certificate-manager-deployment.yaml
external-it/external-horizon-stream-it/pom.xml
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/GQLQueryConstants.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/gqlmodels/querywrappers/FindAllLocationsQueryResult.java
external-it/external-horizon-stream-it/src/main/java/org/opennms/horizon/it/helper/TestsExecutionHelper.java
external-it/external-horizon-stream-it/src/main/resources/org/opennms/horizon/it/horizon-stream.feature
install-local/install-local-opennms-horizon-stream-custom-images-values.yaml
install-local/install-local.sh

End to end tests involving client certificates.
- https://issues.opennms.org/browse/HS-1637

HS-1637 End to end tests with minion secure connection

---

ui/package.json
ui/tests/Common/headlineSection.test.ts
ui/tests/mountWithPiniaVillus.ts
ui/yarn.lock

Update Vue to make use of imported types for props, script setup generics etc. [v3.3.4](https://blog.vuejs.org/posts/vue-3-3)
- https://issues.opennms.org/browse/HS-1665

HS-1665: Update vue and ancillary pckgs

---

charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/opennms/values.yaml
metrics-processor/main/src/main/java/org/opennms/horizon/flows/FlowsApplicationConfig.java
rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java

- https://issues.opennms.org/browse/HS-1669

HS-1669: force plaintext connection for flows

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/GrpcTwinPublisher.java

- https://issues.opennms.org/browse/HS-989

HS-989: Fix twin update failure when one of the subscriber dies

---

ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsCard.vue
ui/src/components/Locations/LocationsEditForm.vue
ui/src/components/Locations/LocationsMinionsCard.vue
ui/src/store/Views/locationStore.ts
ui/src/types/locations.d.ts

Adds the `Edit` and `Delete` context menu items for locations.
Adds the `Delete` context menu item for minions.
Removes placeholder icons as per UX suggestion.
- https://issues.opennms.org/browse/HS-1672

HS-1672: Fix locations edit and delete context menu items

---

operator/sonar-project.properties
ui/sonar-project.properties

Sets `sonar.projectName` to change the names of these projects.
- https://issues.opennms.org/browse/BTO-500

BTO-500: Change Sonarcloud project names to Lokahi for Operator and UI

---

install-local/install-local-opennms-lokahi-values.yaml
install-local/install-local.sh

updated lokahi name ref and image versions

---

inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/GrpcTestBase.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcItTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcStartupIntTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/TagGrpcItTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/integration/FlowRepositoryImplTest.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/DocumentEnricherTest.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/impl/FlowDocumentBuilderClassificationRequestMapperImplTest.java

Fix build failures ( by disabling tests for now)
- https://issues.opennms.org/browse/HS-1687

HS-1687: Disable failing tests

---

ui/package.json
ui/src/components/Common/HoverMenu.vue
ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsCard.vue
ui/src/components/Locations/LocationsCertificateDownload.vue
ui/src/components/Locations/LocationsEditForm.vue
ui/src/components/Locations/LocationsMinionsList.vue
ui/src/components/utils.ts
ui/src/containers/Locations.vue
ui/src/store/Mutations/locationMutations.ts
ui/src/store/Queries/minionsQueries.ts
ui/src/store/Views/locationStore.ts
ui/src/types/index.ts
ui/src/types/locations.d.ts
ui/tests/Common/emptyList.test.ts
ui/tests/Locations/locations.test.ts
ui/tests/Locations/locationsEditForm.test.ts
ui/yarn.lock

Show download cert component immediately after a location is created.
Fix css for hover menu. 
Move d/l functions to utils.
Clear old minions on new api call.
[screencast-localhost_3009-2023.06.06-16_10_04.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/a3fd0b3e-6288-41e2-a015-c7cb9c7b661b)
- https://issues.opennms.org/browse/HS-1407

HS-1407: Show cert screen after location creation

---

charts/lokahi/templates/opennms/spring-boot-env-configmap.yaml

HS-1690: we should always set the default profile

---

ui/src/containers/Locations.vue
ui/src/store/Views/locationStore.ts

Fixes bug introduces in 1560
- https://issues.opennms.org/browse/HS-1560

HS-1560: Fix issue rendering minion list

---

charts/lokahi-operator/Chart.yaml
charts/lokahi-operator/templates/operator.yaml
charts/lokahi/Chart.yaml
charts/lokahi/templates/cortex/cortex-deployment.yaml
charts/lokahi/templates/grafana/grafana-deployment.yaml
charts/lokahi/templates/ingress/custom-errors/nginx-errors-deployment.yaml
charts/lokahi/templates/ingress/nginx-controller/controller-deployment.yaml
charts/lokahi/templates/kafka/kafka-deployment.yaml
charts/lokahi/templates/keycloak/keycloak-deployment.yaml
charts/lokahi/templates/mail-server/mail-server-deployment.yaml
charts/lokahi/templates/opennms/alert/alert-deployment.yaml
charts/lokahi/templates/opennms/api/api-deployment.yaml
charts/lokahi/templates/opennms/datachoices/datachoices-deployment.yaml
charts/lokahi/templates/opennms/events/events-deployment.yaml
charts/lokahi/templates/opennms/inventory/inventory-deployment.yaml
charts/lokahi/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-manager/minion-certificate-manager-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-manager/minion-certificate-verifier-deployment.yaml
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
charts/lokahi/templates/opennms/minion/minion-gateway-deployment.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
charts/lokahi/templates/opennms/ui/ui-deployment.yaml
charts/lokahi/templates/postgres/postgres-deployment.yaml
charts/lokahi/templates/prometheus/prometheus-deployment.yaml
install-local/install-local-snmpd-device.yaml
install-local/postgres-for_testing_keycloak_realm_update.yaml
ui/internal-reverse-proxy.yaml

- https://issues.opennms.org/browse/BTO-535

BTO-535: Add default-container annotation for all Deployments

---

.github/pull_request_template.md
.github/workflows/develop.yml
.github/workflows/tilt.yaml

- https://issues.opennms.org/browse/BTO-509

Add a new GitHub workflow to test 'tilt ci'

---

metrics-processor/flows/src/main/java/org/opennms/horizon/flows/integration/FlowRepositoryImpl.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/integration/FlowRepositoryImplTest.java

- https://opennms.atlassian.net/browse/HS-1711

HS-1711: make sure tenantId is sent to DP

---

external-it/hs-system-tests/README.md
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalApi.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/GetInstanceUsersResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/PostInstanceUserRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/keyvalue/SecretsStorage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/cloud/CloudLoginPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/AddNewInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/AddUserPopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstancePage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/PortalCloudPage.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddNewInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/AddUserSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/DeleteInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/EditInstanceSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalCloudSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PortalSnackBarSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PrepareDataSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/utils/TestDataStorage.java
external-it/hs-system-tests/src/test/resources/cloud-features/tenant-authorization.feature
external-it/hs-system-tests/src/test/resources/portal-features/cloud-summary.feature
external-it/hs-system-tests/src/test/resources/portal-features/create-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/delete-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/edit-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/member-role.feature

- Add PO, Steps and Scenarios for Member user
- Renamed Steps to be more generic
- Add API calls to add/revoke users
- https://issues.opennms.org/browse/HS-1537

HS-1537: Portal: Add scenarios for MEMBER user

---

external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/OktaEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalApi.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/PortalEndpoints.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/AddInstanceUserRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/AuthnRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/AuthnResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/CloudInstanceRequest.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/CloudInstancesResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/GetInstanceUsersResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/api/portal/models/TokenResponse.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/AddUserPopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/DeleteInstancePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/pages/portal/EditInstanceNamePopup.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/CloudLoginSteps.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/portal/PrepareDataSteps.java
external-it/hs-system-tests/src/test/resources/cloud-features/tenant-authorization.feature
external-it/hs-system-tests/src/test/resources/portal-features/cloud-summary.feature
external-it/hs-system-tests/src/test/resources/portal-features/create-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/delete-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/edit-instance.feature
external-it/hs-system-tests/src/test/resources/portal-features/member-role.feature

- Update automation code to swap out `BTO` instance for `cloud` instance.
- Use IDs in a few more places, preferred to CSS lookups.
- https://opennms.atlassian.net/browse/HS-1714
- N/A

HS-1714: Integration Test: Portal: Re-naming

---

ui/src/components/Layout/NavigationRail.vue
ui/src/router/index.ts

Demo feedback:
- Hide the Map.
- Change the name of the "Appliances" page to "Minions".
- https://opennms.atlassian.net/browse/HS-1726

HS-1726: Demo feedback - hide map, rename appliances

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/MonitoringLocationStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/monitoring-location.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoringLocationService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/MonitoringLocationServiceTest.java

- https://issues.opennms.org/browse/HS-1540

HS-1540: delete all minion when location is deleted

---

minion/assembly/prepareLocationAndCerts.sh
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcLocationService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java

- https://opennms.atlassian.net/browse/HS-1742

HS-1742: add prepareLocationAndCerts.sh script for use with runInPlace.sh

---

ui/src/composables/useMinionCmd.ts

After further discussion, looks like this port change was needed after all. 
- https://opennms.atlassian.net/browse/HS-1631

HS-1631: Update ports for minion cmd

---

inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/discovery-inheritance.xml
inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/passive-discovery.xml
inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/snmp-config.xml

Fixed wrong lookups (made them tenant aware) and added removal of data which is not linked to a valid location.
- https://opennms.atlassian.net/browse/HS-1647
Schema migrations, migrations are modified in-place as they did not apply in dev cloud. For tilt it is recommended to re-create schema.

HS-1647 Update schema migrations.

---

.github/pull_request_template.md

NO PR: Update PR template - need to update template so that documentation team gets notified when screen names change, as this affects the product URLs and needs to be updated on the docs side.

NO PR: Update PR template

---

.github/workflows/develop.yml

pipeline-fix-workflows-delete-cluster-after-done

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java

- https://opennms.atlassian.net/browse/HS-1364

HS-1364: don't update the nodeLabel if one is already set.

---

charts/lokahi/templates/opennms/minion/minion-configmap.yaml

Fix minion port usage

---

README.md

- https://opennms.atlassian.net/browse/BTO-599

BTO-599-test

---

test-automation/integration-tests/README.md
test-automation/integration-tests/src/main/java/org/opennms/horizon/exttest/CucumberCommandLineRunner.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/exttest/TestMain.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/DiscoveryTestSteps.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/HorizonStreamTestSteps.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/helper/TestsExecutionHelper.java
test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/discovery-tests.feature
test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/lokahi.feature
test-automation/integration-tests/src/main/resources/snmpd/snmpd.conf
test-automation/integration-tests/src/main/resources/snmpd/snmpd_nondefaults.conf

Adding discovery integration tests, providing ability to pass cucumber options through the command line when running locally.
- https://opennms.atlassian.net/browse/HS-1680
* [x ] Follows Lōkahi's [development guidelines.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Development-Guidelines)
* [x ] Appropriate reviewer(s) have been selected.
* [x ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)

API based discovery tests

---

minion/minion-flows/flows-features/src/main/feature/feature.xml
minion/minion-flows/flows-parser/pom.xml
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/TcpListener.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/UdpListener.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/factory/TcpListenerFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/listeners/factory/UdpListenerFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/TelemetryRegistryImpl.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/IpfixTcpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/IpfixUdpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/Netflow5UdpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/Netflow9UdpParserFactory.java
minion/minion-flows/flows-parser/src/main/java/org/opennms/horizon/minion/flows/parser/factory/dnsresolver/NettyDnsResolver.java
minion/minion-flows/flows-parser/src/main/resources/OSGI-INF/blueprint/blueprint.xml
minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/parser/FlowsListenerTest.java
minion/minion-flows/flows-parser/src/test/java/org/opennms/horizon/minion/flows/shell/ClearUdpSessionCmdTest.java

- https://opennms.atlassian.net/browse/HS-1739

HS-1739: fix metric registry and add jmx reporter

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/tags/ActiveDiscoveryTaggingStepDefinitions.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/tags/NodeTaggingStepDefinitions.java
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/tags/PassiveDiscoveryTaggingStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/active-discovery-tagging.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/monitored-state.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/passive-discovery-tagging.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/model/Node.java
inventory/main/src/main/java/org/opennms/horizon/inventory/model/Tag.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java

… policies## Description
- https://opennms.atlassian.net/browse/HS-1545
- https://opennms.atlassian.net/browse/HS-1546
- https://opennms.atlassian.net/browse/HS-1547

HS-1545|HS-1546|HS-1547: Update monitored state depending on assigned policies

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcMinionCertificateManager.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLMinionCertificateManagerTest.java
ui/src/components/Locations/LocationsCertificateDownload.vue
ui/src/graphql/Location/locationMutations.gql
ui/src/store/Mutations/locationMutations.ts
ui/src/store/Views/locationStore.ts
ui/src/types/graphql.ts

- https://opennms.atlassian.net/browse/HS-1728

HS-1728: Revoke previous certificate upon regeneration request

---

alert/src/main/java/org/opennms/horizon/alertservice/db/entity/Alert.java
alert/src/main/java/org/opennms/horizon/alertservice/db/entity/AlertCondition.java
alert/src/main/java/org/opennms/horizon/alertservice/db/entity/AlertDefinition.java
alert/src/main/java/org/opennms/horizon/alertservice/db/entity/MonitorPolicy.java
alert/src/main/java/org/opennms/horizon/alertservice/db/entity/PolicyRule.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertConditionRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertDefinitionRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/MonitorPolicyRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/mapper/AlertConditionMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/mapper/PolicyRuleMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/main/resources/db/changelog/changelog.xml
alert/src/main/resources/db/changelog/hs-0.1.0/tables/rename_trigger_event_to_alert_condition.xml
alert/src/test/java/org/opennms/horizon/alertservice/repository/MonitoringPolicyRepositoryTest.java
alert/src/test/java/org/opennms/horizon/alertservice/service/AlertEventProcessorTest.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/MonitorPolicySteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature
alert/src/test/resources/org/opennms/horizon/alertservice/node.feature
alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature

TriggerEvent was fairly confusing, this brings the code in line with the frontend and requirements of monitoring policies.
This does not change the API or any other code that makes use of it, only the internals of the alert service. Changes to other services will come later.
- https://opennms.atlassian.net/browse/HS-1776

HS-1776: Rename TriggerEvent entity to AlertCondition

---

install-local/install-local-opennms-lokahi-values.yaml
test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/lokahi.feature

- https://opennms.atlassian.net/browse/BTO-551

BTO-551 - updating install local lokahi images

---

ui/src/components/Discovery/discovery.text.ts

Replaces BTO with Lōkahi
- https://opennms.atlassian.net/browse/HS-1794

HS-1794: Remove/replace 'BTO' in text

---

charts/lokahi/templates/opennms/minion/minion-configmap.yaml
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
charts/lokahi/values.yaml
minion/docker-assembly/pom.xml
minion/docker-assembly/src/main/docker/app/Dockerfile
minion/docker-assembly/src/main/docker/entrypoint/entrypoint.sh

BTO-696: minion: Sanity-check mTLS cert file and password on startup

---

charts/lokahi/values.yaml
tilt-helm-values.yaml

- BTO-521: Increase resources for minion-gateway to address OOM
- minion-gateway: re-enabled otel

BTO-521: give minion-gateway more resources to fix OOM and re-enable otel

---

inventory/main/pom.xml
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/ScannerTaskSetServiceTest.java
parent-pom/pom.xml

Support Ip range cidr notation
- https://opennms.atlassian.net/browse/HS-1642

HS-1642: Add support for cidr notation

---

events/conf/src/main/java/org/opennms/horizon/events/EventConstants.java
events/conf/src/main/resources/events/opennms.correlation.events.xml
parent-pom/pom.xml
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/DiscoveryTestSteps.java

Removes unused Drools dependency and a couple mentions in the code.
- https://opennms.atlassian.net/browse/HS-877
Nothing special here.

HS-877: Remove lingering Drools references

---

ui/components.d.ts
ui/src/components/Dashboard/DashboardNetworkTraffic.vue

Reverses the label order to correctly match the data.
- https://opennms.atlassian.net/browse/HS-1856

HS-1856: Fix labels for network traffic chart

---

ui/components.d.ts
ui/src/store/Views/welcomeStore.ts
ui/tests/store/Queries/welcomeQueries.test.ts
ui/tests/store/Views/welcomeStore.test.ts

Moving the creation of the default location to the second screen as per request.
- https://opennms.atlassian.net/browse/HS-1818
* ~~[ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~
* ~~[ ] Notify documentation team of any changes to names of screens or features (affects URLs).~~

HS-1818: Moving creation of default location

---

docs/modules/operation/pages/alerts/introduction.adoc
docs/modules/operation/pages/alerts/manage.adoc

Provides content on how alerts work, and how users can manage them (clear, acknowledge, search, filter).
- https://opennms.atlassian.net/browse/DP-40

DP-40: Update user documentation for alerts

---

notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyEventFactory.java
notifications/src/main/java/org/opennms/horizon/notifications/api/email/ACSEmailAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/kafka/MonitoringPolicyKafkaConsumer.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyAPITest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyEventFactoryTest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/email/ACSEmailAPITest.java
tests/.gitignore

Some minor fixes to the notification service:
- Add additional logging for traceability
- Capture ACS exceptions as NotificationExceptions
- Ensure PagerDuty events always have a summary
- Other minor cleanup
- https://opennms.atlassian.net/browse/HS-1860

HS-1860: Minor fixes to Notification Service

---

ui/src/components/Appliances/AppliancesNodesTable.vue
ui/src/store/Queries/appliancesQueries.ts

- https://opennms.atlassian.net/browse/LOK-1883

LOK-1883: fix minion page node latency

---

ui/tests/Locations/locationsCard.test.ts

Update the data-test name to fix the test.
- https://opennms.atlassian.net/browse/HS-1187

LOK-1187: Fix location card test

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureCollector.java
minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureScanner.java
minion/plugins/azure-plugin/src/test/java/org/opennms/horizon/minion/azure/AzureCollectorTest.java
minion/plugins/azure-plugin/src/test/java/org/opennms/horizon/minion/azure/AzureScannerTest.java
shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/AzureHttpException.java
shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/dto/error/AzureHttpError.java
shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/dto/instanceview/AzureInstanceView.java
shared-lib/azure/azure-http/src/main/java/org/opennms/horizon/shared/azure/http/dto/instanceview/VmAgent.java
shared-lib/azure/azure-http/src/test/java/org/opennms/horizon/shared/azure/http/dto/instanceview/AzureInstanceViewTest.java

- https://opennms.atlassian.net/browse/LOK-1887

LOK-1887: handle azure monitoring edge cases

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/InventoryPage.java

Adding intelligent handling of inventory node deletions for the UI tests.
- https://opennms.atlassian.net/browse/HS-1839

Intelligent handling when deleting inventory nodes in UI tests.

---

charts/lokahi/templates/opennms/alert/alert-deployment.yaml
charts/lokahi/templates/opennms/api/api-deployment.yaml
charts/lokahi/templates/opennms/datachoices/datachoices-deployment.yaml
charts/lokahi/templates/opennms/events/events-deployment.yaml
charts/lokahi/templates/opennms/inventory/inventory-deployment.yaml
charts/lokahi/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-manager/minion-certificate-manager-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-verifier/minion-certificate-verifier-deployment.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
charts/lokahi/templates/opennms/ui/ui-deployment.yaml

The Lokahi Helm Chart is probably one of the worst I've ever seen. The template is inconsistent with what you can change via `values.yaml`, so my original fix for the resource requests and limits was not working. This PR fixes the templates so the work I did initially can be deployed.
- https://opennms.atlassian.net/browse/BTO-707

BTO-707: Ensure consistency between templates and values file.

---

notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/api/email/ACSEmailAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/config/EmailConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java

Add logging to better trace through email notification flows. Adds a span for tracing in grafana, etc.
- https://opennms.atlassian.net/browse/LOK-1860

LOK-1860: Enhance email notification logging

---

charts/lokahi/values.yaml

I verified the symptoms and the solution via Tilt, as described on the Jira issue.
- https://opennms.atlassian.net/browse/BTO-782
- https://opennms.atlassian.net/browse/LOK-1644

BTO-782: remove limit for proxy-body-size.

---

ui/src/components/Discovery/discovery.text.ts

Fixes the discovery message to indicate the link goes to Monitored Nodes
- https://opennms.atlassian.net/browse/HS-1652

LOK-1652: Fix discovery message

---

ui/src/components/Layout/Menubar.vue

Get logout working with fedarated SSO with Keycloak.
- https://opennms.atlassian.net/browse/BTO-280

BTO-280 - uncommented for testing

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/test/java/org/opennms/horizon/alertservice/service/AlertEventProcessorTest.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/MonitorResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/TaskSetResultsConsumerTest.java
minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java

- https://opennms.atlassian.net/browse/HS-1917

LOK-1917: Alerts from Internal Events are missing Descriptions

---

docs/modules/installation/pages/installation.adoc
docs/modules/operation/pages/get-started/discovery/active.adoc
docs/modules/operation/pages/get-started/discovery/passive.adoc
docs/modules/operation/pages/get-started/policies/create.adoc
docs/modules/operation/pages/get-started/policies/introduction.adoc
docs/modules/operation/pages/get-started/policies/manage.adoc
docs/modules/operation/pages/inventory/introduction.adoc
docs/modules/operation/pages/inventory/nodes.adoc

Fixed some typos and broken links in the documentation.
- https://opennms.atlassian.net/browse/NO JIRA

No Jira: Docs typos

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/LocationsPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/WelcomePage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/LocationSteps.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/MinionSteps.java
test-automation/ui-tests/src/test/java/testcontainers/MinionContainer.java
test-automation/ui-tests/src/test/resources/docker-compose-minion.yaml
test-automation/ui-tests/src/test/resources/features/welcome.feature

adding stability to welcome wizard test

---

test-automation/ui-tests/src/test/resources/features/welcome.feature

change to delete minion last

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/WelcomeSteps.java
test-automation/ui-tests/src/test/resources/features/welcome.feature

no message

---

test-automation/flows-test-image/Dockerfile
test-automation/flows-test-image/README.md
test-automation/flows-test-image/bootstrap.sh
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/DiscoverySteps.java

Removed 3rd party snmpd image
Adding snmpd to our udpgen image instead
Made default image for the tests
- https://opennms.atlassian.net/browse/LOK-1991

Updated udpgen/snmpd image

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/FlowsPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/HomePage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/InventoryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/RefreshMonitor.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/WelcomePage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/DiscoverySteps.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/FlowsSteps.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/HomeSteps.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/MinionSteps.java
test-automation/ui-tests/src/test/resources/features/flows.feature

Adding flow test and minor tweaks/fixes.
- https://opennms.atlassian.net/browse/LOK-2008

Adding flow test and fixing all the minor things that have gotten broken

---

rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/utils/ServerHeaderUtil.java

rest-server: add user attribute to spans

---

charts/lokahi/values.yaml

- https://opennms.atlassian.net/browse/BTO-779

BTO-779: don't use B3 propagation anymore

---

.github/workflows/develop.yml
.github/workflows/release.yml

- https://opennms.atlassian.net/browse/LOK-2021

LOK-2012: Quiet down maven output in CI

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/FlowsPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/FlowsSteps.java

Detect increase in flow data instead of just changes.
Clean up all discoveries at the end of the tests.
- https://opennms.atlassian.net/browse/HS-2008

Better flow detection and clean up discoveries

---

ui/src/services/authService.ts

Removed id_token_hint, trying without that there are some issue with it.
- https://opennms.atlassian.net/browse/LOK-1691

LOK-1691 - …removed id_token_hint

---

minion/minion-grpc/grpc-client/pom.xml
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/Constant.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/GrpcErrorMessages.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/GrpcShutdownHandler.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/channel/SSLChannelFactory.java
minion/minion-grpc/grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/GrpcShutdownHandlerTest.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/MinionGrpcClientTest.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/channel/SSLChannelFactoryTest.java
minion/minion-grpc/grpc-features/src/main/feature/feature.xml

- https://opennms.atlassian.net/browse/LOK-1787

LOK-1787: stop minion if gateway return any certificate errors

---

.github/pull_request_template.md
rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/web/WebExceptionHandler.java
rest-server/src/test/java/org/opennms/horizon/server/GraphQLControllerTest.java

- Update the version of the GraphQL SPQR spring boot starter to latest release (`v1.0.0`).
- Update spring boot version to align with GraphQL SPQR spring boot starter (`v3.1.1`).
- Format BFF pom for consistency.
- Minor changes to address breaking spring boot changes.
- Update pull request template to reference lokahi board name.
- https://opennms.atlassian.net/browse/LOK-1969

LOK-1969: Update GraphQL & Spring Dependencies

---

docs/modules/operation/pages/get-started/discovery/active.adoc
docs/modules/operation/pages/get-started/discovery/manage.adoc

Updates the documentation to describe how to edit and delete discoveries.
- https://opennms.atlassian.net/browse/LOK-1903

LOK-1903: Doc: Discovery: Ability to edit and delete

---

rest-server/src/main/java/org/opennms/horizon/server/service/flows/GrpcFlowService.java
rest-server/src/main/java/org/opennms/horizon/server/service/flows/UnitConverter.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/GrpcFlowServiceTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/UnitConverterTest.java

- https://opennms.atlassian.net/browse/LOK-1880

LOK-1880: convert flow query bytes to bit per second

---

ui/src/components/Map/LeafletMap.vue

Fixes map initial zoom level and max zoom.
- https://opennms.atlassian.net/browse/LOK-1934

LOK-1934: Fix map initial zoom level

---

ui/src/components/Layout/Menubar.vue
ui/src/store/Views/appStore.ts

Adds title to app header based on designs. `Lokahi` for on prem, and `OpenNMS CLOUD` for cloud envs.
- https://opennms.atlassian.net/browse/LOK-1267

LOK-1267: Fix app header

---

charts/lokahi/templates/opennms/api/api-deployment.yaml
charts/lokahi/values.yaml

Pre-work for the minion zip packaging.
- https://opennms.atlassian.net/browse/LOK-2056

Adding env vars to charts for use with the minion zip packaging.

---

alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/PolicyRuleRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/grpc/AlertGrpcService.java
alert/src/main/java/org/opennms/horizon/alertservice/grpc/MonitorPolicyGrpc.java
alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/MonitorPolicySteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcAlertService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/AlertsClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/AlertsClientTest.java
shared-lib/alert/src/main/proto/alerts.proto

- https://opennms.atlassian.net/browse/LOK-2004

LOK-2004: BE: Monitoring Policies: Support deletion of policies and rules within a policy

---

alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/AbstractGrpcUnitTest.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java

- https://opennms.atlassian.net/browse/LOK-2060

LOK-2060: BE: Monitoring Policy: Deletion: Prevent deletion of default policy

---

rest-server/src/main/java/org/opennms/horizon/server/utils/MinionDockerZipPackager.java
rest-server/src/main/resources/.readme
rest-server/src/main/resources/runKarafCommand.bat
rest-server/src/main/resources/runKarafCommand.sh

Add karaf command scripts as part of Minion installation zip file.
- https://opennms.atlassian.net/browse/LOK-2064

LOK-2064: Add karaf command script into zip file

---

ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesSaveButtons.vue

Let's the user edit the default policy tags.
- https://opennms.atlassian.net/browse/LOK-2048

LOK-2048: Let user modify default policy tags

---

minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/GrpcShutdownHandler.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/GrpcShutdownHandlerTest.java
minion/minion-ipc/ipc-heartbeat/src/main/java/org/opennms/horizon/minion/ipc/heartbeat/internal/HeartbeatProducer.java

Add shutdown hook (to display the error message at the end)
Add configurable shutdown delay with `MINION_DELAY_BEFORE_SHUTDOWN` env.
- https://opennms.atlassian.net/browse/LOK-2112

LOK-2112: Add shutdown hook, add delay for shutdown 

---

inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/IcmpActiveDiscoveryGrpcService.java

- https://opennms.atlassian.net/browse/LOK-2118

LOK-2118: Fix discovery validation

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/InventoryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/LeftPanelPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/WelcomePage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/DiscoverySteps.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/steps/LocationSteps.java

Updating welcome and discovery tests with UI changes (welcome, inventory and discovery pages)

Updating welcome test to match all the various UI changes

---

ui/src/components/Inventory/InventoryIconActionList.vue

Correct tool tip text.
- https://opennms.atlassian.net/browse/LOK-1931
N/A

LOK-1931: FE: Alerts mislabelled as Alarms in node details

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java

Fixing discovery tests and making more reliable

Fixing discovery tests and making more reliable

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java

Trying to work around weird UI problems happening in the pipeline by changing the interactions slightly.

Trying some different UI interactions for discovery tests

---

ui/src/components/Welcome/WelcomeSlideOne.vue

In onboarding, update the install/setup link for Docker server. 
N/A
N/A

Onboarding: Update Docker server install link

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/RefreshMonitor.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/WelcomePage.java

When the initial page will not load, try reloading the url instead of refreshing.

BTO-884 - Try re-opening the page instead of refreshing

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/DiscoveryPage.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/LeftPanelPage.java

Turning on headless mode for the UI tests with latest chrome options

BTO-884 - Turning on headless mode with chrome options

---

ui/src/components/Welcome/WelcomeSlideTwo.vue
ui/src/containers/Welcome.vue

Adds a feather tooltop with short description for minion.
Fixes z-index of page so that the tooltip displays correctly.
- https://opennms.atlassian.net/browse/LOK-2156

LOK-2156: Add minion tooltip to welcome page

---

keycloak-ui/README.md

Test
- https://opennms.atlassian.net/browse/BTO-891

BTO-891 - test

---

ui/src/components/Welcome/WelcomeSlideOne.vue
ui/src/components/Welcome/WelcomeSlideTwo.vue

Update some text in the onboarding guide.
- https://opennms.atlassian.net/browse/LOK-2153
N/A

LOK-2153: FE: Update onboarding guide text

---

metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/TaskSetResultProcessor.java

- https://opennms.atlassian.net/browse/LOK-1939

LOK-1939: Don't persist invalid Monitor/Collector response

---

inventory/main/src/main/resources/db/changelog/hs-0.1.0/tables/monitored-service-type.xml

- https://opennms.atlassian.net/browse/LOK-2159

LOK-2159: Add unique constraint for monitor service type

---

.github/workflows/develop.yml
README.md

Putting metadata into file.
- https://opennms.atlassian.net/browse/BTO-886

BTO-886 - test

---

alert/src/main/java/org/opennms/horizon/alertservice/db/entity/SystemPolicyTag.java
alert/src/main/java/org/opennms/horizon/alertservice/db/entity/Tag.java
alert/src/main/java/org/opennms/horizon/alertservice/db/repository/SystemPolicyTagRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/main/resources/db/changelog/changelog.xml
alert/src/main/resources/db/changelog/hs-0.1.0/tables/update_system_policy_tag_nullable_tag_id.xml
alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java

- https://opennms.atlassian.net/browse/LOK-2111

LOK-2111: Make sure default policy have default tag when custom tag is empty

---

docs/modules/development/pages/introduction.adoc
docs/modules/installation/pages/requirements.adoc
docs/modules/operation/pages/get-started/policies/introduction.adoc

Updated the content regarding the kinds of alerts the `default-policy` creates.

LOK-1985: DOC: Update default monitoring policy documentation

---

alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/test/java/org/opennms/horizon/alertservice/grpc/MonitoringPolicyGrpcTest.java

- https://opennms.atlassian.net/browse/LOK-2172

LOK-2172: handle default policy update id validation

---

ui/auto-feather-resolver.ts
ui/components.d.ts
ui/src/components/Layout/NavigationRail.vue
ui/src/components/Layout/NavigationRailNavItem.vue

Adds a link to the documentation
- https://opennms.atlassian.net/browse/LOK-1909

LOK-1909: Add documentation link to nav rail

---

.github/workflows/create-release.yml
build-tools/release/release.sh

- https://opennms.atlassian.net/browse/LOK-2181

Automate creating a Lokahi release

---

ui/src/containers/Discovery.vue

We don't yet support Syslog, so need to remove it.
N/A
N/A

Remove mention of Syslog in Passive Discovery Heading

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/Constants.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/test/java/org/opennms/horizon/server/metrics/QueryServiceTest.java

- https://opennms.atlassian.net/browse/LOK-2148

LOK-2148: Add availability percentage query

---

tilt-helm-values.yaml

Allow Introspection by Default in Tilt

Allow Introspection by Default in Tilt

---

inventory/main/src/main/java/org/opennms/horizon/inventory/mapper/NodeMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/TopNNode.java
rest-server/src/main/java/org/opennms/horizon/server/model/status/NodeReachability.java
rest-server/src/main/java/org/opennms/horizon/server/model/status/NodeResponseTime.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcLocationService.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/Constants.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/test/java/org/opennms/horizon/server/metrics/QueryServiceTest.java
shared-lib/inventory/src/main/proto/nodeService.proto

- https://opennms.atlassian.net/browse/LOK-2149

LOK-2149: Add TopN Nodes GrapQL API

---

alert/src/main/java/org/opennms/horizon/alertservice/db/repository/AlertRepository.java
alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
alert/src/main/java/org/opennms/horizon/alertservice/service/ReductionKeyService.java
alert/src/main/resources/db/changelog/changelog.xml
alert/src/main/resources/db/changelog/hs-0.1.0/data/system_tenant_default_policy_restore.xml
alert/src/test/java/org/opennms/horizon/alertservice/service/AlertEventProcessorTest.java
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature
alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature
ui/src/store/Views/alertsStore.ts

Extra:
add restore rule
add list alert order by date desc
- https://opennms.atlassian.net/browse/LOK-2110

LOK-2110: add clear alert reset threshold status

---

ui/src/components/Common/AddressAutocomplete.vue

Update the term used for address (from `address` to `physical address`).
- https://opennms.atlassian.net/browse/LOK-1933
N/A

LOK-1933: Update term used for geo/physical address

---

ui/src/store/Views/dashboardStore.ts

Fixes a type and typo for reachability
- https://opennms.atlassian.net/browse/LOK-2091

LOK-2091: Fix reachability type

---

rest-server/src/main/java/org/opennms/horizon/server/mapper/SnmpInterfaceMapper.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/Constants.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/test/java/org/opennms/horizon/server/metrics/QueryServiceTest.java
rest-server/src/test/resources/test/data/query-network-traffic.json
ui/src/components/Dashboard/DashboardNetworkTraffic.vue
ui/src/components/Dashboard/dashboardNetworkTraffic.config.ts
ui/src/components/Graphs/LineGraph.vue
ui/src/store/Queries/dashboardQueries.ts

- https://opennms.atlassian.net/browse/LOK-1965

LOK-1965: convert  main page total network traffic from bytes to bits

---

rest-server/src/main/java/org/opennms/horizon/server/web/WebExceptionHandler.java
rest-server/src/test/java/org/opennms/horizon/server/GraphQLAuthTest.java

I noticed that there was a possibility of internal error details leaking out if an unexpected exception occurs in a filter, like when initializing the JWT processor used in Spring Security. I change the exception handler implement to the less ergonomic, but more holistic `WebExceptionHandler` interface to account for this.
- https://opennms.atlassian.net/browse/LOK-1899

LOK-1899: Use WebExceptionHandler instead of controller advice

---

docs/modules/operation/pages/flows/introduction.adoc
docs/modules/operation/pages/minions/introduction.adoc
docs/modules/operation/pages/visualizations/introduction.adoc

Added documentation for the Maps page, and updated the Locations/Minions documentation based on recent updates to the software. Note that the docs are based on QA, for our cohort testing. Therefore the "unlock file password" field on the Minions screen is still present. 
- https://opennms.atlassian.net/browse/LOK-2195

LOK-2195: Doc: Geo Map: User Documentation

---

rest-server/src/main/java/org/opennms/horizon/server/model/status/NodeReachability.java
rest-server/src/main/java/org/opennms/horizon/server/model/status/NodeResponseTime.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java

This seems to fix unstability issues in BFF
- https://opennms.atlassian.net/browse/LOK-2206

LOK-2206: Move to reactive way of returning result

---

docs/modules/operation/pages/flows/introduction.adoc

DP-91: Create Pendo guide for flows page - updated to add node reachability and  top nodes to the docs.
see above
- https://opennms.atlassian.net/browse/DP-91

DP-91: Create Pendo guide for flows page

---

charts/lokahi/templates/grafana/grafana-deployment.yaml
charts/lokahi/templates/keycloak/keycloak-deployment.yaml
charts/lokahi/templates/opennms/alert/alert-deployment.yaml
charts/lokahi/templates/opennms/datachoices/datachoices-deployment.yaml
charts/lokahi/templates/opennms/events/events-deployment.yaml
charts/lokahi/templates/opennms/inventory/inventory-deployment.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
charts/lokahi/values.yaml
install-local/install-local-opennms-lokahi-custom-images-values.yaml
install-local/install-local-opennms-lokahi-values.yaml
tilt-helm-values.yaml

Change the default values so that citus is not enabled by default, and modify the tilt and install local helm values to enable it.
- https://opennms.atlassian.net/browse/LOK-2169

Make citus off by default and force on for tilt and install-local.

---

docs/antora.yml
docs/modules/ROOT/pages/index.adoc

DP-83: Add doc information to each product landing page - added version and last updated info to the landing page for Lokahi docs, for consistency with other OpenNMS docs.
See above
- https://opennms.atlassian.net/browse/DP-83

DP-83: Add doc information to each product landing page

---

ui/src/containers/Flows.vue

- https://opennms.atlassian.net/browse/LOK-1952
-

LOK-1952: hide flow total

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
rest-server/src/main/java/org/opennms/horizon/server/service/metrics/Constants.java
ui/src/containers/Graphs.vue

Azure noe (bits)
Azure portal screen (bytes)
snmp node in bits
Total (bits)
- https://opennms.atlassian.net/browse/LOK-1964

LOK-1964: fix azure metrics and total missing azure 

---

inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcServiceTest.java

Fix bug where an error is thrown when listing minions for a location that doesn't have any. The response is now an empty list instead of an error.
- https://opennms.atlassian.net/browse/LOK-2224
N/A

LOK-2224: BE: Location with no Minion should return empty array instead of error

---

ui/src/components/Locations/LocationsCard.vue
ui/src/components/Locations/LocationsEditForm.vue
ui/src/components/Locations/LocationsList.vue
ui/src/components/Locations/LocationsMinionsCard.vue
ui/src/store/Queries/locationQueries.ts
ui/src/store/Queries/minionsQueries.ts

Refactors the call for getting minions by location so that it does not make extra calls with id 0.
Also removes unused code that we have no current plans of using.
- https://opennms.atlassian.net/browse/LOK-2222

LOK-2222: Fix minions by location id calls

---

.github/workflows/develop.yml
README.md

- Revert "BTO-886 - test (#1532)"
- Use OpenNMS-DevOps account email/name for push to fabric-services
- https://opennms.atlassian.net/browse/BTO-897

BTO-897: Use OpenNMS-DevOps account email/name for push to fabric-services

---

ui/src/services/gqlService.ts

This is a work-in-progress and is hacky and definitely needs cleaned up.
Add trace ID (if available) to errors shown in the UI.
Our web server adds a `Server-Timing` header on all responses (including errors) with the traceparent header. This pulls out the trace ID portion of that and adds it to errors shown in the UI as a snackbar (the red popup at the bottom center of the screen).
Here's what the header looks lke, BTW:
```
$ curl --dump-header /dev/stdout -sSf https://auth.onms-fb-dev.dev.nonprod.dataservice.opennms.com/ | grep -i Server-timing
curl: (22) The requested URL returned error: 404
server-timing: traceparent;desc="00-ee7c5ef3834410c3f7a74ebf2146f18c-830c100f808d18f6-01"
```
There a few issues I ran into while doing this (I'm not sure if any of these need to be addressed as …

LOK-2254: WIP: Add trace ID to graphQL errors shown in the UI

---

Tiltfile

- Tilt: Standardize on workload names so they match filesystem
- Tilt: Move citus into z_dependencies group
- Tilt: Relate uncategorized k8s objects with their workloads

Tilt: various cleanups

---

minion/assembly/src/main/resources/etc/custom.system.properties
minion/plugins/icmp-plugin/src/main/feature/feature.xml
minion/plugins/icmp-plugin/src/main/resources/OSGI-INF/blueprint/icmp-plugins.xml
shared-lib/icmp-api/src/main/java/org/opennms/horizon/shared/icmp/PingerFactoryImpl.java

Use BestMatchPingerFactory and icmp-best in features.
Also set jcimp libary locations in properties file.
- https://opennms.atlassian.net/browse/LOK-2150

LOK-2150:  Prefer Jni/Jni6Pinger  when available

---

minion/assembly/src/main/resources/etc/org.apache.cxf.osgi.cfg

Delete cxf config, misconfiguration is causing exception while loading
- https://opennms.atlassian.net/browse/LOK-2167

LOK-2267: Remove cxf file, no rest endpoints are exposed yet

---

ui/src/store/Queries/minionsQueries.ts

- https://opennms.atlassian.net/browse/LOK-2255

Resolve Minions page shows wrong number of Minions

---

rest-server/src/main/java/org/opennms/horizon/server/model/inventory/TopNNode.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java

Add nodeAlias property to topNNode model and set it NodeStatusService. (2239)
https://opennms.atlassian.net/browse/LOK-2239
Please review.

LOK-2239: Add nodeAlias property to topNNode model 

---

ui/src/components/Locations/LocationsAddForm.vue

On Locations, we shouldn’t allow blank names in UI, save button shouldn’t appear if we have a blank.
Names should be trimmed before sending to BE.
- https://opennms.atlassian.net/browse/LOK-2302

LOK-2302: Don't allow blank location name

---

Tiltfile

- https://opennms.atlassian.net/browse/LOK-2325

LOK-2325: Move shared-lib to manual on tilt

---

ui/src/components/NodeStatus/IPInterfacesTable.vue

Implement sorting on the IP Interfaces table on Interfaces tab of the Node Status page.
This is the components/NodeStatus/IPInterfacesTable.vue component.
- https://opennms.atlassian.net/browse/LOK-2327

Node Details: IP Interfaces component - table sorting

---

ui/src/components/NodeStatus/EventsTable.vue

Implement Events table on Events tab of the Node Status page.
This is the components/NodeStatus/EventsTable.vue component.
get actual data
use FeatherSortHeader, see DashboardTopNodesTable.vue for example
add pagination
Don’t add sorting, that will be a separate task. CSV export and search will also be separate tasks.
https://opennms.atlassian.net/browse/LOK-2298

LOK-2298:Node Details: Events table

---

ui/src/components/NodeStatus/EventsTable.vue

Implement sorting on the Events table on the Events tab of the Node Status page.
This is the components/NodeStatus/EventsTable.vue component.
This should be done after ​LOK-2298.
https://opennms.atlassian.net/browse/LOK-2346

LOK-2346:Events Table Sorting

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/InventoryProcessingStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/inventory-processing.feature

Reference test case for other usecases
- https://opennms.atlassian.net/browse/LOK-2350

LOK-2350: Add test case to validate snmp interfaces/ ip interfaces

---

ui/src/components/Inventory/InventoryTagModal.vue
ui/src/components/NodeStatus/NodeTags.vue
ui/src/containers/NodeStatus.vue
ui/src/store/Components/tagStore.ts

On Node Status page, create a modal dialog that pops up when user clicks either Manage in the NodeTags control, or Manage Tags button that’s on the same line as the title.
See Inventory/InventoryTagModal.vue , use this, adjust it if needed so it works in both Inventory and NodeStatus pages
have it popup on clicking Manage or Manage Tags 
Populate with node label and tags (tags for this node)
X or Cancel should close dialog
Confirm that the Add tags section works
https://opennms.atlassian.net/jira/software/c/projects/LOK/boards/138?selectedIssue=LOK-2284

LOK-2284: Manage Tags dialog

---

ui/src/components/NodeStatus/SNMPInterfacesTable.vue
ui/src/store/Components/tagStore.ts

Implement sorting on the SNMP Interfaces table on Interfaces tab of the Node Status page.
This is the components/NodeStatus/SNMPInterfacesTable.vue component.
- https://opennms.atlassian.net/browse/LOK-2353

Node Details: SNMP Interfaces component - table sorting

---

rest-server/src/main/java/org/opennms/horizon/server/model/inventory/IpInterfaceResponse.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java

Download IpInterfaces for a given node to CSV. This can be done completely in BFF ( rest-server).
https://opennms.atlassian.net/browse/LOK-2234

 LOK-2234 : BE: BFF: Node: DownloadIpInterfacesToCsv

---

ui/src/components/NodeStatus/NodeAlerts.vue
ui/src/store/Views/nodeStatusStore.ts

Add pagination using graphQL to Node Status Recent Alerts.
Also implement the Refresh button for Alerts (just calls fetch again).
https://opennms.atlassian.net/browse/LOK-2373

LOK-2373: Alerts Pagination and Refresh

---

ui/src/components/MonitoringPoliciesLegacy/MonitoringPoliciesCardLegacy.vue
ui/tests/NodeStatus/nodeStatus.test.ts

`vue-router` 4 is `async`, need to account for this when using a router in unit tests.
- https://opennms.atlassian.net/browse/LOK-2347

LOK-2347: Fix nodeStatus test, vue-router async issue

---

ui/tests/store/Views/alertsStore.test.ts

Create tests/store/Views/alertsStore.test.ts, include tests for:
isAlertsListEmpty
isAlertSelected
setAllAlertsSelected
setAlertSelected
clearSelectedAlerts
acknowledgeSelectedAlerts
-https://opennms.atlassian.net/browse/LOK-2391

FE: Unit tests: alertsStore part 1

---

ui/tests/store/Views/locationStore.test.ts

Add tests/store/Views/locationStore.test.ts and add tests for:
fetchLocations
searchLocations
selectLocation
addLocation
- https://opennms.atlassian.net/browse/LOK-2396

Unit tests: locationStore part 1

---

ui/tests/store/Views/locationStore.test.ts

Add tests to tests/store/Views/locationStore.test.ts:
setDisplayType
createLocation
updateLocation
deleteLocation
selectedLocation
- https://opennms.atlassian.net/browse/LOK-2397

Unit tests: locationStore part 2

---

keycloak-ui/themes/lokahi/login/template.ftl
ui/src/components/Welcome/WelcomeSlideOne.vue

Ensure application titles read either "OpenNMS Cloud" or "Lokahi" as appropriate, and remove "Horizon Stream" from titles.
Also reformats and fixes a couple typos in one of the welcome screen files.
- https://opennms.atlassian.net/browse/LOK-2250

LOK-2250: Fix app titles to read OpenNMS Cloud or Lokahi

---

ui/tests/store/Views/dashboardStore.test.ts
ui/tests/store/Views/nodeStatusStore.test.ts

Add tests/store/Views/dashboardStore.test.ts and add tests for all methods.
https://opennms.atlassian.net/browse/LOK-2415

FE: Unit tests: dashboardStore
