OpenNMS-Cloud/lokahi

platform/alarms/rest/pom.xml
platform/alarms/rest/src/main/java/org/opennms/netmgt/alarmd/rest/internal/AlarmRestServiceImpl.java
platform/alarms/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/assemblies/features/src/main/feature/features.xml
platform/bom/pom.xml
platform/core/rest/pom.xml
platform/docker-it/src/test/resources/org/opennms/horizon/openapi-spec.feature
platform/events/api/src/main/java/org/opennms/horizon/events/xml/AlarmData.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/Correlation.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/Event.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/EventReceipt.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/Mask.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/Maskelement.java
platform/events/api/src/main/java/org/opennms/horizon/events/xml/Parms.java
platform/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
platform/events/rest/src/main/java/org/opennms/netmgt/events/rest/internal/EventRestServiceImpl.java
platform/pom.xml

- Set start-level for CORE REST below other REST to ensure whiteboard extensions take effect.
- Update CXF to 3.5.0 to resolve javax.api vs jakarta.servlet-api issue.
- Remove helper setters causing Jackson to fail marshalling with "Conflicting setter definitions" error.

Add OpenAPI spec generation and HTTP endpoints "/openapi.json" and "/openapi.yaml"

---

platform/provision/snmp/src/main/resources/OSGI-INF/blueprint/blueprint.xml

The SNMP detector bundle was not starting due to some bad blueprint wiring. This corrects it.

Fixing bad blueprint wiring

---

dev/kubernetes.kafka.yaml

Update minion location to `Default`
- https://issues.opennms.org/browse/HS-188

HS-188: Minion location should be Default

---

dev/kubernetes.kafka.yaml
skaffold.yaml

Added the Prometheus and Prometheus push gateway in skaffold environment. Push simple metrics data with the following command
`echo "some_metric ${RANDOM:0:2}" | curl --data-binary @- http://localhost:59091/metrics/job/some_job`
Verify the metics pushed to the gateway in the browser at http://localhost:59091/ 
Query the metrics in  the browser at http://localhost:59090/ with `some_metric`
- https://issues.opennms.org/browse/HS-248

HS-248: TSDB in dev environment

---

dev/kubernetes.kafka.yaml
skaffold.yaml

Start skaffold and wait until all pods running. login http://localhost:53000/ as admin/admin and verify datasources hs-metrics is created. Using the following shell script can simulate some sample data. 
```#!/bin/bash
for i in {1..1000}
do
echo "some_metric ${RANDOM:0:2}" | curl --data-binary @- http://localhost:59091/metrics/job/some_job
sleep 120
done
```
Wait for few minutes then can query from the hs-metrics datasource and create an sample dashboard
- https://issues.opennms.org/browse/HS-198

HS-198 Add Grafana into Dev environment

---

ui/tests/Appliances/addDeviceCtrl.test.ts
ui/tests/Appliances/appliances.test.ts
ui/tests/Appliances/notificationsCtrl.test.ts

Need to stub the teleport now, to test anything in a modal
Fixes some warnings for the appliances container
- https://issues.opennms.org/browse/HS-267

HS-267: Fix tests from feather update v 0.17

---

minion-gateway/src/main/java/org/opennms/miniongateway/grpc/server/GrpcServerConfig.java
minion-gateway/src/main/java/org/opennms/miniongateway/grpc/server/stub/StubCloudToMinionMessageProcessor.java
shared-lib/ipc/grpc/client/src/main/java/org/opennms/poc/ignite/grpc/client/internal/StubGrpcClient.java
shared-lib/ipc/grpc/contract/src/main/proto/opennms/rpc/echo/echo.proto
shared-lib/ipc/grpc/contract/src/main/proto/opennms/sink/heatbeat/heartbeat.proto
shared-lib/ipc/grpc/contract/src/main/proto/opennms_minion_ipc.proto
shared-lib/ipc/grpc/server/src/main/java/org/opennms/core/ipc/grpc/server/OpennmsGrpcServer.java
shared-lib/ipc/grpc/server/src/main/java/org/opennms/core/ipc/grpc/server/manager/adapter/CloudServiceDelegate.java
shared-lib/ipc/grpc/server/src/main/java/org/opennms/core/ipc/grpc/server/manager/adapter/DelegateAdapter.java
shared-lib/ipc/grpc/server/src/main/java/org/opennms/core/ipc/grpc/server/manager/adapter/MinionRSTransportAdapter.java

A basic update bringing proto structures for further work. Rename of `MinionHeader` into `Identity` as it can be later used in rpc envelopes.

Rename MinionHeader to Identity, introduce new structs.

---

platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/DeviceMonitorManager.java
platform/ipc/echo/src/main/java/org/opennms/horizon/echo/monitor/SimpleMinionRpcMonitor.java
platform/metrics/api/src/main/java/org/opennms/horizon/metrics/api/OnmsMetricsAdapter.java
platform/metrics/impl/src/main/java/org/opennms/horizon/metrics/impl/PrometheusPushGatewayAdapter.java
platform/minion/heartbeat/src/main/java/org/opennms/minion/heartbeat/HeartbeatConsumer.java
platform/minion/heartbeat/src/test/java/org/opennms/minion/heartbeat/HeartbeatConsumerTest.java
rest-server/src/main/java/org/opennms/horizon/server/service/PrometheusTSDBServiceImpl.java

Register metrics once and push registry to push gateway
Fix graphql query to make a query without labels
- https://issues.opennms.org/browse/HS-303

HS-303: Add groupingKeys for push gateway

---

ui/codegen.yml
ui/src/components/Appliances/AddDeviceCtrl.vue
ui/src/types/graphql.ts

Changed the generated types to use `undefined` for potential missing values, instead of null.
This is done because feather input models work with undefined.
- https://issues.opennms.org/browse/HS-279

HS-279: Use undefined val for generated MaybeInput type

---

ui/components.d.ts
ui/src/components/Appliances/AddDeviceCtrl.vue
ui/src/graphql/Views/applianceQueries.graphql
ui/src/store/Queries/applianceQueries.ts
ui/src/types/graphql.ts

Replaces location input with dropdown. Makes call for locations and populates dropdown with first location by default
- https://issues.opennms.org/browse/HS-309

HS-309: Replace locations input with select dropdown

---

keycloak-ui/Dockerfile
skaffold.yaml

Updates this part of the build cmd: `Ddocker.image=$IMAGE -Ddocker.skipPush=!$PUSH_IMAGE`
Changes keycloak-ui version to 18.0.0
- https://issues.opennms.org/browse/HS-312
Probably should be tested on mac, to be safe

HS-312: Update skaffold vars

---

ui/src/components/Layout/Menubar.vue
ui/src/components/Map/LeafletMap.vue
ui/src/composables/useTheme.ts
ui/tests/Appliances/appliances.test.ts
ui/tests/Layout/menubar.test.ts

Moves the useDark functionality into a useTheme composable. 
Adds separate leaflet tile layer for dark mode.
- https://issues.opennms.org/browse/HS-305

HS-305: Add leaflet dark mode tiles, useTheme hook

---

minion/assembly/src/main/resources/etc/org.ops4j.pax.logging.cfg
minion/minion-ipc/twin-core/pom.xml
minion/minion-ipc/twin-core/src/main/java/org/opennms/horizon/minion/ipc/twin/core/internal/GrpcTwinSubscriber.java
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-client/src/main/java/org/opennms/core/ipc/grpc/client/MinionGrpcClient.java
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-client/src/main/java/org/opennms/core/ipc/grpc/client/ReconnectStrategy.java
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-client/src/main/java/org/opennms/core/ipc/grpc/client/SimpleReconnectStrategy.java
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml

When GRPC channel leaves off the READY state, the stream observers become invalid.
While they do not throw any exception, it is not possible to receive nor publish any update using them.
GRPC api for java does not provide a way to track transition between managed channel states, it allows only to notify about state change.
Yet state change change is not being made unless there is an rpc operation requested.
Its kind of chicken-egg problem as GRPC client code we do, do not attempt to perform operations (where it is aware of channel state) unless channel is ready.
In order to gain a control over channel we need to force a state check. By this we can catch disconnect and connect time.
This commit introduces 30s window to monitor connection state.
In event of communication failure a …

Handling of application level reconnection.

---

minion/minion-features/src/main/resources/features.xml
minion/plugins/snmp-plugin/src/main/feature/feature.xml
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/UtilInitializer.java
minion/plugins/snmp-plugin/src/main/resources/OSGI-INF/blueprint/snmp-plugins.xml
minion/snmp/snmp4j/pom.xml
shared-lib/snmp-api/src/main/java/org/opennms/horizon/shared/snmp/SnmpUtils.java
shared-lib/snmp-api/src/main/resources/OSGI-INF/blueprint/blueprint.xml
tooling/ignite-tool/tools/example-task-set.003.json

Abstraction assumed in snmp api require specific class names, also snmp-api itself require a specific strategy to be present.
Given that we run under OSGi the `Class.forName` calls not working properly especially from api module which defines strategy interface.
This commit also bring minor adjustments in minion snmp4j module to let it work under OSGi.

Working snmp monitor and adjustments to snmp strategy lookup.

---

charts/opennms/templates/opennms/api/api-deployment.yaml

Migration to webflux changed this variable name, this fixes it.
- https://issues.opennms.org/browse/HS-378

[HS-378] Fix environment variable name after migration to spring-webflux

---

platform/assemblies/core-dynamic-dist/pom.xml
platform/assemblies/features/pom.xml
platform/assemblies/features/src/main/feature/features.xml
platform/datachoices/pom.xml
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/dto/UsageStatisticsReportDTO.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/internal/StateManager.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/internal/UsageStatisticsReporter.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/web/DataChoicesRestService.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/web/internal/DataChoiceRestServiceImpl.java
platform/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/DataChoicesDao.java
platform/db/dao-impl/src/main/java/org/opennms/horizon/db/dao/impl/DataChoicesDaoHibernate.java
platform/db/dao-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/db/model/src/main/java/org/opennms/horizon/db/model/OnmsDataChoices.java
platform/db/schema-liquibase/src/main/liquibase/hs-0.1.0/changelog.xml
platform/docker-it/src/test/resources-filtered/karaf/etc/org.apache.karaf.features.cfg
platform/pom.xml

Adding initial datachoices module which will (eventually) send a payload to stats.opennms.com to a new seperate Elastic search cluster and grafana dashboard.
This has been tested with a locally deployed version of https://github.com/OpenNMS/usage-stats-handler/pull/4 which will eventually get deployed to the stats.opennms.com.
This uses the database to store the generated system ID used to identify the installation, and uses the maven project version as the version to be sent to stats.opennms.com. 
The version will need to be updated during the build and deploy pipeline using maven CLI.
Added endpoint to toggle the datachoices (Opt-In/Opt-Out) timer to run. If the datachoices has been enabled, then it will also be enabled after an application restart. The enabled flag is also stored in …

HS-337,HS-338: Stats: Create platform module for data choices

---

ui/src/composables/useWidgets.ts

Reverted back to `defineAsyncComponent` but with fixed casing
This should do it - tested locally with skaffold
- https://issues.opennms.org/browse/HS-395

HS-395: Fix async imports - final

---

notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPIImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyDaoImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/api/dto/PagerDutyConfigDTO.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationServiceImpl.java
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/pagerDutyConfig.xml
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyAPIImplTest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyDaoImplTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestControllerTest.java
notifications/src/test/java/org/opennms/horizon/notifications/rest/NotificationRestIntegrationTest.java

Following Dev Jam, we added the alarm details to the PagerDuty custom details in the plugin classic uses. Also, I realised that the token I was using isn't needed. Have also removed the validation of that token also. So duplicating that work in streams.
- https://issues.opennms.org/browse/HS-394
none

HS-394: add alarm to PagerDuty custom details

---

charts/opennms/templates/grafana/grafana-deployment.yaml
charts/opennms/templates/grafana/grafana-secret.yaml
charts/opennms/templates/opennms/core/core-deployment.yaml
charts/opennms/templates/opennms/notification/notification-deployment.yaml
charts/opennms/templates/postgres/postgres-cred-secret.yaml
charts/opennms/templates/postgres/postgres-deployment.yaml
charts/opennms/templates/postgres/postgres-init-secret.yaml
operator/internal/handlers/grafana.go
operator/internal/handlers/postgres.go
operator/internal/reconciler/values_updater.go
platform/alarms/itests/src/test/java/org/opennms/horizon/alarms/itests/CoreContainer.java
platform/db/schema/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/docker-it/pom.xml

…atabase passwords into Secrets
- Enables authentication against Postgres
- Converts ConfigMaps to Secrets where they contain passwords
- Allows Operator to use special characters when generating Postgres passwords
- https://issues.opennms.org/browse/HS-409
- https://issues.opennms.org/browse/HS-410
- https://issues.opennms.org/browse/HS-411

[HS-409,HS-410,HS-411] Postgres authentication and converting sensitive ConfigMaps to Secrets

---

platform/datachoices/pom.xml
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/dto/UsageStatisticsReportDTO.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/internal/DataChoicesTimerTask.java
platform/datachoices/src/main/java/org/opennms/horizon/datachoices/internal/UsageStatisticsReporter.java
platform/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
platform/datachoices/src/test/java/org/opennms/horizon/datachoices/dto/UsageStatisticsReportDTOTest.java
platform/datachoices/src/test/java/org/opennms/horizon/datachoices/internal/DataChoicesTimerTaskTest.java
platform/datachoices/src/test/java/org/opennms/horizon/datachoices/internal/StateManagerTest.java
platform/datachoices/src/test/java/org/opennms/horizon/datachoices/internal/UsageStatisticsReporterTest.java
platform/datachoices/src/test/java/org/opennms/horizon/datachoices/web/internal/DataChoiceRestServiceImplTest.java
platform/db/dao-api/src/main/java/org/opennms/horizon/db/dao/api/MonitoredServiceDao.java
skaffold.yaml

Implementing the metrics collection for Phase 1. 
Also adding more tests of this datachoices module.
This has been tested with https://github.com/OpenNMS/usage-stats-handler/pull/4 to show the following dashboard: 
(Has been ran multiple times in testing, hence why multiple installs)
This is to be deployed to stats.opennms.com at some point in the future.
* Monitored Services shows 0 because currently we do not write to the `ifServices` yet.
* Currently the deviceType is of the node label until we have a way to get a device type (i.e. Router, Server, Storage)
Still TODO:
* BFF endpoint for frontend
* Frontend button to Opt-In/Out
- https://issues.opennms.org/browse/HS-339

HS-339: Stats: Implement Phase 1 Metrics collection

---

dev/kubernetes.kafka.yaml

- Missing env var in the core deployment broke initial startup
- none

Add missing env var to Core deployment in k8s manifest

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/tasks/EchoRoutingTask.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/router/MinionLookupService.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/router/MinionLookupServiceImpl.java
minion-gateway/main/src/test/java/org/opennms/miniongateway/router/MinionLookupServiceImplTest.java
shared-lib/horizon-ipc/ipc-grpc/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java

I brought back load balancing for requests directed at location. It is based on random rand robin, hoping that overall distribution will be fine over time.
Stacktrace we end with is not nicest one, but it does not have ignite core failure signs:
```
java.util.concurrent.CompletionException: org.apache.ignite.internal.client.thin.ClientServerError: Ignite failed to process request [7]: Failed to reduce job results due to undeclared user exception [task=org.opennms.miniongateway.grpc.server.tasks.EchoRoutingTask@6d7e9f85, err=class org.apache.ignite.IgniteException: Could not execute RPC request] (server status code [1])
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Complet …
```

Adjustment of routing code, include missing location/system message

---

charts/opennms/templates/opennms/api/api-deployment.yaml

start skaffold dev environment. Make sure the GraphQL playground is available at http://localhost:8123/api/gui without any error and the schema can be retrieved.
- https://issues.opennms.org/browse/HS-452

HS-452: fixed the graphql playground target endpoint

---

skaffold.yaml

- The new minion's tests will run even when skipping tests in Skaffold, this fixes it
- https://issues.opennms.org/browse/HS-454

Add usage of Skaffold's --skip-tests flag to Minion build

---

parent-pom/pom.xml

Updating protobuf version from 3.16.1 to 3.17.3 in line with https://github.com/OpenNMS/horizon-stream/pull/361
Also this fixes the problem that occurs on M1 Mac machines
- https://issues.opennms.org/browse/HS-456
n/a

HS-456: Updated protobuf version for arm chip

---

minion/assembly/src/main/resources/etc/org.opennms.core.ignite.client.cfg
skaffold.yaml

- This property was renamed in the blueprint file but not the cfg, and the env var stopped working
- Skaffold port forwards were pointing at the wrong name

Fix minion KUBERNETES_SERVICE_NAME env var and port forwards

---

operator/skaffold.yaml
skaffold.yaml

- This status check was causing skaffold to exit in the event of a deployment failure, which cleaned up the cluster, and made troubleshooting impossible
- As a bonus, dev loop and pod log streaming will start immediately
- Downside, will throw errors during initial port forwards
- https://issues.opennms.org/browse/HS-497
- Need someone to test this out before I merge and make sure it won't cause any issues
- Port forwarding in particular could be a problem with this change. Skaffold should eventually forward those ports, but it has always been flaky.

[HS-497] Disable deployment status checking in Skaffold by default

---

charts/opennms/values.yaml
ui/Dockerfile
ui/nginx/conf.d/default.conf
ui/nginx/nginx.conf

run the UI container on port 8080 instead of 80 to allow it to run without special privileges

bind on port 8080 (instead of 80) to allow container to run unprivileged

---

grafana/Dockerfile
platform/assemblies/docker/src/main/docker/core/Dockerfile

remove a few unneeded setcap calls
this allows us to get closer to running the chart on OpenShift:
```
% kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
grafana-545fd46ffd-ggpbd                     1/1     Running            0          5m6s
mail-server-79f5bc7648-47r76                 1/1     Running            2          12h
onms-kafka-7988b454-vf2tg                    1/1     Running            2          12h
onms-keycloak-6fb84844cf-w77bs               1/1     Running            2          12h
opennms-core-66f9cf5cb4-tbxf9                1/1     Running            2          12h
opennms-inventory-84675fd5c5-559k7           0/1     ImagePullBackOff   0          12h
opennms-metrics-processor-84d5556c48-gcc52   0/1 …
```

remove setcap calls from binaries to allow them to run without special privs

---

inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitoring-location.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/monitoring-system.xml

Update table names to be singular.  
Updated names directly without migrating ( hopefully that should be fine for now)
- https://issues.opennms.org/browse/HS-515

HS-515: Update table names to be singular

---

rest-server/src/main/java/org/opennms/horizon/server/model/TSResult.java
rest-server/src/main/java/org/opennms/horizon/server/model/TimeRangeUnit.java
rest-server/src/main/java/org/opennms/horizon/server/service/PrometheusTSDBServiceImpl.java
rest-server/src/main/resources/application.yml

After the system is ready, try querying metrics from the BFF GraphQL playground at http://localhost:8123/api/gui
The query string looks like the following
```query {
metric(name: "response_time_msec", labels:{monitor: "SNMP"}, timeRange: 10, timeRangeUnit: MINUTE) {
status
data{resultType 
result{metric value values}}
}
}
```
- https://issues.opennms.org/browse/HS-451

HS-451: Add time range to metrics query

---

Tiltfile

- Tilt inspector was used to debug Tilt itself while working on it, but is not necessary at this point. Would fail to start on certain machines.
- https://issues.opennms.org/browse/HS-544

[HS-544] Remove tilt inspector

---

ui/Dockerfile

Currently there are predefined build arguments which can be passed to override defaults assumed by UI build. Sadly they do not work, as they are defined in wrong stage. This means that UI container can not be built with different target than development environment. By moving `ARG` section to build stage where actual JS output is being produced image can be parametrized at build time without necessity to explicitly declare `ENV` vars (which are meaningless for generated JS code).
- https://issues.opennms.org/browse/HS-609

HS-609 Make sure docker args are promoted at build stage

---

inventory/pom.xml
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringLocationService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TrapConfigService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/trapconfig/SnmpV3User.java
inventory/src/main/java/org/opennms/horizon/inventory/service/trapconfig/TrapConfigBean.java
inventory/src/main/resources/trapd-config.json
inventory/src/test/java/org/opennms/horizon/inventory/grpc/LocationGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcStartupIntTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/src/test/resources/db/changelog/changelog-test.xml
inventory/src/test/resources/db/changelog/trap-config-data.xml

Send trap config to minion
- https://issues.opennms.org/browse/HS-605
On line 36 of TrapConfigBean, using the proto generated version of SnmpV3User gives an error when running NodeGrpcStartupIntTest:
Cannot find a (Map) Key deserializer for type [simple type, class com.google.protobuf.Descriptors$FieldDescriptor]
The solutions offered by google failed to fix the problem, so I have created a separate version based of org.opennms.horizon.shared.snmp.SnmpV3User. I can't use that version as several of the proto fields have changed name slightly.

HS-605: Send trap config to minion

---

minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/impl/RpcRequestTimeoutManagerImpl.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/GrpcServerConfig.java
platform/core/monitor/src/main/java/org/opennms/horizon/core/monitor/MinionRpcMonitorManager.java

Fix echo request timeout, Previously the timeout was always 0, the timeout logic (almost) always triggers on minion-gateway, and a single-thread executor shared with a "while (true)" loop prevents completion of the timeout response handling.

Fix echo request timeout

---

ui/components.d.ts
ui/src/components/Events/EventsTable.vue
ui/src/graphql/Views/nodeStatusQueries.graphql
ui/src/store/Queries/nodeStatusQueries.ts
ui/src/types/graphql.ts
ui/tests/fixture/events.ts
ui/tests/store/Queries/nodeStatusQueries.test.ts

Previously calling for all events and then filtering by nodeId on the frontend.
Changed to use the new findEventsByNodeId endpoint.
The designs for this page are yet to be completed, so for now we show just the basic event properties in the table.
- https://issues.opennms.org/browse/HS-651

HS-651: Use findEventsByNodeId for events on node status page

---

charts/opennms/templates/opennms/minion/minion-deployment.yaml
charts/opennms/templates/opennms/minion/minion-gateway-deployment.yaml
minion/docker-assembly/src/main/docker/app/Dockerfile

Disable Ignite version lookups at runtime
Working towards reducing the number of external calls made by the services

disable ignite notifier

---

ui/src/components/Common/Icon.vue
ui/src/components/Inventory/DetectedNodesTabContent.vue
ui/src/components/Inventory/IconActionList.vue
ui/src/components/Inventory/MonitoredNodesTabContent.vue
ui/src/store/Queries/inventoryQueries.ts
ui/src/types/index.ts
ui/tests/Inventory/iconActionList.test.ts

Adds link from inventory card to the node status page
Removes uptime from card as that will not be available
Removes other action items that don't do anything for now (as per meeting convo)
Adds optional tooltip for Icon component
- https://issues.opennms.org/browse/HS-643

HS-643: Add link to node status page, inventory card mods

---

Tiltfile
build-tools/basic/run-port-forwards.sh
charts/opennms/values.yaml
inventory/src/main/java/org/opennms/horizon/inventory/component/TaskSetResultsConsumer.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/InventoryServerInterceptor.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/IpInterfaceRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TrapConfigService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/DetectorTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/MonitorTaskSetService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/manager/DefaultTaskSetManager.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/manager/TaskSetManager.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/manager/TaskSetManagerUtil.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/response/DetectorResponseService.java
inventory/src/test/java/org/opennms/horizon/inventory/component/TaskSetResultsConsumerTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/DetectorResponseServiceIntTest.java
platform/traps/src/main/java/org/opennms/horizon/traps/consumer/TrapSinkConsumer.java

HS-611: Support tenant id in inventory for tasksets
- updating port forward in tilt for alarm service again due to the conflict with the new grpc proxy service
- i had to reduce the memory of some services as i ran into problems with memory on startup when the new grpc proxy service was added (please review the values)
- tested this by passing tenant id through grpc header and seeing it in Minion Gateway interceptor through debug breakpoint, then seeing the tenant id coming through in the kafka consumer.
- https://issues.opennms.org/browse/HS-611

HS-611: Support tenant id in inventory for tasksets

---

inventory/src/main/java/org/opennms/horizon/inventory/component/MinionRpcClient.java
inventory/src/main/java/org/opennms/horizon/inventory/component/MinionRpcManager.java
inventory/src/main/java/org/opennms/horizon/inventory/config/MinionGatewayGrpcClientConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/grpc/TenantIdClientInterceptor.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
inventory/src/test/java/org/opennms/horizon/inventory/SpringContextTestInitializer.java
inventory/src/test/java/org/opennms/horizon/inventory/TestConstants.java
inventory/src/test/java/org/opennms/horizon/inventory/component/MinionRpcClientTest.java
inventory/src/test/java/org/opennms/horizon/inventory/component/MinionRpcManagerTest.java
metrics-processor/src/main/java/org/opennms/horizon/tsdata/Constants.java
metrics-processor/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
minion-gateway/ignite-detector/server/src/main/java/org/opennms/miniongateway/detector/server/IgniteRpcRequestDispatcher.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/RpcRequestDispatcher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/GrpcServerConfig.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/rpcrequest/RpcRequestRouterIgniteTask.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TaskSetTwinMessageProcessor.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/ignite/LocalIgniteRpcRequestDispatcher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/taskset/TaskSetPublisherImpl.java
rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java
rest-server/src/main/java/org/opennms/horizon/server/service/PrometheusTSDBServiceImpl.java
rest-server/src/main/java/org/opennms/horizon/server/utils/JWTValidator.java
rest-server/src/main/java/org/opennms/horizon/server/utils/ServerHeaderUtil.java
rest-server/src/main/resources/application.yml
rest-server/src/test/resources/application.yml
shared-lib/task-set-service/api/src/main/java/org/opennms/taskset/service/api/TaskSetForwarder.java

(stealing existing jira id, probably require re-wording) This PR is result of testing I made with minion with non-standard tenant-id.
1) Propagation of tenant-id to metrics labels
2) Inventory service tenant-id header injection for its clients
3) Basic validation of auth token in rest-server (avoid re-use of expired tokens)
4) Remove use of grpc-tenant interceptor for internal minion gateway rpc calls initiated from ignite job.
https://issues.opennms.org/browse/HS-611

HS-611 Further work on tenant-id handling updates

---

minion/assembly/src/main/resources/etc/org.opennms.core.ipc.grpc.client.cfg
minion/docker-assembly/src/main/docker/app/Dockerfile

Possibility to control grpc connection via env vars.
- https://issues.opennms.org/browse/HS-661

HS-661 Allow customization of grpc contact point for minion by env vars

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/NodeStatusService.java

HS-669: Errors while loading Node Inventory page
Making the nested call reactive instead of performing a blocking get. The Mono did not like the nested call.
- https://issues.opennms.org/browse/HS-669

HS-669: Errors while loading Node Inventory page

---

inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/GrpcTwinPublisherConfig.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/AbstractTwinPublisher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/GrpcTwinPublisher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TaskSetTwinMessageProcessor.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinProvider.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinPublisher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinRequest.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinRpcHandler.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinUpdate.java

Adding tenant id in twin publisher.
Also send detector tasks on Inventory service restart
- https://issues.opennms.org/browse/HS-660

HS-660 Propagation of tenant-id via TwinPublisher

---

inventory/pom.xml
inventory/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/ConfigUpdateService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/src/test/java/org/opennms/horizon/inventory/component/NodeMonitoringManagerTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcServiceTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcStartupIntTest.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/taskset/TestTaskSetGrpcService.java
inventory/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/DetectorResponseServiceIntTest.java

Tasks/Config updates should be sent asynchronously while adding a Minion or a Device.
Any failure related to task/config updates shouldn't effect adding Minion/Device to the DB.
- https://issues.opennms.org/browse/HS-753

HS-753: Asynchronously update tasks and config changes

---

alarm/src/main/resources/application.yaml
alarm/src/test/resources/org/opennms/horizon/alarmservice/alarm.feature
events/main/src/main/resources/application.yml

`events-proto` name was workaround as `events` was already a kafka topic in Core.
Correcting that now since Core no longer exists.
- https://issues.opennms.org/browse/HS-785

HS-785: Rename kafka topic from events-proto to events

---

charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/prometheus/cortex-configmap.yaml
charts/opennms/templates/prometheus/cortex-deployment.yaml
charts/opennms/templates/prometheus/cortex-service.yaml
charts/opennms/templates/prometheus/prometheus-configmap.yaml
charts/opennms/values.yaml

Add Cortex to the stack and integrate it into the write/read paths:
* add the Cortex service
* push metrics from Prometheus to Cortex using the Remote Write API
* point the BFF to the Read API on Cortex
This keeps everything working, and allows us to begin writing directly to Cortex. We can then remove Prometheus and the PushGateway once complete.

add Cortex to the stack

---

metrics-processor/pom.xml
metrics-processor/src/main/java/org/opennms/timeseries/cortex/CortexTSS.java
parent-pom/pom.xml

HS-802
Update Metrics-processor dependecy org.opennms.plugin.timeseries.cortex.wrap:resilience4j to io.github.resilience4j.
- https://issues.opennms.org/browse/HS-802

Use dependency io.github.resilience4j:1.7.0 in metrics-processor

---

events/grpc/src/main/java/org/opennms/horizon/events/grpc/client/InventoryClient.java
events/grpc/src/main/java/org/opennms/horizon/events/grpc/config/ConfigurationUtil.java
events/main/src/main/resources/application.yml
inventory/src/main/java/org/opennms/horizon/inventory/component/MinionRpcClient.java
inventory/src/main/java/org/opennms/horizon/inventory/config/MinionGatewayGrpcClientConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/publisher/GrpcTaskSetPublisher.java
inventory/src/main/resources/application.yml
inventory/src/test/java/org/opennms/horizon/inventory/component/MinionRpcClientTest.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/GrpcClientConstants.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/MinionGrpcClient.java
minion/minion-grpc/grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
rest-server/src/main/java/org/opennms/horizon/server/config/ConfigurationUtil.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/EventsClient.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/main/resources/application.yml
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/InventoryClientDeadlineTest.java
rest-server/src/test/java/org/opennms/horizon/server/service/grpc/InventoryClientTest.java

default value 60000 milliseconds
HS-775
Add a configurable deadline to all gRPC call, it's default value is 60 seconds. see [https://grpc.io/blog/deadlines/](url)
- https://issues.opennms.org/browse/HS-775

HS-775 - Add a configurable deadline to all gRPC call

---

notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyDaoImpl.java
notifications/src/main/java/org/opennms/horizon/notifications/mapper/PagerDutyConfigMapper.java
notifications/src/main/java/org/opennms/horizon/notifications/model/PagerDutyConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/repository/PagerDutyConfigRepository.java
notifications/src/main/resources/application.yml
notifications/src/main/resources/db/changelog/changelog.xml
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/pagerDutyConfigUpdate.xml
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyAPIImplTest.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyDaoImplTest.java
parent-pom/pom.xml

Use JPA instead of jdbcTemplate as that's what the rest of the application is using
- https://issues.opennms.org/browse/HS-870
n/a

HS-870: Use JPA instead of jdbcTemplate for notifications

---

inventory/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
metrics-processor/main-metrics/src/test/java/org/opennms/horizon/tsdata/TSDataProcessorTest.java
metrics-processor/timeseries/pom.xml
metrics-processor/timeseries/src/main/java/org/opennms/horizon/tsdata/TSDataProcessor.java
minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureCollector.java
minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureMonitor.java
minion/plugins/azure-plugin/src/main/java/org/opennms/horizon/minion/azure/AzureScanner.java
shared-lib/azure/proto/src/main/proto/azure-api.proto
shared-lib/protobuf/src/main/proto/taskSet.proto

REQUEST:
```
GET /prometheus/api/v1/query?query=ifOutOctets{instance="127.0.0.2", monitor="AZURE", node_id="2"}[1000s]
X-Scope-OrgID: opennms-prime
```
RESPONSE:
```
{
"status": "success",
"data": {
"resultType": "matrix",
"result": [
{
"metric": {
"__name__": "ifOutOctets",
"instance": "127.0.0.2",
"location": "Default",
"monitor": "AZURE",
"node_id": "2",
"system_id": "opennms-minion-5885b9df75-hf5kn"
},
"values": [
[
1674221552.342,
"123605"
]
]
}
]
}
}
```
- https://issues.opennms.org/browse/HS-836

HS-836: Use new Monitor Type AZURE in Monitor and Collector

---

notifications/src/main/java/org/opennms/horizon/notifications/grpc/config/TenantIdentifierResolver.java
notifications/src/main/java/org/opennms/horizon/notifications/model/PagerDutyConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/model/TenantAwareEntity.java
notifications/src/main/resources/db/changelog/changelog.xml
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/pagerDutyConfigTenantUpdate.xml
notifications/src/test/java/org/opennms/horizon/notifications/GrpcTestBase.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/resources/org/opennms/horizon/notifications/notification-grpc-processing.feature

Multi tenancy for notification component
- https://issues.opennms.org/browse/HS-895
Uses Hibernate TenantId annotation which does all the work for us.
Question: In TenantIdentifierResolver should we always have a tenant id? I'm guessing we should, but don't want to do a load of rework in the tests if this is not necessary.
After some investigation, it appears we have to provide a default if the there isn't one available.

HS-895: add tenant id to notifications

---

notifications/pom.xml
notifications/src/test/resources/application.yml

The h2database dependency causes dependabot's security scanner to rise red flag. Switching it to another embedded database gets backend services clear of major CVEs.
- https://issues.opennms.org/browse/HS-957

HS-957 Replace h2database with hsqldb

---

ui/src/store/Queries/appliancesQueries.ts
ui/src/store/Queries/inventoryQueries.ts

Display nodes without IPs. Metrics will not work with these nodes until further BE/FE changes.
- https://issues.opennms.org/browse/HS-976

HS-976: Display nodes without IPs on inventory

---

notifications/src/main/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumer.java
notifications/src/main/resources/application.yml
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTestNoConfig.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerUnitTest.java
notifications/src/test/resources/application.yml

New alarms module does not send created alarms to notifications topic. TenantId has been added to headers and must be used
- https://issues.opennms.org/browse/HS-940
Not sure if I have covered the acceptance requirements correctly

HS-940 Update notifications topic and use tenant id header

---

notifications/pom.xml
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationsApplicationTests.java
notifications/src/test/java/org/opennms/horizon/notifications/SpringContextTestInitializer.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumerIntegrationTestNoConfig.java
notifications/src/test/resources/application.yml
notifications/src/test/resources/logback.xml

Better to use postgres in tests as that's what is used in production
- https://issues.opennms.org/browse/HS-959
n/a

HS-959: Remove HSQL in memory database in tests in favour of postgres

---

inventory/src/main/java/org/opennms/horizon/inventory/repository/MonitoringSystemRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/ConfigUpdateService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/FlowsConfigService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TrapConfigService.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/GrpcTestBase.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/MonitoringSystemGrpcItTest.java
inventory/src/test/java/org/opennms/horizon/inventory/service/taskset/response/DetectorResponseServiceIntTest.java

Also remove tasksets from Gateway
When there is no single monitoring system for a given location, location should also be deleted.
(This will prevent any new devices going to non-existing locations)
- https://issues.opennms.org/browse/HS-993

HS-993: Remove locations when all monitoring systems are deleted

---

inventory/src/main/java/org/opennms/horizon/inventory/grpc/TagGrpcService.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/TagRepository.java
inventory/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeTaggingStepDefinitions.java
inventory/src/test/java/org/opennms/horizon/inventory/grpc/TagGrpcItTest.java
inventory/src/test/resources/org/opennms/horizon/inventory/node-tagging.feature
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLTagServiceTest.java
shared-lib/inventory/src/main/proto/tagService.proto

HS-1015: Inventory - Partial Search on Tags
the ui needs to search for the tags for the auto populate box, this is adding that functionality to the list endpoints as an optional search term string
```
query {
tags (searchTerm: "abc") {
id,
tenantId,
name
}
}
```
```
query {
tagsByNodeId (nodeId: 1, searchTerm: "abc") {
id,
tenantId,
name
}
}
```
- https://issues.opennms.org/browse/HS-1015

HS-1015: Inventory - Partial Search on Tags

---

parent-pom/pom.xml

Upgrade log4j2 to fix deserialization of Untrusted Data in Log4j. CVE: CVE-2019-17571
Upgrade log4j2 to fix JMSAppender in Log4j 1.2 is vulnerable to deserialization of untrusted data CVE: CVE-2022-23302
- https://issues.opennms.org/browse/HS-964
None

HS-964: Deserialization of Untrusted Data in Log4j

---

ui/yarn.lock

CVE: CVE-2023-23936
https://issues.opennms.org/browse/HS-1050
https://issues.opennms.org/browse/HS-1051
https://issues.opennms.org/browse/HS-1052
https://issues.opennms.org/browse/HS-1053
There was a PR https://github.com/OpenNMS-Cloud/horizon-stream/pull/757
which had this same changes but all the checks were failing so I have just created this new PR which solved all the failing checks with a recent pull

HS-1050: Bump undici from 5.16.0 to 5.19.1

---

inventory/src/main/java/org/opennms/horizon/inventory/model/ActiveDiscoveryConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/model/DiscoveryConfig.java
inventory/src/main/java/org/opennms/horizon/inventory/repository/ActiveDiscoveryConfigRepository.java
inventory/src/main/resources/db/changelog/changelog.xml
inventory/src/main/resources/db/changelog/hs-0.1.0/tables/active-discovery-config.xml
inventory/src/test/java/org/opennms/horizon/inventory/repository/ActiveDiscoveryConfigRepositoryTest.java

- created table active-discovery-config
- created repository ActiveDiscoveryConfigRepository 
- created entity ActiveDiscoveryConfig
HS-1103
Currently, Active Discovery is being persisted in generic Config table.
But we need to move this to Active Discovery Config table that consists of 
1. tenant_id
2. location
3. profile name
4. IPAddresses (ranges/specific/cidr) 
5. SNMP community strings 
6. SNMP agent config ports. 
4-5-6 can be combined one DTO that can be saved as json.
This task involves creating **table**, **entity**, **repository**.
- https://issues.opennms.org/browse/HS-1103

HS-1103: Add Active Discovery Config table persistence

---

inventory/main/pom.xml
notifications/pom.xml
parent-pom/pom.xml
rest-server/src/main/docker/Dockerfile

Also update referenced hash to point to the manifest list vs a particular image, and bump up the jib plugin to the latest.

consolidate base image for services to use: eclipse-temurin:17-jre

---

ui/package.json
ui/src/composables/useKeycloak.ts
ui/src/main.ts
ui/src/services/gqlService.ts
ui/tests/Appliances/appliances.test.ts
ui/tests/Layout/menubar.test.ts
ui/yarn.lock

Seems like there are flaky errors like `dsb-vue-keycloak.esm.js:165 Error: Failure during initialization of keycloak-js adapter at dsb-vue-keycloak.esm.js:162:23`, that could to do with the UI keycloak pckg itself. Current package only supports kc v15, but updating supports v18.
Looks like the dockerfile is using quay.io/keycloak/keycloak:19.0.2 but I'm hoping that at least supporting v18 may solve some of these issues. Tested locally and it ran successfully.
- https://issues.opennms.org/browse/HS-1160

HS-1160: Update keycloak to support v18

---

ui/src/components/Discovery/DiscoveryListCard.vue
ui/src/containers/Discovery.vue
ui/src/graphql/Discovery/togglePassiveDiscoveryMutation.graphql
ui/src/store/Mutations/discoveryMutations.ts
ui/src/types/graphql.ts

Works in the discovery sidebar, but it's not yet on the edit page itself. Will come after overall edit functionality.
- https://issues.opennms.org/browse/HS-1146

HS-1146: Add mutation for passive discovery toggle

---

ui/src/components/Discovery/DiscoveryAzureForm.vue

Fixes an issue with props added to the payload, causing GQL error
- https://issues.opennms.org/browse/HS-1148

HS-1148: Make sure _text is not included in payload

---

.github/workflows/feature-parent-pom.yml

Moved sonar cloud project key to GHA secrets
- https://issues.opennms.org/browse/HS-1184

HS-1184 - moved sonar cloud project key to GHA secrets

---

notifications/src/main/java/org/opennms/horizon/notifications/kafka/AlarmKafkaConsumer.java
notifications/src/main/java/org/opennms/horizon/notifications/kafka/TenantAwareKafkaListener.java
notifications/src/main/java/org/opennms/horizon/notifications/kafka/TenantAwareKafkaListenerAspect.java
notifications/src/main/java/org/opennms/horizon/notifications/tenant/WithTenant.java
notifications/src/main/java/org/opennms/horizon/notifications/tenant/WithTenantAspect.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java

Draft PR showing POC work on Aspect for Kafka Listener to retrieve Tenant from header info.
Also include a parameter, so can choose to skip processing if tenant is not present.
(If you wish to perform something different in the event of a missing tenant id, can always call TenantLookup.getTenantId in the method with KafkaListener on it, and process according to your wishes.)
The second commit has added a WithTenant aspect. This should make tests look nicer. Also anywhere that doesn't come in from a GRPC call or via a KafkaListener.
- https://issues.opennms.org/browse/HS-1135
n/a

HS-1135: Added Aspect for dealing with multi tenancy for Kafka listeners

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLTagServiceTest.java

HS-1209: Get Tags by Passive Discovery ID
REQUEST
```
query {
tagsByPassiveDiscoveryId (passiveDiscoveryId: 1) {
id,
tenantId,
name
}
}
```
RESPONSE
```
{
"data": {
"tagsByPassiveDiscoveryId": [
{
"id": 1,
"tenantId": "opennms-prime",
"name": "tag1"
}
]
}
}
```
Just needed to add the BFF component
- https://issues.opennms.org/browse/HS-1209

HS-1209: Get Tags by Passive Discovery ID

---

.github/CODEOWNERS

- PRs that touch this folder need to be approved by the "architecture" team
- Primarily for ADRs
- https://issues.opennms.org/browse/AR-28
- Created an "Architecture" team and had to explicitly give it write access to the repo for this to work.

AR-28: Add CODEOWNERS for architecture docs

---

minion/assembly/pom.xml

Minion startup should be possible with no internet access. This means that all "system" dependencies should be embedded into its image/archive.
- https://issues.opennms.org/browse/HS-1249

HS-1249 Include cxf-karaf-commands in minion software distribution.

---

.github/workflows/develop.yml

- Disables the trigger for develop workflow when only non-code paths change
- Still triggers when code paths do change
The ignored folders may also contain code, but they are not used in any tests in the develop workflow.
- https://issues.opennms.org/browse/HS-1245

HS-1245: Disable develop workflow when PR only touches non-code paths

---

rest-server/src/main/java/org/opennms/horizon/server/model/inventory/tag/NodeTags.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcTagService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
rest-server/src/test/java/org/opennms/horizon/server/service/GraphQLTagServiceTest.java

HS-1216: Get Tags for Node Ids
```
query {
tagsByNodeIds (nodeIds: [1, 2]) {
nodeId,
tags {
id,
tenantId,
name
}
}
}
```
```
{
"data": {
"tagsByNodeIds": [
{
"nodeId": 1,
"tags": [
{
"id": 1,
"tenantId": "opennms-prime",
"name": "Tag1"
}
]
},
{
"nodeId": 2,
"tags": []
}
]
}
}
```
- https://issues.opennms.org/browse/HS-1216

HS-1216: Get Tags for Node Ids

---

minion-gateway/docker-it/src/test/java/org/opennms/horizon/testcontainers/TestContainerRunnerClassRule.java

Do not enable debugging port by default to avoid unexpected build failures

Comment enabling of debugging port for application container

---

notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/java/org/opennms/horizon/notifications/config/NotificationsConfig.java
notifications/src/main/java/org/opennms/horizon/notifications/exceptions/NotificationAPIRetryableException.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/api/PagerDutyAPITest.java
notifications/src/test/resources/org/opennms/horizon/notifications/notification-processing.feature

If PagerDuty was down or returned a non-successful response code, the notification would be lost. This commit add some configuration to retry and give a best effort for delivering the notification.
- https://issues.opennms.org/browse/HS-1303
null

HS-1303 Add retries for posting notifications to PagerDuty

---

minion-gateway/main/src/main/java/org/opennms/miniongateway/ignite/IgniteConfig.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/jdbc/JdbcInitComponent.java
minion-gateway/main/src/test/java/org/opennms/miniongateway/jdbc/JdbcInitComponentTest.java
minion/docker-it/src/test/java/org/opennms/horizon/dockerit/testcontainers/TestContainerRunnerClassRule.java

Add JdbcInitComponent that waits - up to a timeout - for the database to be accessible, and make the ignite bean depend on it.
This works-around the problem that Ignite only tries one time to get connected to the database for cache JDBC storage, thereby making the service not resilient to slowness, or temporary DB outage, during startup.
- https://issues.opennms.org/browse/HS-1284

HS-1284: Add JdbcInitComponent for Ignite

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumer.java
metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/monitor/TaskSetMonitorResultProcessor.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/monitor/TaskSetMonitorResultProcessorTest.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutionResultProcessorImpl.java
minion/plugins/icmp-plugin/src/main/java/org/opennms/horizon/minion/icmp/IcmpMonitor.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponse.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponseImpl.java
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java
shared-lib/protobuf/src/main/proto/taskSet.proto

Propagation of metric collection timestamp from minion to opennms backend.
- https://issues.opennms.org/browse/HS-1082
I am not clear on timezone handling. Minions will span across different zones hence I think we should go with UTC times, but then there is a question of how cortex/prometheus is interpreting timestamp attached to metric.
Finally there is a question of out-of-order samples received with a significant delay.

HS-1082 Support for propagation of metric collection time.

---

notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/kafka/MonitoringPolicyKafkaConsumer.java
notifications/src/main/java/org/opennms/horizon/notifications/mapper/MonitoringPolicyMapper.java
notifications/src/main/java/org/opennms/horizon/notifications/model/MonitoringPolicy.java
notifications/src/main/java/org/opennms/horizon/notifications/repository/MonitoringPolicyRepository.java
notifications/src/main/java/org/opennms/horizon/notifications/service/MonitoringPolicyService.java
notifications/src/main/resources/db/changelog/changelog.xml
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/monitoringPolicy.xml
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/MonitoringPolicyKafkaConsumerTest.java
notifications/src/test/java/org/opennms/horizon/notifications/service/MonitoringPolicyServiceImplTest.java
notifications/src/test/resources/application.yml
notifications/src/test/resources/org/opennms/horizon/notifications/monitoring-policy.feature

Receives a monitoring policy over a Kafka topic, and we pull out the bits relative to notifications. These policies will then be used to enable configuration in the notifications processing flow.
- https://issues.opennms.org/browse/HS-1140
Should think about refactoring the Cucumber steps file, it looks large but lots is related to tests.

HS-1140: Persist Monitoring Policy for Notifications in Postgres

---

install-local/postgres-for_testing_keycloak_realm_update.yaml

Added a testing yaml for postgres on testing keycloak. Rather than rebuild. Because configmaps for keycloak only update on db init not after it has been created.
- https://issues.opennms.org/browse/HS-1353

HS-1353 - Added yaml for postgres keycloak testing

---

notifications/src/main/java/org/opennms/horizon/notifications/kafka/AlertKafkaConsumer.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlertKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlertKafkaConsumerUnitTest.java
notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationsServiceImplTest.java
notifications/src/test/resources/org/opennms/horizon/notifications/notification-processing.feature
shared-lib/events/src/main/proto/alerts.proto

Now that monitoring policies are persisted in the notification service, we can reference them when processing notifications for alerts, choosing the destination of the notification based on the policy.
- https://issues.opennms.org/browse/HS-1140

HS-1140: Use monitoring policy to send notifications

---

notifications/src/main/java/org/opennms/horizon/notifications/repository/MonitoringPolicyRepository.java
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/test/java/org/opennms/horizon/notifications/NotificationCucumberTestSteps.java
notifications/src/test/java/org/opennms/horizon/notifications/kafka/AlertKafkaConsumerIntegrationTest.java
notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationsServiceImplTest.java
shared-lib/events/src/main/proto/alerts.proto

Alerts may have multiple monitoring policies associated with them, so the notification service needs to honor that.
- https://issues.opennms.org/browse/HS-1140

HS-1140 Allow matching multiple monitoring policies for alerts

---

notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationServiceImplTest.java

Fix a defect where pager duty will be called multiple times for a single alert if there are multiple policies that have the pager duty flag set.
- https://issues.opennms.org/browse/HS-1389
n/a

Only call pagerDuty once if there are multiple monitoring policies for an alert that have the pager duty flag set

---

ui/package.json
ui/src/components/Inventory/InventoryFilter.vue
ui/src/containers/Inventory.vue
ui/src/graphql/Views/inventoryQueries.graphql
ui/src/store/Queries/inventoryQueries.ts
ui/src/types/graphql.ts
ui/src/types/index.ts
ui/yarn.lock

Updates Villus so that we can use the `onData` callbacks.
Adds inventory search functionality by node label.
- https://issues.opennms.org/browse/HS-1345

HS-1345: Add search inventory nodes by label

---

.github/workflows/base-image-update.yml
.github/workflows/feature-alert.yml
.github/workflows/feature-datachoices.yml
.github/workflows/feature-events.yml
.github/workflows/feature-inventory.yml
.github/workflows/feature-metrics-processor.yml
.github/workflows/feature-minion-gateway-grpc-proxy.yml
.github/workflows/feature-minion-gateway.yml
.github/workflows/feature-minion.yml
.github/workflows/feature-notifications.yml
.github/workflows/feature-operator.yml
.github/workflows/feature-parent-pom.yml
.github/workflows/feature-rest-server.yml
.github/workflows/feature-shared-lib.yml
.github/workflows/feature-ui.yml

This makes SonarCloud happy. Also enabled shallow clone for base-image-update, which does not do any SonarCloud scanning
- https://issues.opennms.org/browse/HS-1429

[HS-1429] Disabled shallow clones for operator and ui workflows

---

keycloak-ui/themes/horizon-stream/login/resources/css/login.css
keycloak-ui/themes/horizon-stream/login/resources/js/theme.js
keycloak-ui/themes/horizon-stream/login/template.ftl
keycloak-ui/themes/horizon-stream/login/theme.properties

Looks like the animation was causing Chrome issues for some people. Switching to static gradient for now.
- https://issues.opennms.org/browse/HS-1446

HS-1446: Switch to static gradient for login screens

---

external-it/hs-system-tests/pom.xml
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
external-it/hs-system-tests/src/test/java/org/opennms/horizon/systemtests/steps/cloud/UdpGenSteps.java
external-it/hs-system-tests/src/test/java/testcontainers/MinionContainer.java
external-it/hs-system-tests/src/test/java/testcontainers/UpdGenContainer.java

- `Update` testcontainers version to the latest one (to expose udp ports)
- `Add` UdpGen container 
- `Update` MinionContainer (expose UDP ports + method to obtain mapped UDP port)
- `Add` steps for UdpGen to send flows data to test minion
Overall: now we can check cases with Flows graphs.

[HS-1480] Add Udpgen container that sends flows traffic to test minion

---

minion/assembly/src/main/resources/etc/org.opennms.core.ipc.grpc.client.cfg
minion/docker-it/src/test/java/org/opennms/horizon/dockerit/testcontainers/TestContainerRunnerClassRule.java
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/ssl/MinionGrpcSslContextBuilderFactoryImpl.java
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/ssl/MinionGrpcSslContextBuilderFactoryImplTest.java

This PR bring back previous behavior and allows to connect minion to cloud instances.
- https://issues.opennms.org/browse/HS-1496
-

HS-1496 Make sure trust manager is configured only if custom CA file exists

---

alert/src/main/java/org/opennms/horizon/alertservice/service/routing/EventConsumer.java
inventory/main/src/main/java/org/opennms/horizon/inventory/component/NodeMonitoringManager.java
inventory/main/src/main/java/org/opennms/horizon/inventory/exception/EntityExistException.java
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/component/NodeMonitoringManagerTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/grpc/NodeGrpcServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseServiceIntTest.java

- Prevent creating multiple nodes with the trap events from the same tenant, same location, and same IP address
- Prevent triggering an alert before a node is created.
- https://issues.opennms.org/browse/HS-1476

HS-1476 Prevent creating multiple nodes when receiving trap events

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
events/traps/src/main/java/org/opennms/horizon/events/traps/EventFactory.java
events/traps/src/main/java/org/opennms/horizon/events/traps/TrapsConsumer.java
events/traps/src/test/java/org/opennms/horizon/events/traps/EventFactoryTest.java
notifications/src/main/java/org/opennms/horizon/notifications/api/PagerDutyAPI.java
notifications/src/main/resources/alert.html.vm
shared-lib/events/src/main/proto/events.proto

When an alert is recieved by the Notification service, it doesn't have any real detail about what the trap means. This PR adds the description and log message to the event, which will also be added to the alert to provide some context for the notification.
Sending a trap matching a monitoring policy that has PagerDuty and email enabled will trigger both of those notifications:
There is probably some more tweaking to those notifications to highlight which node the alert applies to, etc.
- https://issues.opennms.org/browse/HS-1532

HS-1532 Include trap description and log message in event

---

ui/mock-graphql/index.ts
ui/mock-graphql/package.json
ui/mock-graphql/yarn.lock

Updates packages for our mock server. Removes deprecated `@graphql-yoga/node` in favour of `graphql-yoga`.
This fixes the following security issues:
- https://issues.opennms.org/browse/HS-766
- https://issues.opennms.org/browse/HS-795
- https://issues.opennms.org/browse/HS-796
- https://issues.opennms.org/browse/HS-797
- https://issues.opennms.org/browse/HS-803

HS-766: Update mock server pckgs to fix security issues

---

charts/opennms/templates/opennms/minion/minion-gateway-deployment.yaml

We've been crashes fairly often in the minion-gateway (OOMs). Let's
see if this fixes it, and if not, we'll just remove it from
JAVA_TOOL_OPTIONS.

Temporarily disable the otel javaagent for minion-gateway

---

doc/architecture/decisions/0004-create-new-monitoring-policy-service.md

Proposed ADR for moving monitoring policies out of the alert service and creating a new microservice for them.
- https://issues.opennms.org/browse/AR-72
Would like some input on context and consequences.

AR-72: Add ADR for new Monitoring Policy service

---

charts/opennms/templates/_helpers.tpl
charts/opennms/templates/keycloak/keycloak-deployment.yaml
charts/opennms/templates/opennms/alert/alert-deployment.yaml
charts/opennms/templates/opennms/api/api-deployment.yaml
charts/opennms/templates/opennms/datachoices/datachoices-deployment.yaml
charts/opennms/templates/opennms/events/events-deployment.yaml
charts/opennms/templates/opennms/inventory/inventory-deployment.yaml
charts/opennms/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/opennms/templates/opennms/minion-gateway-grpc-proxy/minion-gateway-grpc-proxy-deployment.yaml
charts/opennms/templates/opennms/minion/minion-gateway-deployment.yaml
charts/opennms/templates/opennms/notification/notification-deployment.yaml
charts/opennms/templates/opennms/spring-boot-env-configmap.yaml
charts/opennms/values.yaml

- Create a helper include for deployment-specific env variables
- Add OpenNMS.global.openTelemetry.env and use it to set propagators
- Move OTEL_JAVAAGENT_ENABLED=false into the values file

OpenTelemetry config tweaks

---

minion/assembly/runInPlace.sh

I've introduced two new switches:
- `-g AUTHORITY` - assigns custom authority to server, can be used with -h if host is an IP address which shows certificate for specific domain.
- `-T` - extract secrets via kubectl from development tilt setup. -s
- https://issues.opennms.org/browse/HS-1310

HS-1310 Make sure runInPlace.sh works with tilt

---

ui/codegen.yml
ui/package.json
ui/yarn.lock

Now that the GQL playground is under https, generating types will fail - but we can get around this by setting NODE_TLS_REJECT_UNAUTHORIZED=0 for the gen cmd. Added cross-env do to this on mac/windows.
- https://issues.opennms.org/browse/HS-1576

HS-1576: Let code-gen make request to GQL playground

---

ui/src/components/Appliances/AppliancesMinionsTable.vue
ui/src/components/Graphs/LineGraph.vue
ui/src/components/NodeStatus/NodeStatusMetricsModal.vue
ui/src/composables/useGraphs.ts
ui/tests/fixture/metrics.ts

Fixes some minor issues with graph name / multiple metrics on one graph.
Adds more graphs to the node status page, for each interface (bandwidth, latency, errors).
- https://issues.opennms.org/browse/HS-1556

HS-1556: Add graphs for interfaces

---

inventory/main/src/main/java/org/opennms/horizon/inventory/component/TagPublisher.java

Remove use of ApplicationReadyEvent
- https://issues.opennms.org/browse/HS-1606

HS-1606: Remove publishing of tags on Application start

---

alert/src/main/resources/db/changelog/hs-0.1.0/tables/alert.xml
alert/src/main/resources/db/changelog/hs-0.1.0/tables/thresholded_event.xml

This is a temporary fix, Liquibase permanently locked the database and couldn't proceed.
- https://issues.opennms.org/browse/HS-1617

HS-1617: Disable distributed tables which were causing issues on Citus

---

alert/pom.xml
datachoices/pom.xml
events/pom.xml
inventory/main/pom.xml
minion-gateway/task-set-service/pom.xml
minion/docker-it/pom.xml
minion/pom.xml
notifications/pom.xml
parent-pom/pom.xml
rest-server/pom.xml

Fixes warnings from Maven about a deprecated 'localRepository' parameter. Uses pluginManagement in the parent-pom to define the versions.
Minion was using version 2.22.2 of surefire, this is a big bump so tests might not pass.
- https://issues.opennms.org/browse/HS-1614

HS-1614: Update failsafe and surefire plugins to latest 3.1.0 version

---

Tiltfile

The 'test' property is used to specify what tests to run in surefire, not disable tests. This removes that property and replaces it with `skipUTs`.
- https://issues.opennms.org/browse/HS-1619

HS-1619: Fix failed Minion build in Tilt caused by incorrect property

---

charts/opennms/templates/cortex/cortex-configmap.yaml
charts/opennms/templates/opennms/minion-certificate-manager/minion-certificate-manager-deployment.yaml
charts/opennms/templates/opennms/minion-certificate-manager/minion-certificate-verifier-deployment.yaml
minion-certificate-manager/main/pom.xml
minion-certificate-verifier/main/pom.xml
tilt-helm-values.yaml

- Add tracing and JSON logging to new minion certificate services
- Add otel tracing for Cortex, if enabled
- minion-gateway: enable the otel java agent in Tilt

Add tracing and JSON logging to new minion certificate services

---

minion-gateway/ipc-grpc-server/pom.xml
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/grpc/common/TenantIDGrpcServerInterceptor.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
parent-pom/pom.xml

This adds some very basic, but fairly useful, application tracing enhancements to the minion-gateway:
- Tracing: Set the "user" attribute to the tenant ID, if any -- Whenever code calls a method on `TenantIDGrpcServerInterceptor`, the tenantId is added as a span attribute to the current span (if any) with the key `user`. With this, you can do a tag search in a tracing tool to find traces for a specific tenantId, e.g.: `user=opennms-prime`.
- minion-gateway: Start a new span when we call dispatch -- The connections from the minion client to the minion-gateway are long lived and handle many requests, so the lifetime of the trace for the incoming connection is too long to be reasonable to directly contain the traces for all requests. This creates a new top-level trace every time we call …

Basic application tracing support for minion-gateway

---

Tiltfile
datachoices/pom.xml
datachoices/src/main/java/org/opennms/horizon/datachoices/service/DataChoicesService.java
install-local/generate-and-sign-certificate.sh
install-local/load-or-generate-secret.sh
inventory/main/pom.xml
inventory/main/src/main/java/org/opennms/horizon/inventory/component/MinionHeartbeatConsumer.java
minion-certificate-verifier/main/pom.xml
minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/controller/CertificateController.java
minion-gateway/ipc-grpc-server/pom.xml
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/grpc/common/LocationServerInterceptor.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
minion-gateway/main/pom.xml
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/heartbeat/HeartbeatKafkaForwarder.java
parent-pom/pom.xml
tilt-helm-values.yaml
tilt-jaeger-values.yaml

I strongly suggest reviewing commit-by-commit. There are two sonar tests that are failing because a few lines of tracing code were added in sections that already had no coverage. I’m hoping to ignore those failures.
The focus of this PR is to add Jaeger to Tilt to make tracing a first-class debugging tool. It also adds a few more
examples of adding some tracing bits to a few services (to prep for making their logs less noise in the future). It also has a few
small improvements.
Future work after this in upcoming PRs:
1. Disable the nginx-ingress in the opennms helm chart and install it as a separate helm chart like we do in our cloud environments. It will use the same version of nginx that we use in the cloud (or maybe newer). It will also enable tracing in the ingress like we have in the …

Add jaeger and enable tracing by default in Tilt

---

.github/workflows/develop.yml

Now that we require status checks to pass for merging to develop, we
were running into required checks that were never running due to path
filtering. I think this should fix it.
> Note: If a workflow is skipped due to path filtering, branch
> filtering or a commit message, then checks associated with that
> workflow will remain in a "Pending" state. A pull request that
> requires those checks to be successful will be blocked from merging.
>
> If a job in a workflow is skipped due to a conditional, it will
> report its status as "Success". For more information see Skipping
> workflow runs and Using conditions to control job execution.
-- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-chec …

Remove path filtering for develop workflow so status checks pass

---

minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/queue/RocksDbStore.java

RocksDB init requires to add the default namespace to the list of namespaces to open. But this is only required on first startup, as the second one will already have the namespace in the list of existing ones.
- https://issues.opennms.org/browse/HS-1693

HS-1693: Don`t add prefix twice on RocksDB startup

---

build-tools/basic/helm-values.yaml
charts/lokahi/templates/postgres/postgres-init-secret.yaml
install-local/install-local.sh
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
tilt-helm-values.yaml
tilt-ingress-nginx-values.yaml

This is best reviewed commit-by-commit because there's one main change, plus a number of things cleaned-up/improved along the way. This is one ancillary change that I wanted to highlight which is bolded.
The main change: [Tilt: fix adding test location to database](https://github.com/OpenNMS-Cloud/lokahi/pull/1211/commits/bc38390cc4b8bd07c366f1f4d58533144f2746d8) 
Follow the pattern in tests/minion-cert.sh for adding a location
(it it doesn't already exist) in the initContainer for the minion
that sets up certificates.
Added error checking so the init container won't successfully
finish until the location exists and the certificate is created.
In my experience, it takes 2-3 passes until everything is up, but
it does eventually complete.
Ancillary changes:
* Always return server-timing …

Tilt: fix adding test location to database

---

inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/CollectorTaskSetService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java

Update of monitoring state tracking and some minor fixes to snmp result processing for partial interface data.
Discussed with Jose, to mark node as monitored when we receive data. After discussion with Chandra I updated logic a bit to avoid continuous write to database for each monitoring tick we receive.
- https://opennms.atlassian.net/browse/HS-1653

HS-1653 Update monitoring state of detected/scanned nodes.

---

ui/src/services/gqlService.ts

Validation messages for invalid args come from the BE, but were showing on the UI as unknown errors. This fixes the gqlService to properly display invalid args messages across the app. Additional validation for specific inputs on the Minions page is not for EAR, and this page will soon be removed.
- https://opennms.atlassian.net/browse/HS-1202

HS-1202: Fix gql service to handle invalid args error messages

---

ui/src/composables/useTheme.ts

Dark theme was disabled but custom overrides using isDark still work. This sets isDark to always be false.
- https://opennms.atlassian.net/browse/HS-1740

HS-1740: Force isDark to always be false

---

test-automation/integration-tests/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/helper/TestsExecutionHelper.java
test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/lokahi.feature

Check for gql erorrs, except in the location delete case which will always have errors currently.
Restructure how locations/minions are managed in the tests, so they all have their own to reduce the likelihood of cascading problems, and not repeatedly creating the same location once it already exists.

Test cleanup hs1680

---

minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddrTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/IPAddressTableTracker.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/NodeScanner.java
minion/plugins/nodescan-plugin/src/main/java/org/opennms/horizon/minion/nodescan/SNMPInterfaceTableTracker.java
minion/plugins/nodescan-plugin/src/test/java/org/opennms/horizon/minion/nodescan/NodeScanTest.java

The node scan now ignore loopback SNMP interfaces and all IP interfaces which are not regular IPs like loopback, link-local, multicast, wildcards.
- https://opennms.atlassian.net/browse/HS-1481

HS-1481: Ignore some interface

---

charts/lokahi/scripts/opennms/minion/init-create-test-location.sh
charts/lokahi/templates/opennms/minion/minion-configmap.yaml
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
charts/lokahi/templates/opennms/minion/minion-rolebinding.yaml
charts/lokahi/templates/opennms/minion/minion-scripts-configmap.yaml
charts/lokahi/templates/opennms/minion/minion-service.yaml
charts/lokahi/templates/opennms/minion/minion-serviceaccount.yaml
charts/lokahi/values.yaml
install-local/install-local-opennms-lokahi-custom-images-values.yaml
test-automation/integration-tests/src/main/java/org/opennms/horizon/exttest/CucumberCommandLineRunner.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/InventoryTestSteps.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/LocationData.java
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/gqlmodels/MinionData.java
tilt-helm-values.yaml

- Minion: use default location instead of TestLocation
- Helm: Disable Minion by default, enable in Tilt and install-local
- CucumberCommandLineRunner: exit if command line options parsing fails
- InventoryTestSteps: debugging when unexpected locations exist
- InventoryTestSteps: deduplicate LocationData retrieval
- InventoryTestSteps: add @After to clean up minion location if it still exists
- InventoryTestSteps: organize imports

Minion: use default location instead of TestLocation, disable Minion by default

---

alert/src/main/java/org/opennms/horizon/alertservice/mapper/AlertConditionMapper.java
alert/src/main/java/org/opennms/horizon/alertservice/service/MonitorPolicyService.java
alert/src/test/java/org/opennms/horizon/alertservice/repository/MonitoringPolicyRepositoryTest.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/MonitorPolicySteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature
rest-server/src/main/java/org/opennms/horizon/server/mapper/alert/AlertConditionMapper.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/alert/PolicyRuleMapper.java
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/AlertCondition.java
rest-server/src/main/java/org/opennms/horizon/server/model/alerts/PolicyRule.java
rest-server/src/test/java/org/opennms/horizon/server/mapper/alert/MonitorPolicyMapperTest.java
shared-lib/alert/src/main/proto/alerts.proto
ui/src/components/MonitoringPolicies/MonitoringPoliciesCard.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesCardAlertRow.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesEventCondition.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesSaveButtons.vue
ui/src/graphql/Views/monitoringPolicies.graphql
ui/src/store/Views/monitoringPoliciesStore.ts
ui/src/types/graphql.ts
ui/src/types/policies.d.ts
ui/tests/MonitoringPolicies/monitoringPolicies.test.ts

Changes the APIs and UI to use AlertCondition instead of TriggerEvent.
This follows #1268, which changes the internals of the Alert service. Will rebase once that one is merged.
- https://opennms.atlassian.net/browse/HS-1776

HS-1776: Rename TriggerEvent to AlertCondition in APIs and UI 

---

minion-certificate-verifier/main/src/main/java/org/opennms/horizon/minioncertverifier/parser/BasicDnParser.java
minion-certificate-verifier/main/src/test/java/org/opennms/horizon/minioncertverifier/parser/BasicDnParserTest.java

For testing purposes, I use a PKI Layer based on [cert-manager](https://cert-manager.io/), an alternative to the local `minion-certificate-manager`. The problem is that, when adding multiple `OU` fields to the Subject, it is rendered with `+` instead of `,` as a separator confusing the `minion-certificate-validator`.
This small PR contains a patch that will fix the Subject/DN before parse it so it works regardless of what generated the certificate.

Be able to parse Subject/DN generated by cert-manager.

---

ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsEditForm.vue
ui/tests/Locations/locationsAddForm.test.ts
ui/tests/Locations/locationsEditForm.test.ts

Hides the address and coordinate inputs on the locations page.
- https://opennms.atlassian.net/browse/HS-1797

HS-1797: Hide address & coords inputs until map is ready post EAR

---

charts/lokahi/templates/keycloak/keycloak-deployment.yaml

By default, Keycloak was forced to be deployed in development mode (despite the `Dockerfile` being ready for both development and production mode). I verified the correct way to configure Keycloak behind a proxy for TLS termination when using production mode and found the following:
* We have to use `KC_HOSTNAME_URL` instead of the combination of `KC_HOSTNAME` and `KC_HOSTNAME_PORT`. If we don't do that, Keycloak won't start properly (tested with 19.x and 20.x).
* `KC_PROXY` must be set to `edge` to ensure that restricted access (enforced by production mode) works when having an Nginx Ingress controller terminating TLS (so we wouldn't need to pass the certificates to Keycloak ever).
Due to how the Helm chart was designed, the best approach I found to fix this while maintaining …

BTO-604: Ensure Keycloak would work in prod-mode.

---

ui/src/components/Discovery/DiscoveryAzureForm.vue
ui/src/components/Discovery/DiscoveryContentEditable.vue
ui/src/components/Discovery/DiscoveryLocationsAutocomplete.vue
ui/src/components/Discovery/DiscoverySnmpForm.vue

Disables editing inputs for ICMP/SNMP and Azure forms. User should still be able to edit passive discoveries.
- https://opennms.atlassian.net/browse/HS-1796

HS-1796: Disable editing discovery inputs

---

inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/monitored-state.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java

Updating node monitoring state needs to be revisited.
This is partial fix to unblock node creation
- https://opennms.atlassian.net/browse/HS-1812

HS-1812: Fix exception while adding nodes

---

ui/src/components/Inventory/InventoryFilter.vue

After making some changes via HS-1666, we accidentally broke the functionality of the tag search. This PR restores the functionality for the monitored nodes page.
- https://opennms.atlassian.net/browse/HS-1813
* ~~[ ] Notify documentation team of any changes to names of screens or features (affects URLs).~~

HS-1813: Hooking up Tag Search on Inventory Properly

---

ui/src/App.vue
ui/src/components/Welcome/WelcomeSlideThree.vue
ui/src/services/pendoService.ts
ui/src/store/Views/welcomeStore.ts

Bonnie needed some additional support for Pendo and triggering guides in certain situations.
I've added a PendoService to the project, that is a standardized way of adding <div> tags to a <div> at the root of the project with id 'pendo-area.' The idea here is that you use our new pendo service to add/remove Divs (with a value of 1) to the pendo area, which should be enough for Bonnie to activate/de-activate anything within Pendo.
If this process works (we need the code to be in Dev to even try), we will probably push an additional update for the Resource Center in another ticket, so that Bonnie can trigger it for every page aside for the welcome guide and login.
- https://opennms.atlassian.net/browse/HS-1829
It's tough to test this one, as there's a 3 and 10 minute timeout involved, and …

HS-1829: Pendo Guides for Minion + Discovery

---

charts/lokahi/templates/mail-server/mail-server-deployment.yaml
charts/lokahi/templates/mail-server/mail-server-service.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
charts/lokahi/values.yaml
install-local/install-local-opennms-lokahi-custom-images-values.yaml
install-local/install-local-opennms-lokahi-values.yaml
notifications/src/main/resources/application.yml
tilt-helm-values.yaml

- BTO-303: Disable the MailHog testing mail server by default
- BTO-303: add configurability for mail server options in Helm chart
- BTO-303: disable default SMTP parameters

BTO-303: helm mail server configuration

---

tilt-helm-values.yaml

The setting 'add_header X-Frame-Options sameorigin;' needed to be removed from nginx.ingress.kubernetes.io/configuration-snippet to get the local dev server working. tilt-helm-values was changed to remove ALL IngressAnnotations, which caused a problem due to missing settings.
- https://opennms.atlassian.net/browse/HS-1836

HS-1836: Stop tilt-helm-values from removing all OpenNMS.UI.IngressAnnotation settings

---

Tiltfile

- Tilt: Prep for making create_devmode_toggle_btn a bit more reusable
- Tilt: Add a dev mode toggle for the k8s metrics-server

Tilt: Add a dev mode toggle for the k8s metrics-server

---

ui/src/components/Common/DeleteConfirmationModal.vue
ui/src/components/Locations/LocationsCard.vue
ui/src/components/Locations/LocationsList.vue

Fixes an issue where the delete modal stays open and asks if you want to delete the next location in the list.
The main issue here was that multiple DeleteConfirmationModal components were rendering because of a v-for loop. This PR moves the comp to the parent, out of the loop, but does mean we need to pass up which item to delete.
[screencast-localhost_3009-2023.07.19-13_10_25.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/af2dc6d3-33bf-443c-b948-b9f69942e643)
- https://opennms.atlassian.net/browse/HS-1819

HS-1819: Fix multiple modal loc delete

---

ui/src/components/Flows/LineChart.vue
ui/src/containers/Flows.vue
ui/src/store/Views/flowsApplicationStore.ts
ui/src/store/Views/flowsStore.ts
ui/tests/Dashboard/dashboardApplication.test.ts
ui/tests/Flows/flows.test.ts

Step property was hardcoded to 2000000, which creates an interval of about 33 mins.
Grafana makes use of the `maxDataPoints` property which is tied to pixel width: _"The default value is the width (or number of pixels) of the graph, because you can only visualize as many data points as the graph panel has room to display."_
This PR grabs the width of the chart using the Chart.js chartArea property, then calculates the step with the formula `Math.floor((endTime - startTime) / maxDataPoints)`. Time is in ms here.  This formula is the same used in the grafana plugin.
- https://opennms.atlassian.net/browse/HS-1833

HS-1833: Fix steps for application series query

---

alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/AlertTestSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/BackgroundSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/EventSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/MonitorPolicySteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/NodeTestSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/TagTestSteps.java
alert/src/test/java/org/opennms/horizon/alertservice/stepdefs/TenantSteps.java
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature
alert/src/test/resources/org/opennms/horizon/alertservice/monitor-policy.feature
alert/src/test/resources/org/opennms/horizon/alertservice/node.feature
alert/src/test/resources/org/opennms/horizon/alertservice/tag.feature
alert/src/test/resources/org/opennms/horizon/alertservice/threshold.feature
parent-pom/pom.xml

This PR is intended to precede the actual changes for HS-1485; I figure that it might be easier to review & merge this PR separately. 
The scope of this PR is the alert service cucumber tests. The major changes are that:
- Many steps have been updated remove explicit references to the `tenantId`.
- Step classes have been streamlined by removing dead and duplicated code.
- Some scenario and step descriptions have been reworded to reduce verbosity.
No tests have been added or removed. This refactoring is necessary with the upcoming changes. Previously, on each scenario many duplicates of all of a tenant's alert conditions were created, for each policy specified in a background step. This means that an event would generate way too many alerts for duplicate policies that probably should not …

HS-1485: Refactor Alert Service Cucumber Tests

---

ui/src/components/Common/CollapsingCard.vue
ui/src/components/Common/ItemPreview.vue
ui/src/components/Common/commonTypes.ts
ui/src/components/Welcome/WelcomeSlideOne.vue
ui/src/components/Welcome/WelcomeSlideThree.vue
ui/src/components/Welcome/WelcomeSlideTwo.vue
ui/src/store/Views/welcomeStore.ts

We've addressed a variety of small design and copy updates for the welcome guide in this PR. The changes are as follows:
- https://opennms.atlassian.net/browse/HS-1841
* ~~[ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~ (style updates only)

HS-1841: Addressing UX/Design Feedback for Onboarding Guide

---

Tiltfile
tilt-jaeger-values.yaml

- Tilt: Reduce memory requirements for Jaeger
- Tilt: Allow more time download container images for Helm charts

Tilt: Allow more time download container images for Helm charts, reduce memory requirements for Jaeger

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertServiceImpl.java

I noticed that this method call is wrong. I'm not sure we ever create and destroy this `@Component` multiple times, but regardless, if we do, the correct method should be called.
- https://opennms.atlassian.net/browse/HS-1862

HS-1862: Fix delegated method call

---

ui/src/components/Inventory/InventoryTextAnchorList.vue
ui/src/main.ts
ui/src/store/Views/welcomeStore.ts

Keycloak uses URL fragments to keep track of items in localStorage. VueJS's router is incompatible with how Keycloak does this, which causes the fragments to stick around and accumulate. When the URL gets long enough it causes the nginx ingress to return 502 errors.
This is a workaround that fixes the issue. Keycloak needs to be fully initialized before the `@/router` file is imported anywhere - in main.ts the import was moved to the onReady callback, but it also needed to be changed in welcomeStore since it's imported in App.vue. 
- https://opennms.atlassian.net/browse/HS-1654

HS-1654: Fix extra URL fragments caused by an incompatibility between Keycloak and VueJS router

---

ui/src/components/Common/ItemPreview.vue

We added a new piece of text to the bottom of our device preview on the Welcome Guide, but we did not account for when that box is in a preview/loading state (the new text showed up). We don't want it to show up until loading is done, which is what this PR fixes.
- https://opennms.atlassian.net/browse/HS-1841
* ~~[ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~
* ~~[ ] Notify documentation team of any changes to names of screens or features (affects URLs).~~

HS-1841: Followup Fix

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/CucumberHooks.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/UiCucumberRunnerTest.java
test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/InventoryPage.java
test-automation/ui-tests/src/test/java/testcontainers/MinionContainer.java

Making some of the UI test env vars optional to allow more versatility in the testing environment.
- https://opennms.atlassian.net/browse/HS-1866

Make some env vars optional for the UI tests

---

ui/src/store/Views/welcomeStore.ts

`useRouter` only works in Vue components, not stores like welcomeStore. This caused an error when the application tried to show the welcome screen. This PR fixes the error.
- https://opennms.atlassian.net/browse/HS-1654

HS-1654: Fix router being undefined in welcomeStore

---

ui/src/store/Views/nodeStatusStore.ts
ui/tests/store/Views/nodeStatusStore.test.ts

Time range is listed as optional in GQL playground, but looks like it's required somewhere on the BE.
Uses the last 7 days because that's the maximum range the user can filter on the flows page.
- https://opennms.atlassian.net/browse/HS-1843

HS-1843: Add time range for exporters query

---

charts/lokahi/templates/opennms/minion-gateway/minion-gateway-deployment.yaml

We're getting this in dev, so temporarily disable for now while we research:
Liveness probe failed: HTTP probe failed with statuscode: 502
Readiness probe failed: HTTP probe failed with statuscode: 502
- https://opennms.atlassian.net/browse/BTO-687

BTO-687: temporarily disable probes for minion-gateway

---

charts/lokahi/templates/opennms/minion-gateway/minion-gateway-deployment.yaml

Re-enable minion gateway readiness and liveness probes.
- https://opennms.atlassian.net/browse/BTO-687

BTO-687-re-enable-minion-gateway-health-checks

---

events/persistence/src/main/java/org/opennms/horizon/events/persistence/mapper/EventMapper.java
rest-server/src/main/java/org/opennms/horizon/server/mapper/EventMapper.java
ui/src/components/NodeStatus/EventsTable.vue

A node's associated events didn't have values populated for `id` and `time` in the UI.  These now work.
EDIT: In a team discussion, we decided on removing `id` and `node id` fields.
- https://opennms.atlassian.net/browse/HS-1810
No special remarks.

HS-1810: Events: Adjust fields displayed in UI

---

Tiltfile
alert/pom.xml
alert/src/main/resources/application.yaml
alert/src/test/resources/org/opennms/horizon/alertservice/alert.feature
charts/lokahi/templates/opennms/alert/alert-deployment.yaml
charts/lokahi/templates/opennms/api/api-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-verifier/minion-certificate-verifier-deployment.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
events/main/src/main/resources/application.yml
inventory/main/src/main/resources/application.yml
metrics-processor/main/src/main/resources/application.yml
minion-certificate-verifier/main/pom.xml
minion-certificate-verifier/main/src/main/resources/application.yaml
notifications/pom.xml
notifications/src/main/resources/application.yml
rest-server/pom.xml
rest-server/src/main/resources/application.yml

The main idea is to enable Prometheus via Actuator for all those components that don't have it enabled. The reason is to ensure we have basic metrics available, particularly JVM memory usage, as that would help estimate how much heap memory we would need when running Lokahi in Kubernetes.
There were some changes to ensure the Health Checks are enabled, and based on my research for Prometheus, I homologized the management configuration for all the services. We could remove some unnecessary content for the Alerts Component, and I verified that the solution still works as expected.
Also, the Security features for SpringBoot and SpringSecurity were enabled for the Notifications Component, although not used. I removed those dependencies to simplify things because the actuator already works …

HS-1884: Enable Prometheus via Actuator on missing components.

---

charts/lokahi/templates/keycloak/keycloak-deployment.yaml

Keycloak has the metrics engine enabled, but we're not collecting stats by default. This PR enables that via Prometheus annotations (like the rest of the services).
- https://opennms.atlassian.net/browse/BTO-753

BTO-753: Collect Prometheus stats from Keycloak.

---

metrics-processor/main/pom.xml
notifications/pom.xml
parent-pom/pom.xml
rest-server/pom.xml

Reverts OpenNMS-Cloud/lokahi#1348
This PR broke the GraphQL API. It seems like it was permissive with type checking (e.g. would accept an Integer for a String input) but more strict (throwing errors) with the PR.

Revert "BTO-736: Enable JSON logging and upgrade Spring Boot to 3.1.1"

---

.github/actions/jib-maven-sonar/action.yml
.github/workflows/base-image-update.yml
minion/assembly/src/main/resources/etc/org.opennms.core.ipc.grpc.client.cfg
minion/assembly/src/main/resources/etc/org.opennms.horizon.minion.ignite.worker.cfg
minion/docker-assembly/src/main/docker/app/Dockerfile
minion/docker-assembly/src/main/docker/entrypoint/entrypoint.sh
minion/minion-grpc/grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml

- BTO-615: minion: Update default env vars in Dockerfile
- GitHub workflows: Use "jq -r" instead of sed to strip quotes.
- Minion: Move defaults from the Dockerfile to the resources/blueprint
This reduces the number of environment variables that are needed to be passed to Docker to 1: the password.
Here's what I was able to use to connect to production:
```
docker run --rm \
-p 162:1162/udp \
-p 9999:9999/udp \
-e GRPC_CLIENT_KEYSTORE_PASSWORD='<password>' \
--mount type=bind,source="$(pwd)/default-certificate (5).p12",target="/opt/karaf/minion.p12",readonly \
localhost:62186/opennms_lokahi-minion:tilt-build-1690391803
```
Follow-on work:
1. After this is merged **and** we have a release made so that `opennms/lokahi-minion:latest` is updated, we can update the UI. I'll add another PR for …

BTO-615: Minimize required Docker env vars

---

tilt-helm-values.yaml

The original work for BTO-707 included adding reasonable resource requests and limits for all the components. To avoid issues with Tilt, I removed the requests and limits for the Alert and Metrics Processor components to be consistent with their siblings.
- https://opennms.atlassian.net/browse/BTO-707

BTO-707(Tilt): Remove resources for alerts and metrics processor.

---

ui/src/store/Views/monitoringPoliciesStore.ts
ui/tests/MonitoringPolicies/monitoringPolicies.test.ts

The Monitoring Policy form will be automatically populated with a `default` tag. The user may remove the `default` tag and/or add different tags.
[screencast-localhost_3009-2023.08.08-11_36_43.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/81ec7e41-1a50-462b-8974-9784022a547d)
- https://opennms.atlassian.net/browse/HS-1896

LOK-1896: Populate new MP form with default tag

---

.github/workflows/tilt.yaml
Tiltfile
install-local/generate-and-sign-certificate.sh
install-local/install-local.sh
install-local/load-or-generate-secret.sh
tools/ssl-check.sh

- Run tools/ssl-check.sh in Tilt
- ssl-check.sh: remove effective no-op of '2>&1' before '> /dev/null'
- Allow specifying arbitrary kubectl options in SSL tools
- Tilt/ssl-check.sh: Run HTTP checks separately after ingress is up
- ssl-check.sh: also retry minion check
- tilt ci: Make sure necessary names are in /etc/hosts
- ssl-check.sh: connect to 127.0.0.1 to reach minion
- https://opennms.atlassian.net/browse/BTO-784

Tilt: ssl-check.sh at startup and improve context/namespace handling

---

build-tools/basic/run-cluster.sh
charts/lokahi/templates/_helpers.tpl
charts/lokahi/templates/grafana/grafana-deployment.yaml
charts/lokahi/templates/keycloak/keycloak-deployment.yaml
charts/lokahi/templates/opennms/alert/alert-deployment.yaml
charts/lokahi/templates/opennms/api/api-deployment.yaml
charts/lokahi/templates/opennms/datachoices/datachoices-deployment.yaml
charts/lokahi/templates/opennms/events/events-deployment.yaml
charts/lokahi/templates/opennms/inventory/inventory-deployment.yaml
charts/lokahi/templates/opennms/metricsprocessor/metricsprocessor-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-manager/minion-certificate-manager-deployment.yaml
charts/lokahi/templates/opennms/minion-certificate-verifier/minion-certificate-verifier-deployment.yaml
charts/lokahi/templates/opennms/minion-gateway/minion-gateway-deployment.yaml
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
charts/lokahi/templates/opennms/notification/notification-deployment.yaml
charts/lokahi/templates/opennms/ui/ui-deployment.yaml
charts/lokahi/values.yaml
install-local/install-local-opennms-lokahi-custom-images-values.yaml
install-local/install-local.sh

- [Helm chart: allow setting the image version in one place](https://github.com/OpenNMS-Cloud/lokahi/pull/1402/commits/15c2f4a6fcc1742a8823ac41a1f2c6d951f2aceb) 
- [Use new global image repository/tag values](https://github.com/OpenNMS-Cloud/lokahi/pull/1402/commits/7ea566f157bd9c7037813a96571225592f170df3)
- [Helm: Make sure templates are globally unique](https://github.com/OpenNMS-Cloud/lokahi/pull/1402/commits/9306a526f4c66b327cb3692ae0b8576acd7179e8) 
- [Helm: make sure the include for lokahi.deployment.env is last in env](https://github.com/OpenNMS-Cloud/lokahi/pull/1402/commits/88189ea1c6550221afcf95fe8354454149daa80f) 
Also had to tweak how the existing "deployment.env" define is
included since it how has to call the new "lokahi.image" define.
You can only pass one set of values …

Helm chart: allow setting the image version in one place

---

charts/lokahi/templates/opennms/minion-gateway/minion-gateway-deployment.yaml
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
charts/lokahi/values.yaml
tilt-helm-values.yaml

I discovered that the topology reconciliation on Ignite doesn't work well, and enforcing `-Djava.net.preferIPv4Stack=true` helps. I verified via Tilt that changes in the number of replicas are now taken adequately by Ignite (see the Jira issue for more details).
As a bonus, I reduced `-XX:MaxRAMPercentage=` from 50 to 40, as there are 4 Regions on Ignite that could take up to 2GB off-heap, so we reduce the actual heap to keep the current memory limit but be able to fulfill the worst case scenario.
- https://opennms.atlassian.net/browse/BTO-788

BTO-788: Avoid Ignite Topology issues preferring IPv4

---

tilt-helm-values.yaml

Unfortunately, `fb-dev` demonstrated that the Minion Gateway is not ready for multiple replicas (we need more time to understand how to configure and use Ignite), so I'm restoring the replicas to one for Tilt (as it was before).

BTO-788: Restore Minion Gateway replicas to 1

---

metrics-processor/main/src/main/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorSnmpResponseProcessor.java
metrics-processor/main/src/test/java/org/opennms/horizon/tsdata/collector/TaskSetCollectorSnmpResponseProcessorTest.java
metrics-processor/timeseries/src/main/java/org/opennms/horizon/timeseries/cortex/CortexTSS.java

Store all metrics for a given collection at once.
This avoids multiple writes to Cortex
- https://opennms.atlassian.net/browse/LOK-1949

LOK-1949: Store all metrics for a given collection at once

---

test-automation/integration-tests/src/main/java/org/opennms/horizon/it/MonitoringPolicyTestSteps.java
test-automation/integration-tests/src/main/resources/org/opennms/horizon/it/monitoring-policy.feature

[]() The issue has been caused by sending snmp traps from a snmp node before the node(a test container) is fully started. The fix is to insert a waiting period of 20 seconds after the node was started. The test scenarios have also been refactored as a result of the fix.
- https://opennms.atlassian.net/browse/LOK-1979

Fixed the issue where monitoring policy tests failed intermittently.

---

Tiltfile
alert/src/main/resources/application.yaml
charts/lokahi/templates/_helpers.tpl
charts/lokahi/templates/opennms/minion/minion-deployment.yaml
datachoices/src/main/resources/application.yml
events/main/src/main/resources/application.yml
inventory/main/src/main/resources/application.yml
metrics-processor/main/src/main/resources/application.yml
minion-certificate-verifier/main/src/main/resources/application.yaml
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
minion-gateway/main/src/main/resources/application.yaml
minion/assembly/src/main/resources/etc/org.ops4j.pax.logging.cfg
notifications/src/main/resources/application.yml
rest-server/src/main/resources/application.yml
tilt-helm-values.yaml

- Allow setting the Minion log level in the Lokahi chart
- Tilt: otel: add user and location attributes for minion-gateway ingress
- Log when the sink streaming stream is completed
- Tilt: cleanup suggested by Gerald that I missed on a previous PR
- Tilt: add a button to restart the Minion
- Helm: Minion: give 10 attempts at status check
- Configure health checks to always return health details
- Fix 'env' values on individual services

Small minion cleanups and some other small improvements

---

ui/src/services/authService.ts

Removing the refresh_token from the logout call as per Jason and I's conversation.
- https://opennms.atlassian.net/browse/LOK-1691
* ~~[ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~
* ~~[ ] Notify documentation team of any changes to names of screens or features (affects URLs).~~

LOK-1691: Logout Issue Attempt #2

---

ui/src/components/Dashboard/DashboardApplications.vue
ui/src/containers/Flows.vue
ui/tests/Dashboard/dashboardApplication.test.ts

The initial flows date filter is set to `Today`. Loading the dashboard will change it to `24 hours`. Unmounting the dashboard was incorrectly attempting to reset it to `Today`. This change just fixes the reset.
- https://opennms.atlassian.net/browse/HS-2009

LOK-2009: Fix the reset of flows store state

---

ui/src/components/Common/TextRadioButtons.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesSaveButtons.vue
ui/src/store/Views/monitoringPoliciesStore.ts

Let's a user click on a rule, then click on the delete icon to remove that rule from the policy. Because the user must also save the policy after updating the rules, I have made a small change to make sure the Save Policy button always shows (previously the user had to select a rule before it appeared).
[screencast-localhost_3009-2023.08.29-12_58_20.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/9bf43eaf-f36d-44ac-a8ae-05abb53faf5f)
- https://opennms.atlassian.net/browse/HS-2005

LOK-2005: Add ability to delete rule from monitoring policy

---

ui/src/components/Alerts/AlertsSeverityCard.vue
ui/src/components/Common/EmptyList.vue
ui/src/components/Dashboard/DashboardCard.vue
ui/src/components/Discovery/DiscoveryListCard.vue
ui/src/components/Locations/LocationsList.vue
ui/src/components/Locations/LocationsMinionsList.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesCard.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesCardEventConditionTable.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesCardThresholdConditionTable.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesExistingItems.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
ui/src/containers/Alerts.vue
ui/src/containers/Discovery.vue
ui/src/containers/Flows.vue
ui/src/styles/mixins.scss
ui/src/styles/vars.scss

There were inconsistencies with the border and border-radius for some of the major surface containers.
This PR makes things consistent by using a 4px border-radius and the `$border-on-surface` feather var.
ex:
- https://opennms.atlassian.net/browse/HS-1699

LOK-1699: Fix surface border & border-radius

---

parent-pom/pom.xml

- https://opennms.atlassian.net/browse/LOK-2042

LOK-2042: In CI/CD, use current timestamp for Jib docker images

---

ui/package.json
ui/src/components/Layout/Menubar.vue
ui/yarn.lock

Updates the vue-keycloak package and uses the logout function that it offers.
- https://opennms.atlassian.net/browse/HS-1691

LOK-1691: Use logout from latest vue-keycloak package

---

ui/package.json
ui/src/dtos/discovery.dto.ts
ui/yarn.lock

Fixes the IP addresses input by testing against the same reg expressions previously used.
[screencast-localhost_3009-2023.09.13-14_51_05.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/2b86da51-34e3-4edb-9c36-f17a1e19ca6a)
- https://opennms.atlassian.net/browse/LOK-2050

LOK-2050: Fix active discovery cidr input

---

rest-server/src/main/java/org/opennms/horizon/server/utils/JWTValidator.java

Add the "sub" (subject) from the JWT claim as a span attribute, `jwt.claim.sub` (we kinda just guessed at what kind of a name might make sense).
- https://opennms.atlassian.net/browse/BTO-870

BTO-870: gather per-user statistics from rest-server

---

ui/src/components/Flows/LineChart.vue
ui/src/components/Flows/TableChart.vue
ui/src/components/utils.ts
ui/src/containers/Flows.vue
ui/tests/Utils/common.test.ts

We had a request to add the string ` /sec` to the flows line chart to indicate the number is a rate, meaning data over time, versus just data. This is tied in with an additional PR to look into the data in the BE, to make sure the rate is actually per seconds.
This was a joint effort between Scott and Mike. Teamwork!
- https://opennms.atlassian.net/browse/HS-1861
* ~~[ ] Includes [appropriate tests.](https://github.com/OpenNMS-Cloud/lokahi/wiki/Test-Strategy)~~

HS-1861: Adding /sec to charts

---

alert/src/main/resources/db/changelog/hs-0.1.0/data/system_tenant_default_policy.xml

Alert condition was not queried with tenant_id earlier which resulted in multiple rows.
Migration involves these steps.
1. Removes earlier changeset
2. Delete alert definitions that are already present.
3. Create new changeset with updated name and adding where clause for all alert conditions
- https://opennms.atlassian.net/browse/LOK-1834

LOK-1834: Fix liquibase update for alert definition

---

alert/src/main/java/org/opennms/horizon/alertservice/service/AlertEventProcessor.java
events/traps/src/main/java/org/opennms/horizon/events/traps/EventFactory.java

A quick fix to remove the `<p>` tags from alert details 
- https://opennms.atlassian.net/browse/LOK-1874
N/A
A quick test showing what the alert description looks like for SNMP cold start:

LOK-1874: Alerts: Alert Detail for SNMP Cold start contains <p> tags

---

.gitignore
charts/lokahi/templates/opennms/api/api-deployment.yaml
rest-server/src/main/java/org/opennms/horizon/server/config/WebFluxConfig.java
rest-server/src/main/resources/application.yml
tilt-helm-values.yaml

Prior to https://github.com/OpenNMS-Cloud/lokahi/pull/1449, the graphql endpoint would allow CORS requests. When it was replaced, this behaviour was not carried over, causing an interruption in frontend development. Generally it is better to not allow CORS by default given that only our UI is making requests, and via the same origin. My fix here is to provide the configuration option to expose this option via configuration.
This is how you can provide helm chart values without having git tracking them:
In `tilt-config.json`:
```json
{
"devmode": [],
"values": ["./tilt-helm-values-local.yaml"]
}
```
In `tilt-helm-values-local.yaml`:
```yaml
OpenNMS:
API:
CorsAllowed: true
```
- https://opennms.atlassian.net/browse/LOK-2079

LOK-2079: Re-add ability to make CORS requests

---

rest-server/src/main/java/org/opennms/horizon/server/model/inventory/SnmpInterface.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/SnmpInterfaceAdminStatus.java
rest-server/src/main/java/org/opennms/horizon/server/model/inventory/SnmpInterfaceOperatorStatus.java
rest-server/src/test/java/org/opennms/horizon/server/service/flows/GrpcFlowServiceTest.java

When displaying node interfaces, the admin and operator status will be the name (instead of the ordinal value).
- https://opennms.atlassian.net/browse/LOK-1886
N/A
In this example, instead of displaying `1` the user will now see `UP`:

LOK-1886: Inventory: Node: Display interface operator status name instead of ordinal

---

ui/src/components/Common/DeleteConfirmationModal.vue
ui/src/components/Locations/LocationsCertificateDownload.vue
ui/src/store/Views/locationStore.ts

Adds a confirmation for revoking/regenerating the cert.
Adds a minor tweak to repurpose the DeleteConfirmationModal for this.
[screencast-localhost_3009-2023.09.27-13_53_33.webm](https://github.com/OpenNMS-Cloud/lokahi/assets/8680122/25605d85-c0a5-431a-ab5f-18d42dba231b)
- https://opennms.atlassian.net/browse/LOK-2094

LOK-2094: Add confirmation modal for revoke/regen btn

---

ui/src/components/Discovery/DiscoveryMetaInformation.vue
ui/src/dtos/discovery.dto.ts
ui/src/store/Views/discoveryStore.ts
ui/src/types/discovery.d.ts

Since the discovery page refactor, the Azure payload was being sent to the wrong endpoint. This fixes the call, and also fixes the `subscriptionId` property.
- https://opennms.atlassian.net/browse/LOK-2132

LOK-2132: Fix azure call

---

.github/workflows/release.yml
minion/docker-assembly/pom.xml
minion/docker-assembly/src/main/docker/app/Dockerfile
minion/minion-grpc/grpc-client/src/main/java/org/opennms/horizon/minion/grpc/channel/OkHttpChannelBuilderFactory.java
minion/minion-grpc/grpc-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
minion/minion-grpc/grpc-client/src/test/java/org/opennms/horizon/minion/grpc/channel/OkHttpChannelBuilderFactoryTest.java

* Adds a properties file containing version details from the build using https://github.com/git-commit-id/git-commit-id-maven-plugin (plus a few of our own that are added).
* Uses this properties file to add details to the User-agent header sent upstream by OkHttp.
Example user-agent:
```
OpenNMS_Lokahi_Minion/e02572f (built 2023-10-01T01:23:24Z; branch jira/LOK-2043) Java/17.0.8.1 (OpenJDK 64-Bit Server VM/17.0.8.1+1; Eclipse Adoptium) Linux/5.15.49-linuxkit-pr (amd64) grpc-java-okhttp/1.54.1
```
* ~~Update container labels (and remove anything we don't plan to support) -- see https://github.com/opencontainers/image-spec/blob/main/annotations.md~~ -- leaving this one for later, because I'm not sure what we'll want to have. Although this is related to the information we store inside the …

LOK-2043: Add version information to gRPC requests from the minion

---

test-automation/ui-tests/src/test/java/org/opennms/horizon/systemtests/pages/WelcomePage.java

Sometimes the initial page will be empty in the test environment. This will try to force a refresh to attempt to get it to load.
- https://opennms.atlassian.net/browse/BTO-844

Refresh initial page after login if it stays empty.

---

ui/src/containers/Discovery.vue
ui/src/store/Views/discoveryStore.ts

Adds the initial discovery landing screen. Subsequent screen will require additional BE work.
- https://opennms.atlassian.net/browse/LOK-2051

LOK-2051: Add initial discovery landing screen

---

ui/src/components/Locations/LocationsCertificateDownload.vue

All the code for the cert dates on the locations page has been removed, as it is uncertain when/if it will be used in the future.
The new box looks like so
- https://opennms.atlassian.net/browse/LOK-2026

LOK-2026: Remove hardcoded cert dates

---

inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/TagGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/discovery/AzureActiveDiscoveryGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/MonitoringSystemService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/TagService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/MonitoringSystemServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/NodeServiceTest.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/TagServiceTest.java

Flaws
Mutations
* discoveryByNodeIds: partial match will start scans silently — DONE in LOK-1925
* addTagsToNodes: No real node validation but likely throws NPEs when a node id does not exist  — DONE in LOK-1925
* removeTagsFromNodes: No real node validation but likely throws NPEs when a node id does not exist  — TagService getNode & getTag all have empty checking
* createMonitorPolicy: Downstream does not validate that there is no id in request, could potentially be set by the client
* createAzureActiveDiscovery:
* Downstream does not validate that there are no ids in request, could potentially be set by the client — no id field in request
* Does not validate that locationId exists  — DONE in LOK-1925
* revokeMinionCertificate: Downstream does not validate that location is valid — DONE …

LOK-1929: fix graphql flaws

---

ui/src/components/Discovery/DiscoveryListCard.vue
ui/src/containers/Discovery.vue
ui/src/store/Queries/discoveryQueries.ts

Right now if we have only passive type discoveries or only active type discoveries, the frontend will make a tags call for both types. This fixes things so that it will only make the tags call for the type which has available discoveries.
Also fixes the selected/highlighted issue when both a passive and active discovery have the same id.
- https://opennms.atlassian.net/browse/LOK-2171

LOK-2171: Fix discovery page call for tags when no discovery available

---

inventory/main/src/main/java/org/opennms/horizon/inventory/repository/IpInterfaceRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/IpInterfaceService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/taskset/response/ScannerResponseService.java
inventory/main/src/test/java/org/opennms/horizon/inventory/service/IpInterfaceServiceTest.java
metrics-processor/flows/src/main/java/org/opennms/horizon/flows/processing/DocumentEnricherImpl.java
metrics-processor/flows/src/test/java/org/opennms/horizon/flows/processing/DocumentEnricherTest.java

This PR will skip node enrichment if anything happen during grpc call to inventory rather than lost that flow record.
It also make sure findByIpAddressAndLocationIdAndTenantId only return single record. Priority return snmpPrimary first then first record.
- https://opennms.atlassian.net/browse/LOK-2055

LOK-2055: ignore node enrichment if ip lookup fail

---

Tiltfile

I added links to the following resources in Tilt for easier reference locally:
- Keycloak: Admin Console & Welcome Page
- BFF: The GraphQL endpoint and the GUI Playground
- Postgres: The JDBC URL with admin user
- https://opennms.atlassian.net/browse/LOK-1899

LOK-1899: Add links to tiltfile

---

docs/modules/operation/pages/get-started/discovery/introduction.adoc
docs/modules/operation/pages/get-started/discovery/passive.adoc
docs/modules/operation/pages/get-started/policies/create.adoc
docs/modules/operation/pages/get-started/policies/manage.adoc

LOK-2086: Doc: Passive Discovery: Remove mention of syslog - removed mention of syslog in the discovery section of the docs.
LOK- 1907: Doc: Monitoring Policy: Deletion of monitoring policies and rules within a policy - added information about deleting policies, including that you cannot delete the default policy.
LOK-2086: Doc: Passive Discovery: Remove mention of syslog - removed mention of syslog in the discovery section of the docs.
LOK- 1907: Doc: Monitoring Policy: Deletion of monitoring policies and rules within a policy - added information about deleting policies, including that you cannot delete the default policy.
- https://opennms.atlassian.net/browse/LOK-2086
- - https://opennms.atlassian.net/browse/LOK-1907

LOK-2086: Doc: Passive Discovery: Remove mention of syslog

---

notifications/src/main/resources/daily-digest.html.vm

This adds the template for the daily digest email. 
Values are to be populated later.
${date}
${currentYear}
${alerts}
${yesterday}
${change}
${recipient}
Tested with the EmailSender tool in the Portal project.
- https://opennms.atlassian.net/browse/LOK-2187
How it looks in Gmail
How it looks in Outlook

LOK-2187: Add template for daily email

---

rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java

Revert TopNNodes changes to debug timeout issue
- https://opennms.atlassian.net/browse/LOK-2188

LOK-2206: Return empty list for TopNNodes

---

docs/modules/operation/pages/visualizations/introduction.adoc

LOK-2154: Doc: Insight Dashboard Updates: Top Nodes - added documentation to the insights dashboard section regarding the top nodes. Also added bullet on node reachability, which was missing from the docs.
Added documentation to the insights dashboard section regarding the top nodes. Also added bullet on node reachability, which was missing from the docs. Updated because product is updated, and UI is different.
- https://opennms.atlassian.net/browse/LOK-2154

LOK-2154: Doc: Insight Dashboard Updates: Top Nodes

---

ui/src/components/Locations/LocationsCertificateDownload.vue

Just removes the input/copy which displays the cert password. This is no longer needed.
- https://opennms.atlassian.net/browse/LOK-2210

LOK-2210: Remove display/copy of cert password on locations

---

ui/src/components/Alerts/AlertsSeverityCard.vue
ui/src/components/Alerts/AlertsSeverityFilters.vue

Prior to LOK-2091, it looks like the values used to create the `AlertSeverityFilters` component were a filtered array of `Severity` values:
```ts
const severitiesDisplay = ['critical', 'major', 'minor', 'warning', 'indeterminate']
const severities = Object.values(Severity).filter((s) => severitiesDisplay.includes(s.toLowerCase()))
```
It wasn't obvious, but the casing mattered; the `fetchCountAlerts` query, which these severities flow through, requires the enum value rather than a case-insensitive string. I've reverted the array to contain `Severity` types rather than strings, but in a more declarative way.
- https://opennms.atlassian.net/browse/LOK-2203

LOK-2203: Restore usage of enum types

---

ui/src/components/Inventory/InventoryTagModal.vue

Fixes so that tags only delete when clicking on the actual icon.
- https://opennms.atlassian.net/browse/LOK-2223

LOK-2223: Fix tag deletion

---

events/persistence/src/main/resources/db/changelog/hs-0.1.0/tables/eventTenantKey.xml
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/monitoringPolicyTenantKey.xml
notifications/src/main/resources/db/changelog/hs-0.1.0/tables/pagerDutyTenantKey.xml

Distributing the tables will lock in the distribution column/index types. As we want to change these in the future we will hold off distributing until then.
- https://opennms.atlassian.net/browse/LOK-2169
The changesets appear to work even after modifying them. The checksum / all setting appears to allow this but we should look at removing it as the checksum provides valuable protections.

Remove custom sql to distrubute tables

---

parent-pom/pom.xml
rest-server/pom.xml
rest-server/src/main/java/org/opennms/horizon/server/service/graphql/BffDataFetchExceptionHandler.java

- Bumped version of opentelemetry to `1.32.0` (the latest)
- Added an explicit span to `BffDataFetchExceptionHandler`
**Explanation:** Upon diving deeper into the issue, the span that is marked as erroneous comes from the java-agents graphql instrumentation. It seems that the error is reported as a `graphql.ErrorType#DataFetchingException`, which despite its type, is _not actually_ an exception, but rather a classifier that indicates that a graphql data fetch was aborted due to an exception (as opposed to a validation error, being aborted, etc). [Otel source reference](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3b77cc4b2de90ca821d53234e76ea8f279cfc34f/instrumentation/graphql-java-12.0/library/src/main/java/io/opentelemetry/instrumentation/graphql/v12_0/OpenTe …

LOK-2204 open telemetry exception recording

---

.github/workflows/release.yml

MATTERMOST_WEBHOOK_URL secret has already been added to the repo (from `Mattermost DevOps/SRE Notifications Webhook` in bitwarden).
- https://opennms.atlassian.net/browse/LOK-2181

LOK-2181: Add Mattermost notification when release is completed.

---

charts/lokahi/scripts/opennms/minion/prepareLocationAndCerts.sh
minion/assembly/src/main/resources/etc/org.opennms.core.ipc.grpc.client.cfg

- LOK-2249: Make sure setup-env.sh fails cleanly on macOS with old bash
- Fix assembly properties in the minion
- https://opennms.atlassian.net/browse/LOK-2249

LOK-2249: Make sure setup-env.sh fails cleanly on macOS with old bash and fix some assembly properties in the minion

---

build-tools/basic/mk-docker-images.sh
inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/CucumberRunnerIT.java
parent-pom/pom.xml

- Use profiles with arch activation to set default Docker platforms
- We no longer have a development target for the ui container
- inventory CucumberRunnerIT: use v1.12.1 version of tkpd/gripmock with arm64 support

Improve Docker container arm64 build support

---

charts/lokahi/values.yaml
install-local/install-local.sh
test-automation/integration-tests/src/main/java/org/opennms/horizon/it/KeycloakTestSteps.java
tilt-helm-values.yaml

- Add a new GitHub workflow to test 'tilt ci'
- external-it job: Pull namespace into an env variable
- Fix URL in pull request template: Jira is now in Atlassian Cloud
- Move ingress-nginx to Helm chart and version match dev environment
- Upgrade ingress-nginx to controller 1.8.0, Helm chart 4.7.0
- Increase nginx error log level to info so we see SSL handshake errors
- opennms-minion-gateway ingress: Add missing ingressClassName
- Disable built-in ingress, assume it is provided externally
- Improve failure messaging with 'set -e'
- XXX temp: add --debug

HS-1685: install-local.sh: use nginx from helm chart instead of built-in

---

minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/grpc/common/TenantIDGrpcServerInterceptor.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/OpennmsGrpcServer.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/OutgoingMessageFactory.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/OutgoingMessageHandler.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/RpcConnectionTracker.java
minion-gateway/ipc-grpc-server/src/main/java/org/opennms/horizon/shared/ipc/grpc/server/manager/adapter/MinionRSTransportAdapter.java
minion-gateway/main/pom.xml
minion-gateway/main/src/main/java/org/opennms/miniongateway/MinionGatewayMain.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/GrpcServerConfig.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/GrpcTwinPublisherConfig.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/server/RpcConnectionTrackerImpl.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/GrpcTwinPublisher.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TaskSetTwinMessageProcessor.java
minion-gateway/main/src/main/java/org/opennms/miniongateway/grpc/twin/TwinRpcHandler.java
tilt-helm-values.yaml

- BTO-783: Add identity attributes to MinionToCloudMessage streaming and message spans
- BTO-783: Add tracing details for CloudToMinionRPC dispatch calls
- BTO-783: Add tracing for CloudToMinionMessage
- BTO-783: Add tracing for MinionToCloudRPC
- Tilt: include minion-gateway messages in tracing spans by default
- Don't use GlobalOpenTelemetry.get().getTracer anymore
- remove unused import
We should now have tracing spans created for **all** Minion<->Minion-gateway communications:
* CloudToMinionMessage
* MinionToCloudMessage
* CloudToMinionRPC
* MinionToCloudRPC
Streaming gRPC calls (the first two in the list above) are a little interesting, because by default, the OpenTelemetry gRPC instrumentation only adds spans at the *connection* level. These are both long-lived streams, and that …

BTO-783: minion-gateway: flesh out traces for all connection types and streaming messages including identity attributes

---

rest-server/src/main/java/org/opennms/horizon/server/service/metrics/QueryService.java
rest-server/src/test/java/org/opennms/horizon/server/metrics/QueryServiceTest.java

QueryServiceTest.testTotalQuery computes its own start/end
values based on when it calls System.currentTimeMillis() and
QueryService.getQueryString also calls currentTimeMillis()
which will cause the expected result to be off on occasion:
QueryServiceTest.testTotalQuery:99 expected: <start=1703196215> but was: <start=1703196216>
Add another method signature to getQueryString so we can pass
in our value of 'end' from our test to ensure the comparisions
always pass. This succeded for > 1 million runs for me, where
before it would fail around 10k - 100k runs.

Fix intermittent off-by-one error in rest-service test

---

notifications/pom.xml
notifications/src/main/java/org/opennms/horizon/notifications/service/NotificationService.java
notifications/src/test/java/org/opennms/horizon/notifications/service/NotificationServiceImplTest.java

- We use 'user' everywhere else, so be consistent here, so we can find while searching.
- Add first test for tracing data -- in this case, that the tenant is set (as the "user" span attribute)

Tiny fix to tenant span attribute name

---

Tiltfile

Update tilt to use manual trigger instead of auto update for every small change.
- https://opennms.atlassian.net/browse/LOK-2270

LOK-2270: Update tilt to use manual trigger for all services

---

ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue

UI should prevent blank names being added to policy and rule names.
Names should be trimmed before sending to BE.
- https://opennms.atlassian.net/browse/LOK-2303

LOK-2303: Don't allow blank in Monitor policy and rule names

---

ui/src/containers/Discovery.vue
ui/src/dtos/discovery.dto.ts
ui/src/store/Views/discoveryStore.ts

Don’t allow blank names for ICMP/Passive/Azure discovery pages.
Save button shouldn’t appear if we have blank name.
Names should be trimmed before sending to BE.
- https://opennms.atlassian.net/browse/LOK-2301

LOK-2301: Don't allow blank names for discovery

---

ui/src/components/Inventory/InventoryIconActionList.vue
ui/src/components/Inventory/InventoryTabContent.vue
ui/src/containers/NodeDetails.vue
ui/src/containers/NodeStatus.vue
ui/src/router/index.ts
ui/src/store/Views/discoveryStore.ts

Reinstate the previous Node / Node Details page. However please note all functionality on that page should be present in the Node Status page, just in different tabs.
Added "info" icon to Inventory items to navigate to new Node Status. Add clickable Inventory node label which also navigates to the Node Status page. The "warning" icon navigates to the old node details page; updated the tooltip.
Once the new Node Status page is done, we should redirect `/node` to that, and remove the old node page.
Also, fixed linting issues.
- https://opennms.atlassian.net/browse/LOK-2315

LOK-2315: Reinstate previous Node page

---

ui/src/components/NodeStatus/NodeStatusTabContent.vue
ui/src/components/NodeStatus/NodeTags.vue
ui/src/containers/NodeStatus.vue
ui/src/store/Views/nodeStatusStore.ts

Use FeatherChipList to display tags (already there).
When user clicks "X" on a tag, remove it. Looks like this is in nodeMutations.ts, useNodeMutations / removeTagsFromNodes. Then refresh the data.
- https://opennms.atlassian.net/browse/LOK-2283

LOK-2283:Node Details: Tags component

---

inventory/docker-it/src/test/java/org/opennms/horizon/inventory/cucumber/steps/NodeStepDefinitions.java
inventory/docker-it/src/test/resources/org/opennms/horizon/inventory/node.feature
inventory/main/src/main/java/org/opennms/horizon/inventory/grpc/NodeGrpcService.java
inventory/main/src/main/java/org/opennms/horizon/inventory/repository/NodeRepository.java
inventory/main/src/main/java/org/opennms/horizon/inventory/service/NodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/GrpcNodeService.java
rest-server/src/main/java/org/opennms/horizon/server/service/grpc/InventoryClient.java
shared-lib/inventory/src/main/proto/nodeService.proto

Add countNodes API on Inventory & BFF
- https://opennms.atlassian.net/browse/LOK-2221

LOK-2221 :Added new Grpc Call for Node Count.

---

ui/src/components/NodeStatus/IPInterfacesTable.vue

Implement the Refresh button for the IP Interfaces table on the Node Status page.
Not sure there is any way to just refresh IP Interface info, so need to just re-fetch the node status data, something equivalent to:
const queries = useNodeStatusQueries()
queries.fetchNodeStatus()
(may or may not need await, don’t need it if this will fire in the background)
- https://opennms.atlassian.net/browse/LOK-2296

Node Details: IP Interfaces Refresh

---

ui/src/components/NodeStatus/EventsTable.vue

Enable Search on the Events component in the Node Status screen.
User can enter search term to search by. Should be a case-insensitive search which includes partial matches. The search will be implemented client-side and not call the back end; it will use data already stored in nodeStatusStore.node.events.
Can search by:
uei
ip_address
While we are not using BFF for this, a link is included below for reference on what kinds of searches we should support.
https://opennms.atlassian.net/browse/LOK-2352

LOK-2352: Events search

---

ui/src/constants/index.ts
ui/src/store/Views/nodeStatusStore.ts
ui/tests/store/Views/nodeStatusStore.test.ts

Flows is not yet fully implemented. The Node Status / Node Details pages were calling `findExporters` API, causing a snackbar error message to pop up all the time.
This disables that call for now.
- https://opennms.atlassian.net/browse/LOK-2333

LOK-2333: Suppress calling flows API until back end is implemented

---

ui/src/components/MonitoringPolicies/MonitoringPoliciesPolicyForm.vue
ui/src/components/MonitoringPolicies/MonitoringPoliciesRuleForm.vue
ui/src/store/Views/monitoringPoliciesStore.ts

Add validation for Monitoring Policy and Rule names to prevent blank or duplicate names.
Does a client-side check, if that fails, displays a friendly error message next to then input field and does not send an API request.
Should prevent "snackbar" errors from displaying (they occur when graphql API calls fail).
- https://opennms.atlassian.net/browse/LOK-2351

LOK-2351: Friendly error messages for new Monitoring Policy and Rules

---

ui/src/components/NodeStatus/SNMPInterfacesTable.vue

Enable Search on the SNMP Interfaces component in the Node Status screen.
Should be a case-insensitive search which includes partial matches on any of:
ifName
ifDescr
ifAlias
physicalAddr
The search will be implemented client-side and not call the back end; it will use data already stored in nodeStatusStore.node.snmpInterfaces.
One way to implement might be to create a search filter function, then apply it inside a computed property.
While we are not using BFF for this, a link is included below for reference on what kinds of searches we should support.
- https://opennms.atlassian.net/browse/LOK-2293

Node Details: SNMP Interfaces search

---

ui/src/components/NodeStatus/IPInterfacesTable.vue

Enable Search on the IP Interfaces component in the Node Status screen.
User can enter IP address or hostname to search by. Should be a case-insensitive search which includes partial matches. The search will be implemented client-side and not call the back end; it will use data already stored in nodeStatusStore.node.ipInterfaces.
One way to implement might be to create a search filter function, then apply it inside the ipInterfaces computed property.
While we are not using BFF for this, a link is included below for reference on what kinds of searches we should support.
- https://opennms.atlassian.net/browse/LOK-2297

Node Details: IP Interfaces search

---

ui/src/components/NodeStatus/EventsTable.vue

Implement the Refresh button on the Events table in the Node Status page. It should just make another call to the back end for data.
https://opennms.atlassian.net/browse/LOK-2355

LOK-2355: Events table refresh

---

ui/src/containers/NodeStatus.vue
ui/tests/NodeStatus/nodeStatus.test.ts

Add some initial unit tests for the Node Status page.
Add tests/NodeStatus/nodeStatus.test.ts and use inventory.test.ts as an example.
Ensure the main title and System Information title are present.
We will add more tests in the future, this is just to add the first one.
- https://opennms.atlassian.net/browse/LOK-2347

FE: Node Status: Add initial unit tests

---

ui/src/components/Locations/LocationsAddForm.vue
ui/src/components/Locations/LocationsEditForm.vue

For better tracking (and consistency with the rest of the UI), the “Save” labels on the locations screen should be updated:
Save Location (when user is saving a location)
Save Minion or Add Minion (when user is adding a Minion).
Right now, Pendo cannot distinguish these buttons, so we are unable to identify core events like saving a Minion or saving a location. 
https://opennms.atlassian.net/browse/LOK-1927

LOK-1927: Update button labels on screens

---

ui/src/store/Components/tagStore.ts

When managing tags on the Node Status page, you can add duplicate tags, which should not be allowed.
LOK-2345: Duplicate tag name for the same tenant Id exception - Muhammad Junaid
TO DO
is to fix this on the back end, but we should also do a check in the front end to not allow user to add a duplicate tag, if we already have that tag in our tagStore.
https://opennms.atlassian.net/browse/LOK-2375

LOK-2375: Don't add duplicate tags

---

ui/src/components/NodeStatus/SNMPInterfacesTable.vue

Have Refresh button on SNMP Interfaces re-fetch the node status data.
- https://opennms.atlassian.net/browse/LOK-2292

Node Details: SNMP Interfaces Actions and refresh

---

ui/tests/store/Views/nodeStatusStore.test.ts

FE unit tests for nodeStatusStore setNodeIdand updateNodeAlias
When setNodeId is called, make sure nodeStatusQueries.setNodeId is called with correct parameter and that nodeId value is set correctly
When updateNodeAlias is called, make sure mutations.updateNode is called with correct parameters
https://opennms.atlassian.net/browse/LOK-2383

FE: Unit tests: nodeStatusStore setNodeId, updateNodeAlias

---

ui/tests/store/Views/nodeStatusStore.test.ts

FE unit tests for nodeStatusStore downloadIpInterfacesToCsv
When downloadIpInterfacesToCsv is called, make sure nodeStatusQueries.downloadIpInterfaces and createAndDownloadBlobFile  are called with correct parameters 
- https://opennms.atlassian.net/browse/LOK-2384

Unit tests - nodeStatusStore downloadIpInterfacesToCsv

---

minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutionResultProcessorImpl.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponse.java
minion/plugins/plugins-api/src/main/java/org/opennms/horizon/minion/plugin/api/ServiceMonitorResponseImpl.java
minion/plugins/snmp-plugin/src/main/java/org/opennms/horizon/minion/snmp/SnmpMonitor.java

Service Monitor results contains a field named properties which is used to transport metrics gathered from the monitoring poll execution. Rename accordingly.
Starting point is ServiceMonitorResponseImpl. Rename the field properties to metrics. Find all usages of this field in the whole code-base and rename other usages, too. Be aware that this is named metrics in some places already. Check in modules minion, minion-gateway and metric-processor.
- https://opennms.atlassian.net/browse/LOK-2369

LOK-2369: Rename service monitor properties to metrics

---

minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/BSDV4NativeSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/BSDV6NativeSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/NativeDatagramSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/SunV4NativeSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/SunV6NativeSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/UnixV4NativeSocket.java
minion/icmp/icmp-jna/src/main/java/org/opennms/horizon/minion/jicmp/jna/UnixV6NativeSocket.java
parent-pom/pom.xml

Java Native Access (JNA) added support for Apple Silicon (M1 etc. chips) in 5.6. Latest version is 5.14.0. We are on 4.4.0.
This appears to mostly just affect ICMP on Minion. Running with JNA 4.4.0 on an M1 chip results in no ICMP being sent, but it's fixed with 5.6.0 or higher. This also gets us up to the latest version of JNA.
- https://opennms.atlassian.net/browse/LOK-2412

NMS-2412: Upgrade to JNA 5.14.0

---

ui/tests/store/Views/locationStore.test.ts

Add tests to tests/store/Views/locationStore.test.ts:
getMinionsForLocationId
getMinionCertificate
revokeMinionCertificaste
setCertificatePassword
- https://opennms.atlassian.net/browse/LOK-2398

Unit tests: locationStore part 3

---

ui/src/assets/circle.svg
ui/src/components/MonitoringPolicies/MonitoringPoliciesTable.vue
ui/src/containers/MonitoringPolicies.vue
ui/src/store/Views/monitoringPoliciesStore.ts
ui/src/types/graphql.ts
ui/tests/store/Views/nodeStatusStore.test.ts

Monitoring Policies - add table
Implement Monitoring Policies table on new page. Link: monitoring-policies-new.
get actual data
highlight row with mouse over
active vs inactive icon
Can have separate tickets for pagination and sorting.
There isn’t actually an active/inactive status yet, so just use the active icon (see CheckCircle in Feather, success color).
https://opennms.atlassian.net/browse/LOK-2378

LOK-2378: Monitoring Policies - add table

---

minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalMonitorServiceImpl.java
minion/minion-taskset/taskset-worker/src/main/java/org/opennms/horizon/minion/taskset/worker/impl/TaskExecutorLocalServiceFactoryImpl.java
minion/minion-taskset/taskset-worker/src/main/resources/OSGI-INF/blueprint/horizon-ignite.xml
minion/plugins/icmp-plugin/src/test/java/org/opennms/horizon/minion/icmp/IcmpMonitorTest.java

Current monitor execution is undefined and current implementation is unclear. Current API uses futures to delegate problem to implementation.
Implement a thread pool to be shared by all monitors and use this threadpool to execute the monitoring. Therefore alter the monitor interface to not return a future.
Implement a separate thread pool used to process and hand-off monitor results from minion to gateway.
- https://opennms.atlassian.net/browse/LOK-2360

Implement Thread Model for Monitor Execution 
